// generated by tools/ShaderGen from scene.wgsl — do not edit; wgsl-sha256: d47bfee3f1137f8a98a91ed6baf097c316d44df38cd3980d5b96d95f5147dbb4
struct FB {
    float4 fphase;
    float4 fmode;
    float4 stops[16];
};

struct U {
    row_major float4x4 vp;
    float4 eye;
    float4 clip_;
    uint hover;
    uint hover_face;
    uint flags;
    uint mode;
    uint nsel;
    float ppx;
    float ppy;
    uint pad2_;
    uint4 sel[32];
    FB f[4];
    float4 gu;
    float4 gv;
    float4 gn;
    float4 gq;
    float4 gs;
    float4 gcol;
    float4 gax;
    float4 gcu;
    float4 gcv;
    float4 gox;
    float4 goy;
    float4 gd;
    float4 gdx;
    float4 gdy;
    float4 lk;
    float4 lk1_;
    float4 key;
    float4 keyc;
    float4 bg0_;
    float4 bg1_;
    float4 bd;
    float4 bdx;
    float4 bdy;
    float4 sh[9];
    row_major float4x4 lvp;
    float4 ls;
    float4 lr;
    float4 lu;
    float4 lf;
    float4 ao;
    float4 aro;
    float4 arox;
    float4 aroy;
    float4 ard;
    float4 ardx;
    float4 ardy;
    float4 gnd;
};

struct MX {
    row_major float4x4 m;
    uint4 id;
};

struct VI {
    float3 p : LOC0;
    uint id : LOC1;
    float4 col : LOC2;
    uint face : LOC3;
};

struct VO {
    float4 pos : SV_Position;
    float3 world : LOC0;
    nointerpolation uint id : LOC1;
    float4 col : LOC2;
    nointerpolation uint face : LOC3;
};

struct PickOut {
    uint2 id : SV_Target0;
    float4 world : SV_Target1;
};

struct IVI {
    float3 p : LOC0;
    float2 uv : LOC1;
    uint id : LOC2;
    uint face : LOC3;
    float4 col : LOC4;
};

struct IVO {
    float4 pos : SV_Position;
    float3 world : LOC0;
    float2 uv : LOC1;
    nointerpolation uint id : LOC2;
    nointerpolation uint face : LOC3;
    float4 col : LOC4;
};

struct FVI {
    float3 p : LOC0;
    float3 re : LOC1;
    float3 im : LOC2;
};

struct FVO {
    float4 pos : SV_Position;
    float3 world : LOC0;
    float3 re : LOC1;
    float3 im : LOC2;
    nointerpolation uint layer : LOC3;
};

struct GVO {
    float4 pos : SV_Position;
    float2 ndc : LOC0;
};

struct GOut {
    float4 col : SV_Target0;
    float depth : SV_Depth;
};

struct AP {
    float4 a;
    float4 b;
    float4 c;
};

struct APT {
    AP e[256];
};

struct PVI {
    float3 p : LOC0;
    uint id : LOC1;
    float4 col : LOC2;
    uint face : LOC3;
    float3 n : LOC4;
    uint slot : LOC5;
};

struct PVO {
    float4 pos : SV_Position;
    float3 world : LOC0;
    nointerpolation uint id : LOC1;
    float4 col : LOC2;
    nointerpolation uint face : LOC3;
    float3 n : LOC4;
    nointerpolation uint slot : LOC5;
};

struct DVO {
    float4 pos : SV_Position;
    float3 world : LOC0;
};

struct GroundHit {
    float3 w;
    float t;
    float r;
    int _end_pad_0;
    int _end_pad_1;
    int _end_pad_2;
};

struct GrOut {
    float4 col : SV_Target0;
    float depth : SV_Depth;
};

typedef float2 ret_Constructarray16_float2_[16];
ret_Constructarray16_float2_ Constructarray16_float2_(float2 arg0, float2 arg1, float2 arg2, float2 arg3, float2 arg4, float2 arg5, float2 arg6, float2 arg7, float2 arg8, float2 arg9, float2 arg10, float2 arg11, float2 arg12, float2 arg13, float2 arg14, float2 arg15) {
    float2 ret[16] = { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15 };
    return ret;
}

static const float PI = 3.1415927;
static const float DIELECTRIC_F0_ = 0.04;
static const float MIN_ROUGHNESS = 0.045;
static const float MIN_NDOTV = 0.0001;
static const uint SLOT_MASK = 255u;
static const uint STATED_ALPHA = 256u;
static const float TONE_START = 0.76;
static const float TONE_DESAT = 0.15;
static const float TONE_TOE_BREAK = 0.08;
static const float TONE_TOE_SLOPE = 6.25;
static const float TONE_TOE_OFFSET = 0.04;
static const float SRGB_BREAK = 0.0031308;
static const float SRGB_SLOPE = 12.92;
static const float SRGB_SCALE = 1.055;
static const float SRGB_OFFSET = 0.055;
static const float SRGB_GAMMA = 2.4;
static const float SHADOW_MIN_COS = 0.2;
static const uint SHADOW_TAPS = 16u;
static const uint AO_DIRECTIONS = 8u;
static const uint AO_STEPS = 4u;
static const float AO_BIAS = 0.1;
static const float AO_MAX_PIXELS = 64.0;
static const float AO_EMPTY = 3e38;
static const float GROUND_FADE = 0.35;

cbuffer u : register(b0) { U u; }
cbuffer mx : register(b1) { MX mx; }
Texture2D<float4> img : register(t0);
SamplerState img_s : register(s0);
cbuffer ap : register(b2) { APT ap; }
Texture2D<float4> env : register(t1);
SamplerState env_s : register(s1);
Texture2D<float4> brdf : register(t2);
static float2 POISSON[16] = Constructarray16_float2_(float2(-0.94201624, -0.39906216), float2(0.9455861, -0.76890725), float2(-0.0941841, -0.9293887), float2(0.34495938, 0.2938776), float2(-0.9158858, 0.45771432), float2(-0.8154423, -0.87912464), float2(-0.38277543, 0.27676845), float2(0.974844, 0.7564838), float2(0.44323325, -0.97511554), float2(0.5374298, -0.4737342), float2(-0.2649691, -0.41893023), float2(0.79197514, 0.19090188), float2(-0.2418884, 0.99706507), float2(-0.81409955, 0.9143759), float2(0.19984126, 0.78641367), float2(0.14383161, -0.1410079));
Texture2D<float> smap : register(t3);
SamplerComparisonState smap_s : register(s2);
Texture2D<float4> aot : register(t4);
Texture2D<float4> aodepth : register(t5);
Texture2D<float4> aoraw : register(t6);

struct VertexOutput_vs {
    float3 world : LOC0;
    nointerpolation uint id_3 : LOC1;
    float4 col : LOC2;
    nointerpolation uint face_3 : LOC3;
    float4 pos_1 : SV_Position;
};

struct FragmentInput_fs_color {
    float3 world_1 : LOC0;
    nointerpolation uint id_4 : LOC1;
    float4 col_1 : LOC2;
    nointerpolation uint face_4 : LOC3;
    float4 pos_2 : SV_Position;
    bool front_4 : SV_IsFrontFace;
};

struct FragmentInput_fs_line {
    float3 world_2 : LOC0;
    nointerpolation uint id_5 : LOC1;
    float4 col_2 : LOC2;
    nointerpolation uint face_5 : LOC3;
    float4 pos_3 : SV_Position;
};

struct FragmentInput_fs_top {
    float3 world_3 : LOC0;
    nointerpolation uint id_6 : LOC1;
    float4 col_3 : LOC2;
    nointerpolation uint face_6 : LOC3;
    float4 pos_4 : SV_Position;
};

struct FragmentInput_fs_edge {
    float3 world_4 : LOC0;
    nointerpolation uint id_7 : LOC1;
    float4 col_4 : LOC2;
    nointerpolation uint face_7 : LOC3;
    float4 pos_5 : SV_Position;
};

struct FragmentInput_fs_pick {
    float3 world_5 : LOC0;
    nointerpolation uint id_8 : LOC1;
    float4 col_5 : LOC2;
    nointerpolation uint face_8 : LOC3;
    float4 pos_6 : SV_Position;
};

struct VertexOutput_vs_image {
    float3 world_6 : LOC0;
    float2 uv : LOC1;
    nointerpolation uint id_9 : LOC2;
    nointerpolation uint face_9 : LOC3;
    float4 col_6 : LOC4;
    float4 pos_7 : SV_Position;
};

struct FragmentInput_fs_image {
    float3 world_7 : LOC0;
    float2 uv_1 : LOC1;
    nointerpolation uint id_10 : LOC2;
    nointerpolation uint face_10 : LOC3;
    float4 col_7 : LOC4;
    float4 pos_8 : SV_Position;
};

struct VertexOutput_vs_field {
    float3 world_8 : LOC0;
    float3 re_1 : LOC1;
    float3 im_1 : LOC2;
    nointerpolation uint layer : LOC3;
    float4 pos_9 : SV_Position;
};

struct FragmentInput_fs_field {
    float3 world_9 : LOC0;
    float3 re_2 : LOC1;
    float3 im_2 : LOC2;
    nointerpolation uint layer_1 : LOC3;
    float4 pos_10 : SV_Position;
};

struct VertexOutput_vs_grid {
    float2 ndc_1 : LOC0;
    float4 pos_11 : SV_Position;
};

struct FragmentInput_fs_grid {
    float2 ndc_2 : LOC0;
    float4 pos_12 : SV_Position;
};

struct VertexOutput_vs_pbr {
    float3 world_10 : LOC0;
    nointerpolation uint id_11 : LOC1;
    float4 col_8 : LOC2;
    nointerpolation uint face_11 : LOC3;
    float3 n_5 : LOC4;
    nointerpolation uint slot : LOC5;
    float4 pos_13 : SV_Position;
};

struct FragmentInput_fs_pbr {
    float3 world_11 : LOC0;
    nointerpolation uint id_12 : LOC1;
    float4 col_9 : LOC2;
    nointerpolation uint face_12 : LOC3;
    float3 n_6 : LOC4;
    nointerpolation uint slot_1 : LOC5;
    float4 pos_14 : SV_Position;
    bool front_5 : SV_IsFrontFace;
};

struct FragmentInput_fs_pbr_glass {
    float3 world_12 : LOC0;
    nointerpolation uint id_13 : LOC1;
    float4 col_10 : LOC2;
    nointerpolation uint face_13 : LOC3;
    float3 n_7 : LOC4;
    nointerpolation uint slot_2 : LOC5;
    float4 pos_15 : SV_Position;
    bool front_6 : SV_IsFrontFace;
};

struct FragmentInput_fs_backdrop {
    float2 ndc_3 : LOC0;
    float4 pos_16 : SV_Position;
};

struct VertexOutput_vs_shadow {
    float3 world_13 : LOC0;
    float4 pos_17 : SV_Position;
};

struct FragmentInput_fs_depth {
    float3 world_14 : LOC0;
    float4 pos_18 : SV_Position;
};

struct FragmentInput_fs_prepass {
    float3 world_15 : LOC0;
    nointerpolation uint id_14 : LOC1;
    float4 col_11 : LOC2;
    nointerpolation uint face_14 : LOC3;
    float4 pos_19 : SV_Position;
};

struct FragmentInput_fs_ao {
    float2 ndc_4 : LOC0;
    float4 pos_20 : SV_Position;
};

struct FragmentInput_fs_ao_blur {
    float2 ndc_5 : LOC0;
    float4 pos_21 : SV_Position;
};

struct FragmentInput_fs_ground {
    float2 ndc_6 : LOC0;
    float4 pos_22 : SV_Position;
};

struct FragmentInput_fs_ground_prepass {
    float2 ndc_7 : LOC0;
    float4 pos_23 : SV_Position;
};

bool clipped(float3 w)
{
    bool local_20 = (bool)0;

    uint _e3 = u.flags;
    if (((_e3 & 1u) != 0u)) {
        float4 _e12 = u.clip_;
        float _e18 = u.clip_.w;
        local_20 = ((dot(_e12.xyz, w) + _e18) > 0.0);
    } else {
        local_20 = false;
    }
    bool _e23 = local_20;
    return _e23;
}

uint naga_div(uint lhs, uint rhs) {
    return lhs / (rhs == 0u ? 1u : rhs);
}

uint2 sel_entry(uint k_3)
{
    uint4 q = u.sel[naga_div(k_3, 2u)];
    if (((k_3 & 1u) == 0u)) {
        return q.xy;
    }
    return q.zw;
}

bool is_selected(uint id, uint face)
{
    uint k_4 = 0u;
    bool local_21 = (bool)0;
    bool local_22 = (bool)0;

    uint2 loop_bound = uint2(4294967295u, 4294967295u);
    bool loop_init = true;
    while(true) {
        if (all(loop_bound == uint2(0u, 0u))) { break; }
        loop_bound -= uint2(loop_bound.y == 0u, 1u);
        if (!loop_init) {
            uint _e30 = k_4;
            k_4 = (_e30 + 1u);
        }
        loop_init = false;
        uint _e4 = k_4;
        uint _e7 = u.nsel;
        if ((_e4 < _e7)) {
        } else {
            break;
        }
        {
            uint _e9 = k_4;
            const uint2 _e10 = sel_entry(_e9);
            if ((_e10.x == id)) {
                uint _e17 = u.mode;
                if (!((_e17 != 1u))) {
                    local_22 = (_e10.y == face);
                } else {
                    local_22 = true;
                }
                bool _e26 = local_22;
                local_21 = _e26;
            } else {
                local_21 = false;
            }
            bool _e28 = local_21;
            if (_e28) {
                return true;
            }
        }
    }
    return false;
}

float3 highlight(float3 rgb_2, uint id_1, uint face_1)
{
    float3 c = (float3)0;
    bool local_23 = (bool)0;

    c = rgb_2;
    if ((id_1 == 0u)) {
        float3 _e6 = c;
        return _e6;
    }
    uint _e9 = u.mode;
    if ((_e9 == 0u)) {
        uint _e14 = u.hover;
        if ((id_1 == _e14)) {
            float3 _e16 = c;
            c = lerp(_e16, float3(0.2, 0.9, 1.0), 0.45);
        }
    } else {
        uint _e25 = u.mode;
        if ((_e25 == 1u)) {
            uint _e30 = u.hover;
            if ((id_1 == _e30)) {
                uint _e36 = u.hover_face;
                local_23 = (face_1 == _e36);
            } else {
                local_23 = false;
            }
            bool _e39 = local_23;
            if (_e39) {
                float3 _e40 = c;
                c = lerp(_e40, float3(1.0, 1.0, 1.0), 0.35);
            }
            const bool _e47 = is_selected(id_1, face_1);
            if (_e47) {
                float3 _e48 = c;
                c = lerp(_e48, float3(1.0, 0.35, 1.0), 0.6);
            }
        }
    }
    float3 _e55 = c;
    return _e55;
}

uint naga_f2u32(float value) {
    return uint(clamp(value, 0.0, 4294967000.0));
}

float field_value(float3 re, float3 im, uint l)
{
    float c_4 = u.f[l].fphase.x;
    float s_1 = u.f[l].fphase.y;
    float _e20 = u.f[l].fmode.x;
    uint mode = naga_f2u32((_e20 + 0.5));
    if ((mode == 0u)) {
        return sqrt((dot(re, re) + dot(im, im)));
    }
    if ((mode == 1u)) {
        return length(((re * c_4) - (im * s_1)));
    }
    if ((mode == 2u)) {
        return re.x;
    }
    if ((mode == 3u)) {
        return ((re.x * c_4) - (im.x * s_1));
    }
    return sqrt(((re.x * re.x) + (im.x * im.x)));
}

float3 colour_map(float t, uint l_1)
{
    float3 rgb_3 = (float3)0;
    uint k_5 = 1u;
    bool local_24 = (bool)0;

    float _e7 = u.f[l_1].fmode.z;
    uint n_8 = naga_f2u32((_e7 + 0.5));
    float4 _e16 = u.f[l_1].stops[0];
    rgb_3 = _e16.yzw;
    uint2 loop_bound_1 = uint2(4294967295u, 4294967295u);
    bool loop_init_1 = true;
    while(true) {
        if (all(loop_bound_1 == uint2(0u, 0u))) { break; }
        loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
        if (!loop_init_1) {
            uint _e64 = k_5;
            k_5 = (_e64 + 1u);
        }
        loop_init_1 = false;
        uint _e21 = k_5;
        if ((_e21 < n_8)) {
        } else {
            break;
        }
        {
            uint _e27 = k_5;
            float4 a_6 = u.f[l_1].stops[(_e27 - 1u)];
            uint _e36 = k_5;
            float4 b_1 = u.f[l_1].stops[_e36];
            if (!((t <= b_1.x))) {
                uint _e44 = k_5;
                local_24 = (_e44 == (n_8 - 1u));
            } else {
                local_24 = true;
            }
            bool _e49 = local_24;
            if (_e49) {
                float w_4 = clamp(((t - a_6.x) / max((b_1.x - a_6.x), 1e-6)), 0.0, 1.0);
                rgb_3 = lerp(a_6.yzw, b_1.yzw, w_4);
                break;
            }
        }
    }
    float3 _e67 = rgb_3;
    return _e67;
}

float grid_weight(float c_1, float m)
{
    return ((0.45 * clamp(((c_1 - 6.0) / 8.0), 0.0, 1.0)) + (0.55 * clamp(((c_1 - (6.0 * m)) / (8.0 * m)), 0.0, 1.0)));
}

float grid_on(float2 p, float2 pf, float s, float2 ph)
{
    float2 a_7 = ((p + ph) / (s).xx);
    float2 d_2 = (abs((frac((a_7 - (0.5).xx)) - (0.5).xx)) / max((pf / (s).xx), float2(1e-12, 1e-12)));
    return (1.0 - min(min(d_2.x, d_2.y), 1.0));
}

float3 env_dir(float3 w_1)
{
    float _e4 = u.lk.z;
    float _e10 = u.lk.w;
    float _e17 = u.lk.w;
    float _e24 = u.lk.z;
    return float3(((_e4 * w_1.x) + (_e10 * w_1.y)), ((-(_e17) * w_1.x) + (_e24 * w_1.y)), w_1.z);
}

float2 oct_uv(float3 d_1)
{
    float2 p_1 = (float2)0;

    float s_2 = ((abs(d_1.x) + abs(d_1.y)) + abs(d_1.z));
    p_1 = (d_1.xy / (s_2).xx);
    if ((d_1.z < 0.0)) {
        float2 _e19 = p_1;
        float2 _e29 = p_1;
        p_1 = ((float2(1.0, 1.0) - abs(_e19.yx)) * ((_e29 >= float2(0.0, 0.0)) ? float2(1.0, 1.0) : float2(-1.0, -1.0)));
    }
    float2 _e36 = p_1;
    return ((_e36 * 0.5) + float2(0.5, 0.5));
}

float3 env_radiance(float3 w_2, float rough)
{
    const float3 _e4 = env_dir(w_2);
    const float2 _e5 = oct_uv(_e4);
    float _e9 = u.lk1_.y;
    float4 _e11 = env.SampleLevel(env_s, _e5, (rough * _e9));
    return _e11.xyz;
}

float3 irradiance(float3 n_1)
{
    const float3 _e1 = env_dir(n_1);
    float4 _e5 = u.sh[0];
    float4 _e10 = u.sh[1];
    float4 _e18 = u.sh[2];
    float4 _e26 = u.sh[3];
    float4 _e34 = u.sh[4];
    float4 _e44 = u.sh[5];
    float4 _e54 = u.sh[6];
    float4 _e68 = u.sh[7];
    float4 _e78 = u.sh[8];
    return ((((((((_e5.xyz + (_e10.xyz * _e1.y)) + (_e18.xyz * _e1.z)) + (_e26.xyz * _e1.x)) + (_e34.xyz * (_e1.x * _e1.y))) + (_e44.xyz * (_e1.y * _e1.z))) + (_e54.xyz * (((3.0 * _e1.z) * _e1.z) - 1.0))) + (_e68.xyz * (_e1.x * _e1.z))) + (_e78.xyz * ((_e1.x * _e1.x) - (_e1.y * _e1.y))));
}

float2 brdf_lut(float nv, float rough_1)
{
    float4 _e12 = brdf.SampleLevel(env_s, float2(clamp(nv, 0.0, 1.0), clamp(rough_1, 0.0, 1.0)), 0.0);
    return _e12.xy;
}

float ggx_d(float nh, float a_2)
{
    float a2_ = (a_2 * a_2);
    float f = (((nh * nh) * (a2_ - 1.0)) + 1.0);
    return (a2_ / ((PI * f) * f));
}

float smith_v(float nv_1, float nl, float a_3)
{
    float a2_1 = (a_3 * a_3);
    float gv = (nl * sqrt((((nv_1 * nv_1) * (1.0 - a2_1)) + a2_1)));
    float gl = (nv_1 * sqrt((((nl * nl) * (1.0 - a2_1)) + a2_1)));
    return (0.5 / max((gv + gl), 1e-7));
}

float3 schlick3_(float3 f0_, float vh)
{
    float k_7 = pow((1.0 - clamp(vh, 0.0, 1.0)), 5.0);
    return (f0_ + ((float3(1.0, 1.0, 1.0) - f0_) * k_7));
}

float schlick1_(float f0_1, float vh_1)
{
    return (f0_1 + ((1.0 - f0_1) * pow((1.0 - clamp(vh_1, 0.0, 1.0)), 5.0)));
}

float3 pbr_neutral(float3 c0_)
{
    float3 c_2 = (float3)0;

    c_2 = c0_;
    float _e3 = c_2.x;
    float _e5 = c_2.y;
    float _e7 = c_2.z;
    float x_1 = min(_e3, min(_e5, _e7));
    float offset = ((x_1 < TONE_TOE_BREAK) ? (x_1 - ((TONE_TOE_SLOPE * x_1) * x_1)) : TONE_TOE_OFFSET);
    float3 _e18 = c_2;
    c_2 = (_e18 - float3(offset, offset, offset));
    float _e22 = c_2.x;
    float _e24 = c_2.y;
    float _e26 = c_2.z;
    float peak = max(_e22, max(_e24, _e26));
    if ((peak < TONE_START)) {
        float3 _e31 = c_2;
        return _e31;
    }
    float np = (1.0 - ((0.24000001 * 0.24000001) / ((peak + 0.24000001) - TONE_START)));
    float3 _e40 = c_2;
    c_2 = (_e40 * (np / peak));
    float g = (1.0 - (1.0 / ((TONE_DESAT * (peak - np)) + 1.0)));
    float3 _e52 = c_2;
    return lerp(_e52, float3(np, np, np), g);
}

float srgb1_(float x)
{
    float c_5 = clamp(x, 0.0, 1.0);
    return ((c_5 <= SRGB_BREAK) ? (c_5 * SRGB_SLOPE) : ((SRGB_SCALE * pow(c_5, 0.41666666)) - SRGB_OFFSET));
}

float3 display(float3 lin)
{
    float _e4 = u.lk.x;
    const float3 _e11 = pbr_neutral(max((lin * _e4), float3(0.0, 0.0, 0.0)));
    const float _e13 = srgb1_(_e11.x);
    const float _e15 = srgb1_(_e11.y);
    const float _e17 = srgb1_(_e11.z);
    return float3(_e13, _e15, _e17);
}

float3 highlight_pm(float3 rgb_4, float a_4, uint id_2, uint face_2)
{
    float3 c_3 = (float3)0;
    bool local_25 = (bool)0;

    c_3 = rgb_4;
    if ((id_2 == 0u)) {
        float3 _e7 = c_3;
        return _e7;
    }
    uint _e10 = u.mode;
    if ((_e10 == 0u)) {
        uint _e15 = u.hover;
        if ((id_2 == _e15)) {
            float3 _e17 = c_3;
            c_3 = lerp(_e17, (float3(0.2, 0.9, 1.0) * a_4), 0.45);
        }
    } else {
        uint _e27 = u.mode;
        if ((_e27 == 1u)) {
            uint _e32 = u.hover;
            if ((id_2 == _e32)) {
                uint _e38 = u.hover_face;
                local_25 = (face_2 == _e38);
            } else {
                local_25 = false;
            }
            bool _e41 = local_25;
            if (_e41) {
                float3 _e42 = c_3;
                c_3 = lerp(_e42, (float3(1.0, 1.0, 1.0) * a_4), 0.35);
            }
            const bool _e50 = is_selected(id_2, face_2);
            if (_e50) {
                float3 _e51 = c_3;
                c_3 = lerp(_e51, (float3(1.0, 0.35, 1.0) * a_4), 0.6);
            }
        }
    }
    float3 _e59 = c_3;
    return _e59;
}

float shadow_vis(float3 w_3, float3 n_2)
{
    bool local_26 = (bool)0;
    bool local_27 = (bool)0;
    bool local_28 = (bool)0;
    bool local_29 = (bool)0;
    float lit_ = 0.0;
    uint k_6 = 0u;

    float _e5 = u.ls.x;
    if ((_e5 < 0.5)) {
        return 1.0;
    }
    float4x4 _e11 = u.lvp;
    float _e15 = u.lr.w;
    float4 c_6 = mul(float4((w_3 + (n_2 * _e15)), 1.0), _e11);
    float2 uv_2 = float2(((c_6.x * 0.5) + 0.5), (0.5 - (c_6.y * 0.5)));
    if (!((uv_2.x < 0.0))) {
        local_26 = (uv_2.x > 1.0);
    } else {
        local_26 = true;
    }
    bool _e42 = local_26;
    if (!(_e42)) {
        local_27 = (uv_2.y < 0.0);
    } else {
        local_27 = true;
    }
    bool _e50 = local_27;
    if (!(_e50)) {
        local_28 = (uv_2.y > 1.0);
    } else {
        local_28 = true;
    }
    bool _e58 = local_28;
    if (!(_e58)) {
        local_29 = (c_6.z <= 0.0);
    } else {
        local_29 = true;
    }
    bool _e66 = local_29;
    if (_e66) {
        return 1.0;
    }
    float4 _e70 = u.lf;
    float nf = min(dot(n_2, _e70.xyz), -0.2);
    float4 _e77 = u.lr;
    float4 _e82 = u.lu;
    float2 g_1 = (-(float2(dot(n_2, _e77.xyz), dot(n_2, _e82.xyz))) / (nf).xx);
    float z = min(c_6.z, 1.0);
    uint2 loop_bound_2 = uint2(4294967295u, 4294967295u);
    bool loop_init_2 = true;
    while(true) {
        if (all(loop_bound_2 == uint2(0u, 0u))) { break; }
        loop_bound_2 -= uint2(loop_bound_2.y == 0u, 1u);
        if (!loop_init_2) {
            uint _e132 = k_6;
            k_6 = (_e132 + 1u);
        }
        loop_init_2 = false;
        uint _e96 = k_6;
        if ((_e96 < SHADOW_TAPS)) {
        } else {
            break;
        }
        {
            uint _e100 = k_6;
            float2 _e102 = POISSON[min(uint(_e100), 15u)];
            float _e106 = u.ls.y;
            float2 o_10 = (_e102 * _e106);
            float _e115 = u.ls.z;
            float2 t_1 = (uv_2 + (float2(o_10.x, -(o_10.y)) * _e115));
            float _e118 = lit_;
            float _e125 = u.ls.w;
            float _e130 = smap.SampleCmpLevelZero(smap_s, t_1, min((z + (dot(g_1, o_10) * _e125)), 1.0));
            lit_ = (_e118 + _e130);
        }
    }
    float _e135 = lit_;
    return (_e135 / 16.0);
}

float4 pbr(PVO i_17, bool front_3, float occ_1)
{
    float3 n_3 = (float3)0;
    float3 surface = (float3)0;
    bool local_30 = (bool)0;
    float vis = 1.0;
    float nh_1 = 0.0;
    float vh_2 = 0.0;
    float ad = (float)0;
    float3 coat = (float3)0;
    float ac = (float)0;
    float alpha_1 = 1.0;
    float cov = (float)0;
    bool local_31 = (bool)0;

    AP m_1 = ap.e[(i_17.slot & SLOT_MASK)];
    float4 _e12 = u.eye;
    float3 v_6 = normalize((_e12.xyz - i_17.world));
    n_3 = normalize(i_17.n);
    if (!(front_3)) {
        uint _e23 = u.flags;
        if (((_e23 & 2u) != 0u)) {
            n_3 = v_6;
        } else {
            float3 _e28 = n_3;
            n_3 = -(_e28);
        }
    }
    float3 _e30 = n_3;
    float nv_2 = max(dot(_e30, v_6), MIN_NDOTV);
    float3 base = m_1.a.xyz;
    float metal = clamp(m_1.a.w, 0.0, 1.0);
    float rough_2 = clamp(m_1.b.x, 0.0, 1.0);
    float t_2 = clamp(m_1.b.y, 0.0, 1.0);
    float fr0_ = ((m_1.b.z - 1.0) / (m_1.b.z + 1.0));
    float3 f0_2 = lerp(float3((fr0_ * fr0_), (fr0_ * fr0_), (fr0_ * fr0_)), base, metal);
    const float2 _e65 = brdf_lut(nv_2, rough_2);
    float3 spec_albedo = ((f0_2 * _e65.x) + float3(_e65.y, _e65.y, _e65.y));
    float3 _e73 = n_3;
    float3 _e77 = n_3;
    float3 r_1 = (((2.0 * dot(_e73, v_6)) * _e77) - v_6);
    const float3 _e80 = env_radiance(r_1, rough_2);
    float _e84 = u.lk.y;
    float3 reflected = (_e80 * _e84);
    float3 _e86 = n_3;
    const float3 _e87 = irradiance(_e86);
    float _e91 = u.lk.y;
    float3 irr = (_e87 * _e91);
    surface = (((reflected * spec_albedo) + ((((((float3(1.0, 1.0, 1.0) - spec_albedo) * (1.0 - metal)) * (1.0 - t_2)) * base) * irr) / (3.1415927).xxx)) * occ_1);
    float4 _e115 = u.key;
    float3 l_3 = _e115.xyz;
    float3 _e117 = n_3;
    float nl_1 = dot(_e117, l_3);
    if ((nl_1 > 0.0)) {
        float4 _e125 = u.keyc;
        float4 _e129 = u.keyc;
        local_30 = (dot(_e125.xyz, _e129.xyz) > 0.0);
    } else {
        local_30 = false;
    }
    bool keyon = local_30;
    if (keyon) {
        float3 _e139 = n_3;
        const float _e140 = shadow_vis(i_17.world, _e139);
        vis = _e140;
    }
    if (keyon) {
        float3 h_2 = normalize((l_3 + v_6));
        float3 _e147 = n_3;
        nh_1 = max(dot(_e147, h_2), 0.0);
        vh_2 = max(dot(v_6, h_2), 0.0);
        ad = max(rough_2, MIN_ROUGHNESS);
        float _e157 = ad;
        float _e158 = ad;
        ad = (_e157 * _e158);
        float _e160 = vh_2;
        const float3 _e161 = schlick3_(f0_2, _e160);
        float _e162 = nh_1;
        float _e163 = ad;
        const float _e164 = ggx_d(_e162, _e163);
        float _e165 = ad;
        const float _e166 = smith_v(nv_2, nl_1, _e165);
        float3 lobe = (_e161 * (_e164 * _e166));
        float3 body = (((((float3(1.0, 1.0, 1.0) - _e161) * (1.0 - metal)) * (1.0 - t_2)) * base) / (3.1415927).xxx);
        float3 _e184 = surface;
        float4 _e188 = u.keyc;
        float _e194 = u.lk.y;
        float _e197 = vis;
        surface = (_e184 + (((((lobe + body) * _e188.xyz) * _e194) * nl_1) * _e197));
    }
    float cc = clamp(m_1.b.w, 0.0, 1.0);
    if ((cc > 0.0)) {
        float ccr = clamp(m_1.c.x, 0.0, 1.0);
        const float2 _e212 = brdf_lut(nv_2, ccr);
        float coat_albedo = ((DIELECTRIC_F0_ * _e212.x) + _e212.y);
        const float3 _e218 = env_radiance(r_1, ccr);
        float _e222 = u.lk.y;
        coat = (((_e218 * _e222) * coat_albedo) * occ_1);
        if (keyon) {
            ac = max(ccr, MIN_ROUGHNESS);
            float _e230 = ac;
            float _e231 = ac;
            ac = (_e230 * _e231);
            float3 _e233 = coat;
            float4 _e236 = u.keyc;
            float _e241 = u.lk.y;
            float _e244 = vh_2;
            const float _e245 = schlick1_(DIELECTRIC_F0_, _e244);
            float _e246 = nh_1;
            float _e247 = ac;
            const float _e248 = ggx_d(_e246, _e247);
            float _e250 = ac;
            const float _e251 = smith_v(nv_2, nl_1, _e250);
            float _e254 = vis;
            coat = (_e233 + ((_e236.xyz * _e241) * ((((_e245 * _e248) * _e251) * nl_1) * _e254)));
        }
        float3 _e258 = surface;
        float3 _e263 = coat;
        surface = ((_e258 * (1.0 - (cc * coat_albedo))) + (_e263 * cc));
    }
    if ((t_2 > 0.0)) {
        float3 att = m_1.c.yzw;
        float fs = (((spec_albedo.x + spec_albedo.y) + spec_albedo.z) / 3.0);
        float tau = (((att.x + att.y) + att.z) / 3.0);
        float through = (t_2 * (1.0 - fs));
        alpha_1 = (1.0 - (through * tau));
        float3 _e292 = surface;
        surface = (_e292 + (((((through * (1.0 - tau)) * att) * irr) / (3.1415927).xxx) * occ_1));
    }
    cov = (((i_17.slot & STATED_ALPHA) != 0u) ? i_17.col.w : 1.0);
    uint _e315 = u.mode;
    if ((_e315 == 0u)) {
        const bool _e322 = is_selected(i_17.id, 0u);
        local_31 = _e322;
    } else {
        local_31 = false;
    }
    bool _e324 = local_31;
    if (_e324) {
        float _e325 = cov;
        cov = min(_e325, 0.5);
    }
    float _e328 = alpha_1;
    float _e329 = cov;
    float a_8 = (_e328 * _e329);
    float3 _e331 = surface;
    const float3 _e332 = display(_e331);
    float _e333 = cov;
    const float3 _e337 = highlight_pm((_e332 * _e333), a_8, i_17.id, i_17.face);
    return float4(_e337, a_8);
}

int2 naga_f2i32(float2 value) {
    return int2(clamp(value, -2147483600.0, 2147483500.0));
}

float occlusion_at(float2 pos)
{
    float _e4 = u.ao.x;
    if ((_e4 < 0.5)) {
        return 1.0;
    }
    float4 _e11 = aot.Load(int3(naga_f2i32(pos), int(0)));
    return _e11.x;
}

int2 ao_clamp(int2 xy, int2 size)
{
    return clamp(xy, int2(int(0), int(0)), asint(asuint(size) - asuint(int2(int(1), int(1)))));
}

float4 ao_point(int2 xy_1, int2 size_1)
{
    float4 _e4 = aodepth.Load(int3(xy_1, int(0)));
    float t_3 = _e4.x;
    if ((t_3 > 1.5e38)) {
        return float4(0.0, 0.0, 0.0, 0.0);
    }
    float2 s_3 = float2(size_1);
    float x_2 = ((((float(xy_1.x) + 0.5) / s_3.x) * 2.0) - 1.0);
    float y = (1.0 - (((float(xy_1.y) + 0.5) / s_3.y) * 2.0));
    float4 _e36 = u.aro;
    float4 _e40 = u.arox;
    float4 _e46 = u.aroy;
    float3 o_11 = ((_e36.xyz + (_e40.xyz * x_2)) + (_e46.xyz * y));
    float4 _e52 = u.ard;
    float4 _e56 = u.ardx;
    float4 _e62 = u.ardy;
    float3 d_3 = ((_e52.xyz + (_e56.xyz * x_2)) + (_e62.xyz * y));
    return float4((o_11 + (d_3 * t_3)), 1.0);
}

float3 ao_normal(int2 xy_2, int2 size_2, float3 p_2)
{
    float4 l_2 = float4(0.0, 0.0, 0.0, 0.0);
    float4 r = (float4)0;
    float4 a_5 = (float4)0;
    float4 b = (float4)0;
    float3 dx = float3(0.0, 0.0, 0.0);
    bool local_32 = (bool)0;
    bool local_33 = (bool)0;
    float3 dy = float3(0.0, 0.0, 0.0);
    bool local_34 = (bool)0;
    bool local_35 = (bool)0;
    float3 n_4 = (float3)0;

    float4 _e9 = l_2;
    r = _e9;
    float4 _e11 = l_2;
    a_5 = _e11;
    float4 _e13 = l_2;
    b = _e13;
    if ((xy_2.x > int(0))) {
        const float4 _e22 = ao_point(asint(asuint(xy_2) - asuint(int2(int(1), int(0)))), size_2);
        l_2 = _e22;
    }
    if ((xy_2.x < asint(asuint(size_2.x) - asuint(int(1))))) {
        const float4 _e32 = ao_point(asint(asuint(xy_2) + asuint(int2(int(1), int(0)))), size_2);
        r = _e32;
    }
    if ((xy_2.y > int(0))) {
        const float4 _e40 = ao_point(asint(asuint(xy_2) - asuint(int2(int(0), int(1)))), size_2);
        a_5 = _e40;
    }
    if ((xy_2.y < asint(asuint(size_2.y) - asuint(int(1))))) {
        const float4 _e50 = ao_point(asint(asuint(xy_2) + asuint(int2(int(0), int(1)))), size_2);
        b = _e50;
    }
    float _e57 = r.w;
    if ((_e57 > 0.0)) {
        float _e63 = l_2.w;
        if (!((_e63 == 0.0))) {
            float4 _e69 = r;
            float4 _e73 = l_2;
            local_33 = (length((_e69.xyz - p_2)) < length((p_2 - _e73.xyz)));
        } else {
            local_33 = true;
        }
        bool _e79 = local_33;
        local_32 = _e79;
    } else {
        local_32 = false;
    }
    bool _e81 = local_32;
    if (_e81) {
        float4 _e82 = r;
        dx = (_e82.xyz - p_2);
    } else {
        float _e86 = l_2.w;
        if ((_e86 > 0.0)) {
            float4 _e89 = l_2;
            dx = (p_2 - _e89.xyz);
        }
    }
    float _e98 = b.w;
    if ((_e98 > 0.0)) {
        float _e104 = a_5.w;
        if (!((_e104 == 0.0))) {
            float4 _e110 = b;
            float4 _e114 = a_5;
            local_35 = (length((_e110.xyz - p_2)) < length((p_2 - _e114.xyz)));
        } else {
            local_35 = true;
        }
        bool _e120 = local_35;
        local_34 = _e120;
    } else {
        local_34 = false;
    }
    bool _e122 = local_34;
    if (_e122) {
        float4 _e123 = b;
        dy = (_e123.xyz - p_2);
    } else {
        float _e127 = a_5.w;
        if ((_e127 > 0.0)) {
            float4 _e130 = a_5;
            dy = (p_2 - _e130.xyz);
        }
    }
    float3 _e133 = dx;
    float3 _e134 = dy;
    n_4 = cross(_e133, _e134);
    float4 _e139 = u.ard;
    float3 ray = _e139.xyz;
    float3 _e141 = n_4;
    float3 _e142 = n_4;
    if ((dot(_e141, _e142) < 1e-36)) {
        return -(ray);
    }
    float3 _e147 = n_4;
    n_4 = normalize(_e147);
    float3 _e149 = n_4;
    if ((dot(_e149, ray) > 0.0)) {
        float3 _e153 = n_4;
        n_4 = -(_e153);
    }
    float3 _e155 = n_4;
    return _e155;
}

GroundHit ground_hit(float2 ndc)
{
    GroundHit h_1 = (GroundHit)0;
    bool local_36 = (bool)0;
    bool local_37 = (bool)0;

    h_1.r = 2.0;
    float4 _e6 = u.aro;
    float4 _e10 = u.arox;
    float4 _e17 = u.aroy;
    float3 o_12 = ((_e6.xyz + (_e10.xyz * ndc.x)) + (_e17.xyz * ndc.y));
    float4 _e24 = u.ard;
    float4 _e28 = u.ardx;
    float4 _e35 = u.ardy;
    float3 d_4 = ((_e24.xyz + (_e28.xyz * ndc.x)) + (_e35.xyz * ndc.y));
    if (!((abs(d_4.z) < 1e-30))) {
        float _e50 = u.gnd.w;
        local_36 = (_e50 <= 0.0);
    } else {
        local_36 = true;
    }
    bool _e54 = local_36;
    if (_e54) {
        GroundHit _e55 = h_1;
        const GroundHit groundhit = _e55;
        return groundhit;
    }
    float _e60 = u.gnd.z;
    h_1.t = ((_e60 - o_12.z) / d_4.z);
    float _e67 = h_1.t;
    h_1.w = (o_12 + (d_4 * _e67));
    float4 _e72 = u.ardx;
    float4 _e76 = u.ardx;
    if ((dot(_e72.xyz, _e76.xyz) > 0.0)) {
        float _e84 = h_1.t;
        local_37 = (_e84 <= 0.0);
    } else {
        local_37 = false;
    }
    bool _e88 = local_37;
    if (_e88) {
        GroundHit _e89 = h_1;
        const GroundHit groundhit_1 = _e89;
        return groundhit_1;
    }
    float3 _e92 = h_1.w;
    float4 _e96 = u.gnd;
    float _e103 = u.gnd.w;
    h_1.r = (length((_e92.xy - _e96.xy)) / _e103);
    GroundHit _e105 = h_1;
    const GroundHit groundhit_2 = _e105;
    return groundhit_2;
}

VertexOutput_vs vs(VI v)
{
    VO o = (VO)0;

    float4x4 _e4 = mx.m;
    float3 p_3 = mul(float4(v.p, 1.0), _e4).xyz;
    float4x4 _e13 = u.vp;
    o.pos = mul(float4(p_3, 1.0), _e13);
    uint _e20 = mx.id.y;
    if ((_e20 != 0u)) {
        uint _e26 = mx.id.y;
        float _e32 = u.ppx;
        uint _e37 = mx.id.y;
        float _e45 = u.ppy;
        float2 px = float2((float((_e26 & 1u)) * _e32), (float(((_e37 >> 1u) & 1u)) * _e45));
        float4 _e50 = o.pos;
        float _e54 = o.pos.w;
        float4 _e58 = o.pos;
        o.pos = float4((_e50.xy + (px * _e54)), _e58.zw);
    }
    o.world = p_3;
    uint _e67 = mx.id.x;
    o.id = (v.id + _e67);
    o.col = v.col;
    o.face = v.face;
    VO _e73 = o;
    const VO vo = _e73;
    const VertexOutput_vs vo_1 = { vo.world, vo.id, vo.col, vo.face, vo.pos };
    return vo_1;
}

float4 fs_color(FragmentInput_fs_color fragmentinput_fs_color) : SV_Target0
{
    VO i = { fragmentinput_fs_color.pos_2, fragmentinput_fs_color.world_1, fragmentinput_fs_color.id_4, fragmentinput_fs_color.col_1, fragmentinput_fs_color.face_4 };
    bool front = fragmentinput_fs_color.front_4;
    bool local = (bool)0;
    bool local_1 = (bool)0;
    bool local_2 = (bool)0;
    bool local_3 = (bool)0;
    bool local_4 = (bool)0;
    bool local_5 = (bool)0;
    bool local_6 = (bool)0;
    float3 rgb = (float3)0;
    bool local_7 = (bool)0;
    float a = (float)0;
    bool local_8 = (bool)0;

    float3 _e3 = ddx(i.world);
    float3 _e5 = ddy(i.world);
    float3 n_9 = normalize(cross(_e3, _e5));
    const bool _e9 = clipped(i.world);
    if (_e9) {
        discard;
    }
    if ((i.col.w == 0.0)) {
        if ((i.id != 0u)) {
            uint _e21 = u.mode;
            local = (_e21 == 0u);
        } else {
            local = false;
        }
        bool _e25 = local;
        if (_e25) {
            uint _e31 = u.hover;
            local_1 = (i.id == _e31);
        } else {
            local_1 = false;
        }
        bool _e34 = local_1;
        if (_e34) {
            return float4(0.2, 0.9, 1.0, 0.18);
        }
        if ((i.id != 0u)) {
            uint _e47 = u.mode;
            local_2 = (_e47 == 1u);
        } else {
            local_2 = false;
        }
        bool _e51 = local_2;
        if (_e51) {
            const bool _e56 = is_selected(i.id, i.face);
            local_3 = _e56;
        } else {
            local_3 = false;
        }
        bool _e58 = local_3;
        if (_e58) {
            return float4(1.0, 0.35, 1.0, 0.4);
        }
        if ((i.id != 0u)) {
            uint _e71 = u.mode;
            local_4 = (_e71 == 1u);
        } else {
            local_4 = false;
        }
        bool _e75 = local_4;
        if (_e75) {
            uint _e81 = u.hover;
            local_5 = (i.id == _e81);
        } else {
            local_5 = false;
        }
        bool _e84 = local_5;
        if (_e84) {
            uint _e90 = u.hover_face;
            local_6 = (i.face == _e90);
        } else {
            local_6 = false;
        }
        bool _e93 = local_6;
        if (_e93) {
            return float4(1.0, 1.0, 1.0, 0.25);
        }
        discard;
    }
    float4 _e101 = u.eye;
    float d_5 = abs(dot(n_9, normalize((_e101.xyz - i.world))));
    rgb = (i.col.xyz * (0.3 + (0.7 * d_5)));
    if (!(front)) {
        uint _e121 = u.flags;
        local_7 = ((_e121 & 2u) != 0u);
    } else {
        local_7 = false;
    }
    bool _e127 = local_7;
    if (_e127) {
        rgb = (i.col.xyz * 0.8);
    }
    a = i.col.w;
    uint _e137 = u.mode;
    if ((_e137 == 0u)) {
        const bool _e144 = is_selected(i.id, 0u);
        local_8 = _e144;
    } else {
        local_8 = false;
    }
    bool _e146 = local_8;
    if (_e146) {
        float _e147 = a;
        a = min(_e147, 0.5);
    }
    float3 _e150 = rgb;
    const float3 _e153 = highlight(_e150, i.id, i.face);
    float _e154 = a;
    return float4(_e153, _e154);
}

float4 fs_line(FragmentInput_fs_line fragmentinput_fs_line) : SV_Target0
{
    VO i_1 = { fragmentinput_fs_line.pos_3, fragmentinput_fs_line.world_2, fragmentinput_fs_line.id_5, fragmentinput_fs_line.col_2, fragmentinput_fs_line.face_5 };
    return float4(i_1.col.xyz, 1.0);
}

float4 fs_top(FragmentInput_fs_top fragmentinput_fs_top) : SV_Target0
{
    VO i_2 = { fragmentinput_fs_top.pos_4, fragmentinput_fs_top.world_3, fragmentinput_fs_top.id_6, fragmentinput_fs_top.col_3, fragmentinput_fs_top.face_6 };
    bool local_9 = (bool)0;
    bool local_10 = (bool)0;

    const bool _e2 = clipped(i_2.world);
    if (!(_e2)) {
        uint _e8 = u.mode;
        local_9 = (_e8 != 1u);
    } else {
        local_9 = true;
    }
    bool _e12 = local_9;
    if (!(_e12)) {
        const bool _e18 = is_selected(i_2.id, i_2.face);
        local_10 = !(_e18);
    } else {
        local_10 = true;
    }
    bool _e21 = local_10;
    if (_e21) {
        discard;
    }
    return float4(1.0, 0.35, 1.0, 0.45);
}

float4 fs_edge(FragmentInput_fs_edge fragmentinput_fs_edge) : SV_Target0
{
    VO i_3 = { fragmentinput_fs_edge.pos_5, fragmentinput_fs_edge.world_4, fragmentinput_fs_edge.id_7, fragmentinput_fs_edge.col_4, fragmentinput_fs_edge.face_7 };
    bool show = false;
    bool local_11 = (bool)0;

    const bool _e2 = clipped(i_3.world);
    if (_e2) {
        discard;
    }
    uint _e7 = u.mode;
    if ((_e7 == 0u)) {
        const bool _e12 = is_selected(i_3.id, 0u);
        show = _e12;
    }
    uint _e15 = u.mode;
    if ((_e15 == 1u)) {
        const bool _e22 = is_selected(i_3.id, (i_3.face & 65535u));
        if (!(_e22)) {
            const bool _e30 = is_selected(i_3.id, (i_3.face >> 16u));
            local_11 = _e30;
        } else {
            local_11 = true;
        }
        bool _e32 = local_11;
        show = _e32;
    }
    bool _e33 = show;
    if (!(_e33)) {
        discard;
    }
    return float4(1.0, 0.35, 1.0, 1.0);
}

PickOut fs_pick(FragmentInput_fs_pick fragmentinput_fs_pick)
{
    VO i_4 = { fragmentinput_fs_pick.pos_6, fragmentinput_fs_pick.world_5, fragmentinput_fs_pick.id_8, fragmentinput_fs_pick.col_5, fragmentinput_fs_pick.face_8 };
    PickOut o_1 = (PickOut)0;

    const bool _e2 = clipped(i_4.world);
    if (_e2) {
        discard;
    }
    o_1.id = uint2(i_4.id, i_4.face);
    o_1.world = float4(i_4.world, 1.0);
    PickOut _e12 = o_1;
    const PickOut pickout = _e12;
    return pickout;
}

VertexOutput_vs_image vs_image(IVI v_1)
{
    IVO o_2 = (IVO)0;

    float4x4 _e4 = mx.m;
    float3 p_4 = mul(float4(v_1.p, 1.0), _e4).xyz;
    float4x4 _e13 = u.vp;
    o_2.pos = mul(float4(p_4, 1.0), _e13);
    o_2.world = p_4;
    o_2.uv = v_1.uv;
    uint _e25 = mx.id.x;
    o_2.id = (v_1.id + _e25);
    o_2.face = v_1.face;
    o_2.col = v_1.col;
    IVO _e31 = o_2;
    const IVO ivo = _e31;
    const VertexOutput_vs_image ivo_1 = { ivo.world, ivo.uv, ivo.id, ivo.face, ivo.col, ivo.pos };
    return ivo_1;
}

float4 fs_image(FragmentInput_fs_image fragmentinput_fs_image) : SV_Target0
{
    IVO i_5 = { fragmentinput_fs_image.pos_8, fragmentinput_fs_image.world_7, fragmentinput_fs_image.uv_1, fragmentinput_fs_image.id_10, fragmentinput_fs_image.face_10, fragmentinput_fs_image.col_7 };
    bool local_12 = (bool)0;
    bool local_13 = (bool)0;
    bool local_14 = (bool)0;
    float a_1 = (float)0;
    bool local_15 = (bool)0;

    float4 t_4 = img.Sample(img_s, i_5.uv);
    const bool _e6 = clipped(i_5.world);
    if (_e6) {
        discard;
    }
    if (!((i_5.uv.x < -(0.0001)))) {
        local_12 = (i_5.uv.x > (1.0 + 0.0001));
    } else {
        local_12 = true;
    }
    bool _e21 = local_12;
    if (!(_e21)) {
        local_13 = (i_5.uv.y < -(0.0001));
    } else {
        local_13 = true;
    }
    bool _e30 = local_13;
    if (!(_e30)) {
        local_14 = (i_5.uv.y > (1.0 + 0.0001));
    } else {
        local_14 = true;
    }
    bool _e40 = local_14;
    if (_e40) {
        discard;
    }
    a_1 = (t_4.w * i_5.col.w);
    uint _e48 = u.mode;
    if ((_e48 == 0u)) {
        const bool _e55 = is_selected(i_5.id, 0u);
        local_15 = _e55;
    } else {
        local_15 = false;
    }
    bool _e57 = local_15;
    if (_e57) {
        float _e58 = a_1;
        a_1 = min(_e58, 0.5);
    }
    float _e61 = a_1;
    if ((_e61 <= 0.0)) {
        discard;
    }
    const float3 _e67 = highlight(t_4.xyz, i_5.id, i_5.face);
    float _e68 = a_1;
    return float4(_e67, _e68);
}

VertexOutput_vs_field vs_field(FVI v_2)
{
    FVO o_3 = (FVO)0;

    float4x4 _e5 = u.vp;
    o_3.pos = mul(float4(v_2.p, 1.0), _e5);
    o_3.world = v_2.p;
    o_3.re = v_2.re;
    o_3.im = v_2.im;
    uint _e20 = mx.id.y;
    o_3.layer = min(_e20, 3u);
    FVO _e23 = o_3;
    const FVO fvo = _e23;
    const VertexOutput_vs_field fvo_1 = { fvo.world, fvo.re, fvo.im, fvo.layer, fvo.pos };
    return fvo_1;
}

float4 fs_field(FragmentInput_fs_field fragmentinput_fs_field) : SV_Target0
{
    FVO i_6 = { fragmentinput_fs_field.pos_10, fragmentinput_fs_field.world_9, fragmentinput_fs_field.re_2, fragmentinput_fs_field.im_2, fragmentinput_fs_field.layer_1 };
    bool local_16 = (bool)0;
    float v_3 = (float)0;

    uint l_4 = i_6.layer;
    float _e7 = u.f[l_4].fmode.w;
    if ((_e7 < 0.5)) {
        const bool _e13 = clipped(i_6.world);
        local_16 = _e13;
    } else {
        local_16 = false;
    }
    bool _e15 = local_16;
    if (_e15) {
        discard;
    }
    const float _e18 = field_value(i_6.re, i_6.im, l_4);
    v_3 = _e18;
    float _e25 = u.f[l_4].fmode.y;
    if ((_e25 > 0.5)) {
        float _e28 = v_3;
        v_3 = (6.0206 * log2(max(abs(_e28), 1e-30)));
    }
    float lo = u.f[l_4].fphase.z;
    float hi = u.f[l_4].fphase.w;
    float _e47 = v_3;
    float t_5 = clamp(((_e47 - lo) / max((hi - lo), 1e-30)), 0.0, 1.0);
    const float3 _e56 = colour_map(t_5, l_4);
    return float4(_e56, 1.0);
}

VertexOutput_vs_grid vs_grid(uint k : SV_VertexID)
{
    GVO o_4 = (GVO)0;

    float cx = ((float(((22u >> k) & 1u)) * 2.0) - 1.0);
    float cy = ((float(((52u >> k) & 1u)) * 2.0) - 1.0);
    o_4.pos = float4(cx, cy, 0.5, 1.0);
    o_4.ndc = float2(cx, cy);
    GVO _e26 = o_4;
    const GVO gvo = _e26;
    const VertexOutput_vs_grid gvo_1 = { gvo.ndc, gvo.pos };
    return gvo_1;
}

GOut fs_grid(FragmentInput_fs_grid fragmentinput_fs_grid)
{
    GVO i_7 = { fragmentinput_fs_grid.pos_12, fragmentinput_fs_grid.ndc_2 };
    bool local_17 = (bool)0;
    bool local_18 = (bool)0;
    float alpha = 0.0;
    int j = int(0);
    float3 rgb_1 = (float3)0;
    GOut o_5 = (GOut)0;

    float4 _e3 = u.gq;
    float4 _e7 = u.gox;
    float4 _e15 = u.goy;
    float3 ro = ((_e3.xyz + (_e7.xyz * i_7.ndc.x)) + (_e15.xyz * i_7.ndc.y));
    float4 _e23 = u.gd;
    float4 _e27 = u.gdx;
    float4 _e35 = u.gdy;
    float3 rd = ((_e23.xyz + (_e27.xyz * i_7.ndc.x)) + (_e35.xyz * i_7.ndc.y));
    float4 _e43 = u.gn;
    float dn = dot(rd, _e43.xyz);
    float _e49 = u.gn.w;
    float4 _e52 = u.gn;
    float t_6 = ((_e49 - dot(ro, _e52.xyz)) / ((dn == 0.0) ? 1e-30 : dn));
    float3 w_5 = (ro + (rd * t_6));
    float4 _e65 = u.gu;
    float pu = dot(w_5, _e65.xyz);
    float4 _e70 = u.gv;
    float pv = dot(w_5, _e70.xyz);
    float2 p_5 = float2(pu, pv);
    float2 _e74 = fwidth(p_5);
    float2 pf_1 = max(_e74, float2(1e-30, 1e-30));
    float cosine = (abs(dn) / max(length(rd), 1e-30));
    if (!((cosine < 0.0001))) {
        float _e92 = u.gq.w;
        if ((_e92 > 0.5)) {
            local_18 = (t_6 <= 0.0);
        } else {
            local_18 = false;
        }
        bool _e100 = local_18;
        local_17 = _e100;
    } else {
        local_17 = true;
    }
    bool _e102 = local_17;
    if (_e102) {
        discard;
    }
    float mpp = max(pf_1.x, pf_1.y);
    float _e109 = u.gs.y;
    float m_2 = max(_e109, 2.0);
    float _e115 = u.gs.x;
    float c0_1 = (_e115 / mpp);
    float k0_ = clamp(ceil((log((6.0 / c0_1)) / log(m_2))), 0.0, 24.0);
    uint2 loop_bound_3 = uint2(4294967295u, 4294967295u);
    bool loop_init_3 = true;
    while(true) {
        if (all(loop_bound_3 == uint2(0u, 0u))) { break; }
        loop_bound_3 -= uint2(loop_bound_3.y == 0u, 1u);
        if (!loop_init_3) {
            int _e164 = j;
            j = asint(asuint(_e164) + asuint(int(1)));
        }
        loop_init_3 = false;
        int _e130 = j;
        if ((_e130 < int(3))) {
        } else {
            break;
        }
        {
            int _e133 = j;
            float k_8 = (k0_ + float(_e133));
            float _e139 = u.gs.x;
            float s_4 = (_e139 * pow(m_2, k_8));
            float4 _e144 = u.gax;
            float _e149 = u.gu.w;
            float _e153 = u.gv.w;
            float2 ph_1 = ((k_8 < 1.5) ? float2(_e149, _e153) : _e144.zw);
            float _e158 = alpha;
            const float _e159 = grid_on(p_5, pf_1, s_4, ph_1);
            const float _e161 = grid_weight((s_4 / mpp), m_2);
            alpha = max(_e158, (_e159 * _e161));
        }
    }
    float _e167 = alpha;
    float _e171 = u.gcol.w;
    alpha = (_e167 * _e171);
    float4 _e175 = u.gcol;
    rgb_1 = _e175.xyz;
    float _e181 = u.gax.x;
    float on_v = (1.0 - min(((abs((pu - _e181)) / pf_1.x) / 1.2), 1.0));
    float _e195 = u.gax.y;
    float on_u = (1.0 - min(((abs((pv - _e195)) / pf_1.y) / 1.2), 1.0));
    float _e209 = u.gcv.w;
    float _e211 = alpha;
    if (((on_v * _e209) > _e211)) {
        float _e216 = u.gcv.w;
        alpha = (on_v * _e216);
        float4 _e220 = u.gcv;
        rgb_1 = _e220.xyz;
    }
    float _e225 = u.gcu.w;
    float _e227 = alpha;
    if (((on_u * _e225) > _e227)) {
        float _e232 = u.gcu.w;
        alpha = (on_u * _e232);
        float4 _e236 = u.gcu;
        rgb_1 = _e236.xyz;
    }
    float _e238 = alpha;
    alpha = (_e238 * smoothstep(0.0, 0.035, cosine));
    float _e243 = alpha;
    if ((_e243 <= 0.002)) {
        discard;
    }
    float3 _e248 = rgb_1;
    float _e249 = alpha;
    o_5.col = float4(_e248, _e249);
    float4x4 _e253 = u.vp;
    float4 c_7 = mul(float4(w_5, 1.0), _e253);
    o_5.depth = clamp((c_7.z / c_7.w), 0.0, 1.0);
    GOut _e264 = o_5;
    const GOut gout = _e264;
    return gout;
}

VertexOutput_vs_pbr vs_pbr(PVI v_4)
{
    PVO o_6 = (PVO)0;

    float4x4 _e4 = mx.m;
    float3 p_6 = mul(float4(v_4.p, 1.0), _e4).xyz;
    float4x4 _e13 = u.vp;
    o_6.pos = mul(float4(p_6, 1.0), _e13);
    o_6.world = p_6;
    uint _e23 = mx.id.x;
    o_6.id = (v_4.id + _e23);
    o_6.col = v_4.col;
    o_6.face = v_4.face;
    float4x4 _e32 = mx.m;
    o_6.n = mul(float4(v_4.n, 0.0), _e32).xyz;
    o_6.slot = v_4.slot;
    PVO _e40 = o_6;
    const PVO pvo = _e40;
    const VertexOutput_vs_pbr pvo_1 = { pvo.world, pvo.id, pvo.col, pvo.face, pvo.n, pvo.slot, pvo.pos };
    return pvo_1;
}

float4 fs_pbr(FragmentInput_fs_pbr fragmentinput_fs_pbr) : SV_Target0
{
    PVO i_8 = { fragmentinput_fs_pbr.pos_14, fragmentinput_fs_pbr.world_11, fragmentinput_fs_pbr.id_12, fragmentinput_fs_pbr.col_9, fragmentinput_fs_pbr.face_12, fragmentinput_fs_pbr.n_6, fragmentinput_fs_pbr.slot_1 };
    bool front_1 = fragmentinput_fs_pbr.front_5;
    const bool _e3 = clipped(i_8.world);
    if (_e3) {
        discard;
    }
    const float _e6 = occlusion_at(i_8.pos.xy);
    const float4 _e7 = pbr(i_8, front_1, _e6);
    return _e7;
}

float4 fs_pbr_glass(FragmentInput_fs_pbr_glass fragmentinput_fs_pbr_glass) : SV_Target0
{
    PVO i_9 = { fragmentinput_fs_pbr_glass.pos_15, fragmentinput_fs_pbr_glass.world_12, fragmentinput_fs_pbr_glass.id_13, fragmentinput_fs_pbr_glass.col_10, fragmentinput_fs_pbr_glass.face_13, fragmentinput_fs_pbr_glass.n_7, fragmentinput_fs_pbr_glass.slot_2 };
    bool front_2 = fragmentinput_fs_pbr_glass.front_6;
    const bool _e3 = clipped(i_9.world);
    if (_e3) {
        discard;
    }
    const float4 _e5 = pbr(i_9, front_2, 1.0);
    return _e5;
}

float4 fs_backdrop(FragmentInput_fs_backdrop fragmentinput_fs_backdrop) : SV_Target0
{
    GVO i_10 = { fragmentinput_fs_backdrop.pos_16, fragmentinput_fs_backdrop.ndc_3 };
    float _e4 = u.lk1_.x;
    if ((_e4 < 1.5)) {
        float t_7 = clamp(((i_10.ndc.y * 0.5) + 0.5), 0.0, 1.0);
        float4 _e18 = u.bg1_;
        float4 _e22 = u.bg0_;
        return float4(lerp(_e18.xyz, _e22.xyz, t_7), 1.0);
    }
    float4 _e29 = u.bd;
    float4 _e33 = u.bdx;
    float4 _e41 = u.bdy;
    float3 d_6 = ((_e29.xyz + (_e33.xyz * i_10.ndc.x)) + (_e41.xyz * i_10.ndc.y));
    const float3 _e49 = env_dir(d_6);
    const float2 _e50 = oct_uv(_e49);
    float4 _e52 = env.SampleLevel(env_s, _e50, 0.0);
    float _e57 = u.lk.y;
    float3 c_8 = (_e52.xyz * _e57);
    const float3 _e59 = display(c_8);
    return float4(_e59, 1.0);
}

VertexOutput_vs_shadow vs_shadow(VI v_5)
{
    DVO o_7 = (DVO)0;

    float4x4 _e4 = mx.m;
    float3 p_7 = mul(float4(v_5.p, 1.0), _e4).xyz;
    float4x4 _e13 = u.lvp;
    o_7.pos = mul(float4(p_7, 1.0), _e13);
    o_7.world = p_7;
    DVO _e18 = o_7;
    const DVO dvo = _e18;
    const VertexOutput_vs_shadow dvo_1 = { dvo.world, dvo.pos };
    return dvo_1;
}

void fs_depth(FragmentInput_fs_depth fragmentinput_fs_depth)
{
    DVO i_11 = { fragmentinput_fs_depth.pos_18, fragmentinput_fs_depth.world_14 };
    const bool _e2 = clipped(i_11.world);
    if (_e2) {
        discard;
    } else {
        return;
    }
}

float4 fs_prepass(FragmentInput_fs_prepass fragmentinput_fs_prepass) : SV_Target0
{
    VO i_12 = { fragmentinput_fs_prepass.pos_19, fragmentinput_fs_prepass.world_15, fragmentinput_fs_prepass.id_14, fragmentinput_fs_prepass.col_11, fragmentinput_fs_prepass.face_14 };
    const bool _e2 = clipped(i_12.world);
    if (_e2) {
        discard;
    }
    float4 _e6 = u.aro;
    float4 _e11 = u.ard;
    return float4(dot((i_12.world - _e6.xyz), _e11.xyz), 0.0, 0.0, 1.0);
}

uint2 NagaDimensions2D(Texture2D<float4> tex)
{
    uint4 ret;
    tex.GetDimensions(0, ret.x, ret.y, ret.z);
    return ret.xy;
}

float4 fs_ao(FragmentInput_fs_ao fragmentinput_fs_ao) : SV_Target0
{
    GVO i_13 = { fragmentinput_fs_ao.pos_20, fragmentinput_fs_ao.ndc_4 };
    float occ = 0.0;
    uint d = 0u;
    float h = (float)0;
    uint k_1 = (uint)0;

    int2 size_3 = int2(NagaDimensions2D(aodepth));
    int2 xy_3 = naga_f2i32(i_13.pos.xy);
    const float4 _e7 = ao_point(xy_3, size_3);
    if ((_e7.w == 0.0)) {
        return float4(1.0, 1.0, 1.0, 1.0);
    }
    float3 p_8 = _e7.xyz;
    const float3 _e17 = ao_normal(xy_3, size_3, p_8);
    float4 _e20 = aodepth.Load(int3(xy_3, int(0)));
    float t_8 = _e20.x;
    float4 _e24 = u.arox;
    float4 _e28 = u.ardx;
    float wpp = ((length((_e24.xyz + (_e28.xyz * t_8))) * 2.0) / float(size_3.x));
    float _e41 = u.ao.y;
    float rpx = clamp((_e41 / max(wpp, 1e-30)), 1.0, AO_MAX_PIXELS);
    uint cell = ((uint((xy_3.x & int(3))) * 4u) + uint((xy_3.y & int(3))));
    float turn = ((float(cell) + 0.5) / 16.0);
    float step0_ = ((float(((cell * 5u) & 15u)) + 0.5) / 16.0);
    float _e76 = u.ao.y;
    float _e80 = u.ao.y;
    float r2_ = (_e76 * _e80);
    uint2 loop_bound_4 = uint2(4294967295u, 4294967295u);
    bool loop_init_4 = true;
    while(true) {
        if (all(loop_bound_4 == uint2(0u, 0u))) { break; }
        loop_bound_4 -= uint2(loop_bound_4.y == 0u, 1u);
        if (!loop_init_4) {
            uint _e148 = d;
            d = (_e148 + 1u);
        }
        loop_init_4 = false;
        uint _e86 = d;
        if ((_e86 < AO_DIRECTIONS)) {
        } else {
            break;
        }
        {
            uint _e89 = d;
            float a_9 = ((((float(_e89) + turn) * 2.0) * PI) / 8.0);
            float2 dir = float2(cos(a_9), sin(a_9));
            h = 0.0;
            k_1 = 0u;
            uint2 loop_bound_5 = uint2(4294967295u, 4294967295u);
            bool loop_init_5 = true;
            while(true) {
                if (all(loop_bound_5 == uint2(0u, 0u))) { break; }
                loop_bound_5 -= uint2(loop_bound_5.y == 0u, 1u);
                if (!loop_init_5) {
                    uint _e142 = k_1;
                    k_1 = (_e142 + 1u);
                }
                loop_init_5 = false;
                uint _e105 = k_1;
                if ((_e105 < AO_STEPS)) {
                } else {
                    break;
                }
                {
                    uint _e109 = k_1;
                    float2 off = ((dir * rpx) * ((float(_e109) + step0_) / 4.0));
                    const int2 _e118 = ao_clamp(asint(asuint(xy_3) + asuint(naga_f2i32(round(off)))), size_3);
                    const float4 _e119 = ao_point(_e118, size_3);
                    if ((_e119.w == 0.0)) {
                        continue;
                    }
                    float3 v_7 = (_e119.xyz - p_8);
                    float len2_ = dot(v_7, v_7);
                    if ((len2_ <= 0.0)) {
                        continue;
                    }
                    float fall = clamp((1.0 - (len2_ / r2_)), 0.0, 1.0);
                    float _e134 = h;
                    h = max(_e134, (((dot(_e17, v_7) * rsqrt(len2_)) - AO_BIAS) * fall));
                }
            }
            float _e145 = occ;
            float _e146 = h;
            occ = (_e145 + _e146);
        }
    }
    float _e151 = occ;
    float open = clamp((1.0 - (_e151 / 7.2)), 0.0, 1.0);
    return float4(open, open, open, 1.0);
}

float4 fs_ao_blur(FragmentInput_fs_ao_blur fragmentinput_fs_ao_blur) : SV_Target0
{
    GVO i_14 = { fragmentinput_fs_ao_blur.pos_21, fragmentinput_fs_ao_blur.ndc_5 };
    float sum = 0.0;
    float n = 0.0;
    int j_1 = int(-2);
    int k_2 = (int)0;
    bool local_19 = (bool)0;

    int2 size_4 = int2(NagaDimensions2D(aodepth));
    int2 xy_4 = naga_f2i32(i_14.pos.xy);
    const float4 _e7 = ao_point(xy_4, size_4);
    if ((_e7.w == 0.0)) {
        return float4(1.0, 1.0, 1.0, 1.0);
    }
    uint2 loop_bound_6 = uint2(4294967295u, 4294967295u);
    bool loop_init_6 = true;
    while(true) {
        if (all(loop_bound_6 == uint2(0u, 0u))) { break; }
        loop_bound_6 -= uint2(loop_bound_6.y == 0u, 1u);
        if (!loop_init_6) {
            int _e65 = j_1;
            j_1 = asint(asuint(_e65) + asuint(int(1)));
        }
        loop_init_6 = false;
        int _e22 = j_1;
        if ((_e22 < int(2))) {
        } else {
            break;
        }
        {
            k_2 = int(-2);
            uint2 loop_bound_7 = uint2(4294967295u, 4294967295u);
            bool loop_init_7 = true;
            while(true) {
                if (all(loop_bound_7 == uint2(0u, 0u))) { break; }
                loop_bound_7 -= uint2(loop_bound_7.y == 0u, 1u);
                if (!loop_init_7) {
                    int _e62 = k_2;
                    k_2 = asint(asuint(_e62) + asuint(int(1)));
                }
                loop_init_7 = false;
                int _e27 = k_2;
                if ((_e27 < int(2))) {
                } else {
                    break;
                }
                {
                    int _e30 = k_2;
                    int _e31 = j_1;
                    const int2 _e34 = ao_clamp(asint(asuint(xy_4) + asuint(int2(_e30, _e31))), size_4);
                    const float4 _e35 = ao_point(_e34, size_4);
                    if (!((_e35.w == 0.0))) {
                        float _e49 = u.ao.z;
                        local_19 = (length((_e35.xyz - _e7.xyz)) > _e49);
                    } else {
                        local_19 = true;
                    }
                    bool _e52 = local_19;
                    if (_e52) {
                        continue;
                    }
                    float _e53 = sum;
                    float4 _e56 = aoraw.Load(int3(_e34, int(0)));
                    sum = (_e53 + _e56.x);
                    float _e59 = n;
                    n = (_e59 + 1.0);
                }
            }
        }
    }
    float _e68 = sum;
    float _e69 = n;
    float _e71 = n;
    float open_1 = ((_e71 > 0.0) ? (_e68 / _e69) : 1.0);
    return float4(open_1, open_1, open_1, 1.0);
}

GrOut fs_ground(FragmentInput_fs_ground fragmentinput_fs_ground)
{
    GVO i_15 = { fragmentinput_fs_ground.pos_22, fragmentinput_fs_ground.ndc_6 };
    GrOut o_8 = (GrOut)0;

    const GroundHit _e2 = ground_hit(i_15.ndc);
    if ((_e2.r >= 1.0)) {
        discard;
    }
    float fade = (1.0 - smoothstep(GROUND_FADE, 1.0, _e2.r));
    float share = u.lu.w;
    const float _e21 = shadow_vis(_e2.w, float3(0.0, 0.0, 1.0));
    const float _e27 = occlusion_at(i_15.pos.xy);
    float lost = (1.0 - ((share * _e21) + ((1.0 - share) * _e27)));
    o_8.col = float4(0.0, 0.0, 0.0, clamp((lost * fade), 0.0, 1.0));
    float4x4 _e44 = u.vp;
    float4 c_9 = mul(float4(_e2.w, 1.0), _e44);
    o_8.depth = clamp((c_9.z / c_9.w), 0.0, 1.0);
    GrOut _e56 = o_8;
    const GrOut grout = _e56;
    return grout;
}

GrOut fs_ground_prepass(FragmentInput_fs_ground_prepass fragmentinput_fs_ground_prepass)
{
    GVO i_16 = { fragmentinput_fs_ground_prepass.pos_23, fragmentinput_fs_ground_prepass.ndc_7 };
    GrOut o_9 = (GrOut)0;

    const GroundHit _e2 = ground_hit(i_16.ndc);
    if ((_e2.r >= 1.0)) {
        discard;
    }
    o_9.col = float4(_e2.t, 0.0, 0.0, 1.0);
    float4x4 _e15 = u.vp;
    float4 c_10 = mul(float4(_e2.w, 1.0), _e15);
    o_9.depth = clamp((c_10.z / c_10.w), 0.0, 1.0);
    GrOut _e27 = o_9;
    const GrOut grout_1 = _e27;
    return grout_1;
}
