// generated by tools/ShaderGen from scene.wgsl — do not edit; wgsl-sha256: 86c815f8b494c1a21e849bf84704f6e9b18c95c4f3c5fab198d90e41255b62d2
struct FB {
    float4 fphase;
    float4 fmode;
    float4 stops[16];
};

struct U {
    row_major float4x4 vp;
    float4 eye;
    float4 clip_;
    uint hover;
    uint hover_face;
    uint flags;
    uint mode;
    uint nsel;
    float ppx;
    float ppy;
    uint pad2_;
    uint4 sel[32];
    FB f[4];
    float4 gu;
    float4 gv;
    float4 gn;
    float4 gq;
    float4 gs;
    float4 gcol;
    float4 gax;
    float4 gcu;
    float4 gcv;
    float4 gox;
    float4 goy;
    float4 gd;
    float4 gdx;
    float4 gdy;
    float4 lk;
    float4 lk1_;
    float4 key;
    float4 keyc;
    float4 bg0_;
    float4 bg1_;
    float4 bd;
    float4 bdx;
    float4 bdy;
    float4 sh[9];
};

struct MX {
    row_major float4x4 m;
    uint4 id;
};

struct VI {
    float3 p : LOC0;
    uint id : LOC1;
    float4 col : LOC2;
    uint face : LOC3;
};

struct VO {
    float4 pos : SV_Position;
    float3 world : LOC0;
    nointerpolation uint id : LOC1;
    float4 col : LOC2;
    nointerpolation uint face : LOC3;
};

struct PickOut {
    uint2 id : SV_Target0;
    float4 world : SV_Target1;
};

struct IVI {
    float3 p : LOC0;
    float2 uv : LOC1;
    uint id : LOC2;
    uint face : LOC3;
    float4 col : LOC4;
};

struct IVO {
    float4 pos : SV_Position;
    float3 world : LOC0;
    float2 uv : LOC1;
    nointerpolation uint id : LOC2;
    nointerpolation uint face : LOC3;
    float4 col : LOC4;
};

struct FVI {
    float3 p : LOC0;
    float3 re : LOC1;
    float3 im : LOC2;
};

struct FVO {
    float4 pos : SV_Position;
    float3 world : LOC0;
    float3 re : LOC1;
    float3 im : LOC2;
    nointerpolation uint layer : LOC3;
};

struct GVO {
    float4 pos : SV_Position;
    float2 ndc : LOC0;
};

struct GOut {
    float4 col : SV_Target0;
    float depth : SV_Depth;
};

struct AP {
    float4 a;
    float4 b;
    float4 c;
};

struct APT {
    AP e[256];
};

struct PVI {
    float3 p : LOC0;
    uint id : LOC1;
    float4 col : LOC2;
    uint face : LOC3;
    float3 n : LOC4;
    uint slot : LOC5;
};

struct PVO {
    float4 pos : SV_Position;
    float3 world : LOC0;
    nointerpolation uint id : LOC1;
    float4 col : LOC2;
    nointerpolation uint face : LOC3;
    float3 n : LOC4;
    nointerpolation uint slot : LOC5;
};

static const float PI = 3.1415927;
static const float DIELECTRIC_F0_ = 0.04;
static const float MIN_ROUGHNESS = 0.045;
static const float MIN_NDOTV = 0.0001;
static const uint SLOT_MASK = 255u;
static const uint STATED_ALPHA = 256u;
static const float TONE_START = 0.76;
static const float TONE_DESAT = 0.15;
static const float TONE_TOE_BREAK = 0.08;
static const float TONE_TOE_SLOPE = 6.25;
static const float TONE_TOE_OFFSET = 0.04;
static const float SRGB_BREAK = 0.0031308;
static const float SRGB_SLOPE = 12.92;
static const float SRGB_SCALE = 1.055;
static const float SRGB_OFFSET = 0.055;
static const float SRGB_GAMMA = 2.4;

cbuffer u : register(b0) { U u; }
cbuffer mx : register(b1) { MX mx; }
Texture2D<float4> img : register(t0);
SamplerState img_s : register(s0);
cbuffer ap : register(b2) { APT ap; }
Texture2D<float4> env : register(t1);
SamplerState env_s : register(s1);
Texture2D<float4> brdf : register(t2);

struct VertexOutput_vs {
    float3 world : LOC0;
    nointerpolation uint id_3 : LOC1;
    float4 col : LOC2;
    nointerpolation uint face_3 : LOC3;
    float4 pos : SV_Position;
};

struct FragmentInput_fs_color {
    float3 world_1 : LOC0;
    nointerpolation uint id_4 : LOC1;
    float4 col_1 : LOC2;
    nointerpolation uint face_4 : LOC3;
    float4 pos_1 : SV_Position;
    bool front_2 : SV_IsFrontFace;
};

struct FragmentInput_fs_line {
    float3 world_2 : LOC0;
    nointerpolation uint id_5 : LOC1;
    float4 col_2 : LOC2;
    nointerpolation uint face_5 : LOC3;
    float4 pos_2 : SV_Position;
};

struct FragmentInput_fs_top {
    float3 world_3 : LOC0;
    nointerpolation uint id_6 : LOC1;
    float4 col_3 : LOC2;
    nointerpolation uint face_6 : LOC3;
    float4 pos_3 : SV_Position;
};

struct FragmentInput_fs_edge {
    float3 world_4 : LOC0;
    nointerpolation uint id_7 : LOC1;
    float4 col_4 : LOC2;
    nointerpolation uint face_7 : LOC3;
    float4 pos_4 : SV_Position;
};

struct FragmentInput_fs_pick {
    float3 world_5 : LOC0;
    nointerpolation uint id_8 : LOC1;
    float4 col_5 : LOC2;
    nointerpolation uint face_8 : LOC3;
    float4 pos_5 : SV_Position;
};

struct VertexOutput_vs_image {
    float3 world_6 : LOC0;
    float2 uv : LOC1;
    nointerpolation uint id_9 : LOC2;
    nointerpolation uint face_9 : LOC3;
    float4 col_6 : LOC4;
    float4 pos_6 : SV_Position;
};

struct FragmentInput_fs_image {
    float3 world_7 : LOC0;
    float2 uv_1 : LOC1;
    nointerpolation uint id_10 : LOC2;
    nointerpolation uint face_10 : LOC3;
    float4 col_7 : LOC4;
    float4 pos_7 : SV_Position;
};

struct VertexOutput_vs_field {
    float3 world_8 : LOC0;
    float3 re_1 : LOC1;
    float3 im_1 : LOC2;
    nointerpolation uint layer : LOC3;
    float4 pos_8 : SV_Position;
};

struct FragmentInput_fs_field {
    float3 world_9 : LOC0;
    float3 re_2 : LOC1;
    float3 im_2 : LOC2;
    nointerpolation uint layer_1 : LOC3;
    float4 pos_9 : SV_Position;
};

struct VertexOutput_vs_grid {
    float2 ndc : LOC0;
    float4 pos_10 : SV_Position;
};

struct FragmentInput_fs_grid {
    float2 ndc_1 : LOC0;
    float4 pos_11 : SV_Position;
};

struct VertexOutput_vs_pbr {
    float3 world_10 : LOC0;
    nointerpolation uint id_11 : LOC1;
    float4 col_8 : LOC2;
    nointerpolation uint face_11 : LOC3;
    float3 n_2 : LOC4;
    nointerpolation uint slot : LOC5;
    float4 pos_12 : SV_Position;
};

struct FragmentInput_fs_pbr {
    float3 world_11 : LOC0;
    nointerpolation uint id_12 : LOC1;
    float4 col_9 : LOC2;
    nointerpolation uint face_12 : LOC3;
    float3 n_3 : LOC4;
    nointerpolation uint slot_1 : LOC5;
    float4 pos_13 : SV_Position;
    bool front_3 : SV_IsFrontFace;
};

struct FragmentInput_fs_backdrop {
    float2 ndc_2 : LOC0;
    float4 pos_14 : SV_Position;
};

bool clipped(float3 w)
{
    bool local_21 = (bool)0;

    uint _e3 = u.flags;
    if (((_e3 & 1u) != 0u)) {
        float4 _e12 = u.clip_;
        float _e18 = u.clip_.w;
        local_21 = ((dot(_e12.xyz, w) + _e18) > 0.0);
    } else {
        local_21 = false;
    }
    bool _e23 = local_21;
    return _e23;
}

uint naga_div(uint lhs, uint rhs) {
    return lhs / (rhs == 0u ? 1u : rhs);
}

uint2 sel_entry(uint k_1)
{
    uint4 q = u.sel[naga_div(k_1, 2u)];
    if (((k_1 & 1u) == 0u)) {
        return q.xy;
    }
    return q.zw;
}

bool is_selected(uint id, uint face)
{
    uint k_2 = 0u;
    bool local_22 = (bool)0;
    bool local_23 = (bool)0;

    uint2 loop_bound = uint2(4294967295u, 4294967295u);
    bool loop_init = true;
    while(true) {
        if (all(loop_bound == uint2(0u, 0u))) { break; }
        loop_bound -= uint2(loop_bound.y == 0u, 1u);
        if (!loop_init) {
            uint _e30 = k_2;
            k_2 = (_e30 + 1u);
        }
        loop_init = false;
        uint _e4 = k_2;
        uint _e7 = u.nsel;
        if ((_e4 < _e7)) {
        } else {
            break;
        }
        {
            uint _e9 = k_2;
            const uint2 _e10 = sel_entry(_e9);
            if ((_e10.x == id)) {
                uint _e17 = u.mode;
                if (!((_e17 != 1u))) {
                    local_23 = (_e10.y == face);
                } else {
                    local_23 = true;
                }
                bool _e26 = local_23;
                local_22 = _e26;
            } else {
                local_22 = false;
            }
            bool _e28 = local_22;
            if (_e28) {
                return true;
            }
        }
    }
    return false;
}

float3 highlight(float3 rgb_2, uint id_1, uint face_1)
{
    float3 c = (float3)0;
    bool local_24 = (bool)0;

    c = rgb_2;
    if ((id_1 == 0u)) {
        float3 _e6 = c;
        return _e6;
    }
    uint _e9 = u.mode;
    if ((_e9 == 0u)) {
        uint _e14 = u.hover;
        if ((id_1 == _e14)) {
            float3 _e16 = c;
            c = lerp(_e16, float3(0.2, 0.9, 1.0), 0.45);
        }
    } else {
        uint _e25 = u.mode;
        if ((_e25 == 1u)) {
            uint _e30 = u.hover;
            if ((id_1 == _e30)) {
                uint _e36 = u.hover_face;
                local_24 = (face_1 == _e36);
            } else {
                local_24 = false;
            }
            bool _e39 = local_24;
            if (_e39) {
                float3 _e40 = c;
                c = lerp(_e40, float3(1.0, 1.0, 1.0), 0.35);
            }
            const bool _e47 = is_selected(id_1, face_1);
            if (_e47) {
                float3 _e48 = c;
                c = lerp(_e48, float3(1.0, 0.35, 1.0), 0.6);
            }
        }
    }
    float3 _e55 = c;
    return _e55;
}

uint naga_f2u32(float value) {
    return uint(clamp(value, 0.0, 4294967000.0));
}

float field_value(float3 re, float3 im, uint l)
{
    float c_4 = u.f[l].fphase.x;
    float s_1 = u.f[l].fphase.y;
    float _e20 = u.f[l].fmode.x;
    uint mode = naga_f2u32((_e20 + 0.5));
    if ((mode == 0u)) {
        return sqrt((dot(re, re) + dot(im, im)));
    }
    if ((mode == 1u)) {
        return length(((re * c_4) - (im * s_1)));
    }
    if ((mode == 2u)) {
        return re.x;
    }
    if ((mode == 3u)) {
        return ((re.x * c_4) - (im.x * s_1));
    }
    return sqrt(((re.x * re.x) + (im.x * im.x)));
}

float3 colour_map(float t, uint l_1)
{
    float3 rgb_3 = (float3)0;
    uint k_3 = 1u;
    bool local_25 = (bool)0;

    float _e7 = u.f[l_1].fmode.z;
    uint n_4 = naga_f2u32((_e7 + 0.5));
    float4 _e16 = u.f[l_1].stops[0];
    rgb_3 = _e16.yzw;
    uint2 loop_bound_1 = uint2(4294967295u, 4294967295u);
    bool loop_init_1 = true;
    while(true) {
        if (all(loop_bound_1 == uint2(0u, 0u))) { break; }
        loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
        if (!loop_init_1) {
            uint _e64 = k_3;
            k_3 = (_e64 + 1u);
        }
        loop_init_1 = false;
        uint _e21 = k_3;
        if ((_e21 < n_4)) {
        } else {
            break;
        }
        {
            uint _e27 = k_3;
            float4 a_5 = u.f[l_1].stops[(_e27 - 1u)];
            uint _e36 = k_3;
            float4 b = u.f[l_1].stops[_e36];
            if (!((t <= b.x))) {
                uint _e44 = k_3;
                local_25 = (_e44 == (n_4 - 1u));
            } else {
                local_25 = true;
            }
            bool _e49 = local_25;
            if (_e49) {
                float w_3 = clamp(((t - a_5.x) / max((b.x - a_5.x), 1e-6)), 0.0, 1.0);
                rgb_3 = lerp(a_5.yzw, b.yzw, w_3);
                break;
            }
        }
    }
    float3 _e67 = rgb_3;
    return _e67;
}

float grid_weight(float c_1, float m)
{
    return ((0.45 * clamp(((c_1 - 6.0) / 8.0), 0.0, 1.0)) + (0.55 * clamp(((c_1 - (6.0 * m)) / (8.0 * m)), 0.0, 1.0)));
}

float grid_on(float2 p, float2 pf, float s, float2 ph)
{
    float2 a_6 = ((p + ph) / (s).xx);
    float2 d_1 = (abs((frac((a_6 - (0.5).xx)) - (0.5).xx)) / max((pf / (s).xx), float2(1e-12, 1e-12)));
    return (1.0 - min(min(d_1.x, d_1.y), 1.0));
}

float3 env_dir(float3 w_1)
{
    float _e4 = u.lk.z;
    float _e10 = u.lk.w;
    float _e17 = u.lk.w;
    float _e24 = u.lk.z;
    return float3(((_e4 * w_1.x) + (_e10 * w_1.y)), ((-(_e17) * w_1.x) + (_e24 * w_1.y)), w_1.z);
}

float2 oct_uv(float3 d)
{
    float2 p_1 = (float2)0;

    float s_2 = ((abs(d.x) + abs(d.y)) + abs(d.z));
    p_1 = (d.xy / (s_2).xx);
    if ((d.z < 0.0)) {
        float2 _e19 = p_1;
        float2 _e29 = p_1;
        p_1 = ((float2(1.0, 1.0) - abs(_e19.yx)) * ((_e29 >= float2(0.0, 0.0)) ? float2(1.0, 1.0) : float2(-1.0, -1.0)));
    }
    float2 _e36 = p_1;
    return ((_e36 * 0.5) + float2(0.5, 0.5));
}

float3 env_radiance(float3 w_2, float rough)
{
    const float3 _e4 = env_dir(w_2);
    const float2 _e5 = oct_uv(_e4);
    float _e9 = u.lk1_.y;
    float4 _e11 = env.SampleLevel(env_s, _e5, (rough * _e9));
    return _e11.xyz;
}

float3 irradiance(float3 n_1)
{
    const float3 _e1 = env_dir(n_1);
    float4 _e5 = u.sh[0];
    float4 _e10 = u.sh[1];
    float4 _e18 = u.sh[2];
    float4 _e26 = u.sh[3];
    float4 _e34 = u.sh[4];
    float4 _e44 = u.sh[5];
    float4 _e54 = u.sh[6];
    float4 _e68 = u.sh[7];
    float4 _e78 = u.sh[8];
    return ((((((((_e5.xyz + (_e10.xyz * _e1.y)) + (_e18.xyz * _e1.z)) + (_e26.xyz * _e1.x)) + (_e34.xyz * (_e1.x * _e1.y))) + (_e44.xyz * (_e1.y * _e1.z))) + (_e54.xyz * (((3.0 * _e1.z) * _e1.z) - 1.0))) + (_e68.xyz * (_e1.x * _e1.z))) + (_e78.xyz * ((_e1.x * _e1.x) - (_e1.y * _e1.y))));
}

float2 brdf_lut(float nv, float rough_1)
{
    float4 _e12 = brdf.SampleLevel(env_s, float2(clamp(nv, 0.0, 1.0), clamp(rough_1, 0.0, 1.0)), 0.0);
    return _e12.xy;
}

float ggx_d(float nh_1, float a_2)
{
    float a2_ = (a_2 * a_2);
    float f = (((nh_1 * nh_1) * (a2_ - 1.0)) + 1.0);
    return (a2_ / ((PI * f) * f));
}

float smith_v(float nv_1, float nl, float a_3)
{
    float a2_1 = (a_3 * a_3);
    float gv = (nl * sqrt((((nv_1 * nv_1) * (1.0 - a2_1)) + a2_1)));
    float gl = (nv_1 * sqrt((((nl * nl) * (1.0 - a2_1)) + a2_1)));
    return (0.5 / max((gv + gl), 1e-7));
}

float3 schlick3_(float3 f0_, float vh_1)
{
    float k_4 = pow((1.0 - clamp(vh_1, 0.0, 1.0)), 5.0);
    return (f0_ + ((float3(1.0, 1.0, 1.0) - f0_) * k_4));
}

float schlick1_(float f0_1, float vh_2)
{
    return (f0_1 + ((1.0 - f0_1) * pow((1.0 - clamp(vh_2, 0.0, 1.0)), 5.0)));
}

float3 pbr_neutral(float3 c0_)
{
    float3 c_2 = (float3)0;

    c_2 = c0_;
    float _e3 = c_2.x;
    float _e5 = c_2.y;
    float _e7 = c_2.z;
    float x_1 = min(_e3, min(_e5, _e7));
    float offset = ((x_1 < TONE_TOE_BREAK) ? (x_1 - ((TONE_TOE_SLOPE * x_1) * x_1)) : TONE_TOE_OFFSET);
    float3 _e18 = c_2;
    c_2 = (_e18 - float3(offset, offset, offset));
    float _e22 = c_2.x;
    float _e24 = c_2.y;
    float _e26 = c_2.z;
    float peak = max(_e22, max(_e24, _e26));
    if ((peak < TONE_START)) {
        float3 _e31 = c_2;
        return _e31;
    }
    float np = (1.0 - ((0.24000001 * 0.24000001) / ((peak + 0.24000001) - TONE_START)));
    float3 _e40 = c_2;
    c_2 = (_e40 * (np / peak));
    float g = (1.0 - (1.0 / ((TONE_DESAT * (peak - np)) + 1.0)));
    float3 _e52 = c_2;
    return lerp(_e52, float3(np, np, np), g);
}

float srgb1_(float x)
{
    float c_5 = clamp(x, 0.0, 1.0);
    return ((c_5 <= SRGB_BREAK) ? (c_5 * SRGB_SLOPE) : ((SRGB_SCALE * pow(c_5, 0.41666666)) - SRGB_OFFSET));
}

float3 display(float3 lin)
{
    float _e4 = u.lk.x;
    const float3 _e11 = pbr_neutral(max((lin * _e4), float3(0.0, 0.0, 0.0)));
    const float _e13 = srgb1_(_e11.x);
    const float _e15 = srgb1_(_e11.y);
    const float _e17 = srgb1_(_e11.z);
    return float3(_e13, _e15, _e17);
}

float3 highlight_pm(float3 rgb_4, float a_4, uint id_2, uint face_2)
{
    float3 c_3 = (float3)0;
    bool local_26 = (bool)0;

    c_3 = rgb_4;
    if ((id_2 == 0u)) {
        float3 _e7 = c_3;
        return _e7;
    }
    uint _e10 = u.mode;
    if ((_e10 == 0u)) {
        uint _e15 = u.hover;
        if ((id_2 == _e15)) {
            float3 _e17 = c_3;
            c_3 = lerp(_e17, (float3(0.2, 0.9, 1.0) * a_4), 0.45);
        }
    } else {
        uint _e27 = u.mode;
        if ((_e27 == 1u)) {
            uint _e32 = u.hover;
            if ((id_2 == _e32)) {
                uint _e38 = u.hover_face;
                local_26 = (face_2 == _e38);
            } else {
                local_26 = false;
            }
            bool _e41 = local_26;
            if (_e41) {
                float3 _e42 = c_3;
                c_3 = lerp(_e42, (float3(1.0, 1.0, 1.0) * a_4), 0.35);
            }
            const bool _e50 = is_selected(id_2, face_2);
            if (_e50) {
                float3 _e51 = c_3;
                c_3 = lerp(_e51, (float3(1.0, 0.35, 1.0) * a_4), 0.6);
            }
        }
    }
    float3 _e59 = c_3;
    return _e59;
}

VertexOutput_vs vs(VI v)
{
    VO o = (VO)0;

    float4x4 _e4 = mx.m;
    float3 p_2 = mul(float4(v.p, 1.0), _e4).xyz;
    float4x4 _e13 = u.vp;
    o.pos = mul(float4(p_2, 1.0), _e13);
    uint _e20 = mx.id.y;
    if ((_e20 != 0u)) {
        uint _e26 = mx.id.y;
        float _e32 = u.ppx;
        uint _e37 = mx.id.y;
        float _e45 = u.ppy;
        float2 px = float2((float((_e26 & 1u)) * _e32), (float(((_e37 >> 1u) & 1u)) * _e45));
        float4 _e50 = o.pos;
        float _e54 = o.pos.w;
        float4 _e58 = o.pos;
        o.pos = float4((_e50.xy + (px * _e54)), _e58.zw);
    }
    o.world = p_2;
    uint _e67 = mx.id.x;
    o.id = (v.id + _e67);
    o.col = v.col;
    o.face = v.face;
    VO _e73 = o;
    const VO vo = _e73;
    const VertexOutput_vs vo_1 = { vo.world, vo.id, vo.col, vo.face, vo.pos };
    return vo_1;
}

float4 fs_color(FragmentInput_fs_color fragmentinput_fs_color) : SV_Target0
{
    VO i = { fragmentinput_fs_color.pos_1, fragmentinput_fs_color.world_1, fragmentinput_fs_color.id_4, fragmentinput_fs_color.col_1, fragmentinput_fs_color.face_4 };
    bool front = fragmentinput_fs_color.front_2;
    bool local = (bool)0;
    bool local_1 = (bool)0;
    bool local_2 = (bool)0;
    bool local_3 = (bool)0;
    bool local_4 = (bool)0;
    bool local_5 = (bool)0;
    bool local_6 = (bool)0;
    float3 rgb = (float3)0;
    bool local_7 = (bool)0;
    float a = (float)0;
    bool local_8 = (bool)0;

    float3 _e3 = ddx(i.world);
    float3 _e5 = ddy(i.world);
    float3 n_5 = normalize(cross(_e3, _e5));
    const bool _e9 = clipped(i.world);
    if (_e9) {
        discard;
    }
    if ((i.col.w == 0.0)) {
        if ((i.id != 0u)) {
            uint _e21 = u.mode;
            local = (_e21 == 0u);
        } else {
            local = false;
        }
        bool _e25 = local;
        if (_e25) {
            uint _e31 = u.hover;
            local_1 = (i.id == _e31);
        } else {
            local_1 = false;
        }
        bool _e34 = local_1;
        if (_e34) {
            return float4(0.2, 0.9, 1.0, 0.18);
        }
        if ((i.id != 0u)) {
            uint _e47 = u.mode;
            local_2 = (_e47 == 1u);
        } else {
            local_2 = false;
        }
        bool _e51 = local_2;
        if (_e51) {
            const bool _e56 = is_selected(i.id, i.face);
            local_3 = _e56;
        } else {
            local_3 = false;
        }
        bool _e58 = local_3;
        if (_e58) {
            return float4(1.0, 0.35, 1.0, 0.4);
        }
        if ((i.id != 0u)) {
            uint _e71 = u.mode;
            local_4 = (_e71 == 1u);
        } else {
            local_4 = false;
        }
        bool _e75 = local_4;
        if (_e75) {
            uint _e81 = u.hover;
            local_5 = (i.id == _e81);
        } else {
            local_5 = false;
        }
        bool _e84 = local_5;
        if (_e84) {
            uint _e90 = u.hover_face;
            local_6 = (i.face == _e90);
        } else {
            local_6 = false;
        }
        bool _e93 = local_6;
        if (_e93) {
            return float4(1.0, 1.0, 1.0, 0.25);
        }
        discard;
    }
    float4 _e101 = u.eye;
    float d_2 = abs(dot(n_5, normalize((_e101.xyz - i.world))));
    rgb = (i.col.xyz * (0.3 + (0.7 * d_2)));
    if (!(front)) {
        uint _e121 = u.flags;
        local_7 = ((_e121 & 2u) != 0u);
    } else {
        local_7 = false;
    }
    bool _e127 = local_7;
    if (_e127) {
        rgb = (i.col.xyz * 0.8);
    }
    a = i.col.w;
    uint _e137 = u.mode;
    if ((_e137 == 0u)) {
        const bool _e144 = is_selected(i.id, 0u);
        local_8 = _e144;
    } else {
        local_8 = false;
    }
    bool _e146 = local_8;
    if (_e146) {
        float _e147 = a;
        a = min(_e147, 0.5);
    }
    float3 _e150 = rgb;
    const float3 _e153 = highlight(_e150, i.id, i.face);
    float _e154 = a;
    return float4(_e153, _e154);
}

float4 fs_line(FragmentInput_fs_line fragmentinput_fs_line) : SV_Target0
{
    VO i_1 = { fragmentinput_fs_line.pos_2, fragmentinput_fs_line.world_2, fragmentinput_fs_line.id_5, fragmentinput_fs_line.col_2, fragmentinput_fs_line.face_5 };
    return float4(i_1.col.xyz, 1.0);
}

float4 fs_top(FragmentInput_fs_top fragmentinput_fs_top) : SV_Target0
{
    VO i_2 = { fragmentinput_fs_top.pos_3, fragmentinput_fs_top.world_3, fragmentinput_fs_top.id_6, fragmentinput_fs_top.col_3, fragmentinput_fs_top.face_6 };
    bool local_9 = (bool)0;
    bool local_10 = (bool)0;

    const bool _e2 = clipped(i_2.world);
    if (!(_e2)) {
        uint _e8 = u.mode;
        local_9 = (_e8 != 1u);
    } else {
        local_9 = true;
    }
    bool _e12 = local_9;
    if (!(_e12)) {
        const bool _e18 = is_selected(i_2.id, i_2.face);
        local_10 = !(_e18);
    } else {
        local_10 = true;
    }
    bool _e21 = local_10;
    if (_e21) {
        discard;
    }
    return float4(1.0, 0.35, 1.0, 0.45);
}

float4 fs_edge(FragmentInput_fs_edge fragmentinput_fs_edge) : SV_Target0
{
    VO i_3 = { fragmentinput_fs_edge.pos_4, fragmentinput_fs_edge.world_4, fragmentinput_fs_edge.id_7, fragmentinput_fs_edge.col_4, fragmentinput_fs_edge.face_7 };
    bool show = false;
    bool local_11 = (bool)0;

    const bool _e2 = clipped(i_3.world);
    if (_e2) {
        discard;
    }
    uint _e7 = u.mode;
    if ((_e7 == 0u)) {
        const bool _e12 = is_selected(i_3.id, 0u);
        show = _e12;
    }
    uint _e15 = u.mode;
    if ((_e15 == 1u)) {
        const bool _e22 = is_selected(i_3.id, (i_3.face & 65535u));
        if (!(_e22)) {
            const bool _e30 = is_selected(i_3.id, (i_3.face >> 16u));
            local_11 = _e30;
        } else {
            local_11 = true;
        }
        bool _e32 = local_11;
        show = _e32;
    }
    bool _e33 = show;
    if (!(_e33)) {
        discard;
    }
    return float4(1.0, 0.35, 1.0, 1.0);
}

PickOut fs_pick(FragmentInput_fs_pick fragmentinput_fs_pick)
{
    VO i_4 = { fragmentinput_fs_pick.pos_5, fragmentinput_fs_pick.world_5, fragmentinput_fs_pick.id_8, fragmentinput_fs_pick.col_5, fragmentinput_fs_pick.face_8 };
    PickOut o_1 = (PickOut)0;

    const bool _e2 = clipped(i_4.world);
    if (_e2) {
        discard;
    }
    o_1.id = uint2(i_4.id, i_4.face);
    o_1.world = float4(i_4.world, 1.0);
    PickOut _e12 = o_1;
    const PickOut pickout = _e12;
    return pickout;
}

VertexOutput_vs_image vs_image(IVI v_1)
{
    IVO o_2 = (IVO)0;

    float4x4 _e4 = mx.m;
    float3 p_3 = mul(float4(v_1.p, 1.0), _e4).xyz;
    float4x4 _e13 = u.vp;
    o_2.pos = mul(float4(p_3, 1.0), _e13);
    o_2.world = p_3;
    o_2.uv = v_1.uv;
    uint _e25 = mx.id.x;
    o_2.id = (v_1.id + _e25);
    o_2.face = v_1.face;
    o_2.col = v_1.col;
    IVO _e31 = o_2;
    const IVO ivo = _e31;
    const VertexOutput_vs_image ivo_1 = { ivo.world, ivo.uv, ivo.id, ivo.face, ivo.col, ivo.pos };
    return ivo_1;
}

float4 fs_image(FragmentInput_fs_image fragmentinput_fs_image) : SV_Target0
{
    IVO i_5 = { fragmentinput_fs_image.pos_7, fragmentinput_fs_image.world_7, fragmentinput_fs_image.uv_1, fragmentinput_fs_image.id_10, fragmentinput_fs_image.face_10, fragmentinput_fs_image.col_7 };
    bool local_12 = (bool)0;
    bool local_13 = (bool)0;
    bool local_14 = (bool)0;
    float a_1 = (float)0;
    bool local_15 = (bool)0;

    float4 t_1 = img.Sample(img_s, i_5.uv);
    const bool _e6 = clipped(i_5.world);
    if (_e6) {
        discard;
    }
    if (!((i_5.uv.x < -(0.0001)))) {
        local_12 = (i_5.uv.x > (1.0 + 0.0001));
    } else {
        local_12 = true;
    }
    bool _e21 = local_12;
    if (!(_e21)) {
        local_13 = (i_5.uv.y < -(0.0001));
    } else {
        local_13 = true;
    }
    bool _e30 = local_13;
    if (!(_e30)) {
        local_14 = (i_5.uv.y > (1.0 + 0.0001));
    } else {
        local_14 = true;
    }
    bool _e40 = local_14;
    if (_e40) {
        discard;
    }
    a_1 = (t_1.w * i_5.col.w);
    uint _e48 = u.mode;
    if ((_e48 == 0u)) {
        const bool _e55 = is_selected(i_5.id, 0u);
        local_15 = _e55;
    } else {
        local_15 = false;
    }
    bool _e57 = local_15;
    if (_e57) {
        float _e58 = a_1;
        a_1 = min(_e58, 0.5);
    }
    float _e61 = a_1;
    if ((_e61 <= 0.0)) {
        discard;
    }
    const float3 _e67 = highlight(t_1.xyz, i_5.id, i_5.face);
    float _e68 = a_1;
    return float4(_e67, _e68);
}

VertexOutput_vs_field vs_field(FVI v_2)
{
    FVO o_3 = (FVO)0;

    float4x4 _e5 = u.vp;
    o_3.pos = mul(float4(v_2.p, 1.0), _e5);
    o_3.world = v_2.p;
    o_3.re = v_2.re;
    o_3.im = v_2.im;
    uint _e20 = mx.id.y;
    o_3.layer = min(_e20, 3u);
    FVO _e23 = o_3;
    const FVO fvo = _e23;
    const VertexOutput_vs_field fvo_1 = { fvo.world, fvo.re, fvo.im, fvo.layer, fvo.pos };
    return fvo_1;
}

float4 fs_field(FragmentInput_fs_field fragmentinput_fs_field) : SV_Target0
{
    FVO i_6 = { fragmentinput_fs_field.pos_9, fragmentinput_fs_field.world_9, fragmentinput_fs_field.re_2, fragmentinput_fs_field.im_2, fragmentinput_fs_field.layer_1 };
    bool local_16 = (bool)0;
    float v_3 = (float)0;

    uint l_2 = i_6.layer;
    float _e7 = u.f[l_2].fmode.w;
    if ((_e7 < 0.5)) {
        const bool _e13 = clipped(i_6.world);
        local_16 = _e13;
    } else {
        local_16 = false;
    }
    bool _e15 = local_16;
    if (_e15) {
        discard;
    }
    const float _e18 = field_value(i_6.re, i_6.im, l_2);
    v_3 = _e18;
    float _e25 = u.f[l_2].fmode.y;
    if ((_e25 > 0.5)) {
        float _e28 = v_3;
        v_3 = (6.0206 * log2(max(abs(_e28), 1e-30)));
    }
    float lo = u.f[l_2].fphase.z;
    float hi = u.f[l_2].fphase.w;
    float _e47 = v_3;
    float t_2 = clamp(((_e47 - lo) / max((hi - lo), 1e-30)), 0.0, 1.0);
    const float3 _e56 = colour_map(t_2, l_2);
    return float4(_e56, 1.0);
}

VertexOutput_vs_grid vs_grid(uint k : SV_VertexID)
{
    GVO o_4 = (GVO)0;

    float cx = ((float(((22u >> k) & 1u)) * 2.0) - 1.0);
    float cy = ((float(((52u >> k) & 1u)) * 2.0) - 1.0);
    o_4.pos = float4(cx, cy, 0.5, 1.0);
    o_4.ndc = float2(cx, cy);
    GVO _e26 = o_4;
    const GVO gvo = _e26;
    const VertexOutput_vs_grid gvo_1 = { gvo.ndc, gvo.pos };
    return gvo_1;
}

GOut fs_grid(FragmentInput_fs_grid fragmentinput_fs_grid)
{
    GVO i_7 = { fragmentinput_fs_grid.pos_11, fragmentinput_fs_grid.ndc_1 };
    bool local_17 = (bool)0;
    bool local_18 = (bool)0;
    float alpha = 0.0;
    int j = int(0);
    float3 rgb_1 = (float3)0;
    GOut o_5 = (GOut)0;

    float4 _e3 = u.gq;
    float4 _e7 = u.gox;
    float4 _e15 = u.goy;
    float3 ro = ((_e3.xyz + (_e7.xyz * i_7.ndc.x)) + (_e15.xyz * i_7.ndc.y));
    float4 _e23 = u.gd;
    float4 _e27 = u.gdx;
    float4 _e35 = u.gdy;
    float3 rd = ((_e23.xyz + (_e27.xyz * i_7.ndc.x)) + (_e35.xyz * i_7.ndc.y));
    float4 _e43 = u.gn;
    float dn = dot(rd, _e43.xyz);
    float _e49 = u.gn.w;
    float4 _e52 = u.gn;
    float t_3 = ((_e49 - dot(ro, _e52.xyz)) / ((dn == 0.0) ? 1e-30 : dn));
    float3 w_4 = (ro + (rd * t_3));
    float4 _e65 = u.gu;
    float pu = dot(w_4, _e65.xyz);
    float4 _e70 = u.gv;
    float pv = dot(w_4, _e70.xyz);
    float2 p_4 = float2(pu, pv);
    float2 _e74 = fwidth(p_4);
    float2 pf_1 = max(_e74, float2(1e-30, 1e-30));
    float cosine = (abs(dn) / max(length(rd), 1e-30));
    if (!((cosine < 0.0001))) {
        float _e92 = u.gq.w;
        if ((_e92 > 0.5)) {
            local_18 = (t_3 <= 0.0);
        } else {
            local_18 = false;
        }
        bool _e100 = local_18;
        local_17 = _e100;
    } else {
        local_17 = true;
    }
    bool _e102 = local_17;
    if (_e102) {
        discard;
    }
    float mpp = max(pf_1.x, pf_1.y);
    float _e109 = u.gs.y;
    float m_1 = max(_e109, 2.0);
    float _e115 = u.gs.x;
    float c0_1 = (_e115 / mpp);
    float k0_ = clamp(ceil((log((6.0 / c0_1)) / log(m_1))), 0.0, 24.0);
    uint2 loop_bound_2 = uint2(4294967295u, 4294967295u);
    bool loop_init_2 = true;
    while(true) {
        if (all(loop_bound_2 == uint2(0u, 0u))) { break; }
        loop_bound_2 -= uint2(loop_bound_2.y == 0u, 1u);
        if (!loop_init_2) {
            int _e164 = j;
            j = asint(asuint(_e164) + asuint(int(1)));
        }
        loop_init_2 = false;
        int _e130 = j;
        if ((_e130 < int(3))) {
        } else {
            break;
        }
        {
            int _e133 = j;
            float k_5 = (k0_ + float(_e133));
            float _e139 = u.gs.x;
            float s_3 = (_e139 * pow(m_1, k_5));
            float4 _e144 = u.gax;
            float _e149 = u.gu.w;
            float _e153 = u.gv.w;
            float2 ph_1 = ((k_5 < 1.5) ? float2(_e149, _e153) : _e144.zw);
            float _e158 = alpha;
            const float _e159 = grid_on(p_4, pf_1, s_3, ph_1);
            const float _e161 = grid_weight((s_3 / mpp), m_1);
            alpha = max(_e158, (_e159 * _e161));
        }
    }
    float _e167 = alpha;
    float _e171 = u.gcol.w;
    alpha = (_e167 * _e171);
    float4 _e175 = u.gcol;
    rgb_1 = _e175.xyz;
    float _e181 = u.gax.x;
    float on_v = (1.0 - min(((abs((pu - _e181)) / pf_1.x) / 1.2), 1.0));
    float _e195 = u.gax.y;
    float on_u = (1.0 - min(((abs((pv - _e195)) / pf_1.y) / 1.2), 1.0));
    float _e209 = u.gcv.w;
    float _e211 = alpha;
    if (((on_v * _e209) > _e211)) {
        float _e216 = u.gcv.w;
        alpha = (on_v * _e216);
        float4 _e220 = u.gcv;
        rgb_1 = _e220.xyz;
    }
    float _e225 = u.gcu.w;
    float _e227 = alpha;
    if (((on_u * _e225) > _e227)) {
        float _e232 = u.gcu.w;
        alpha = (on_u * _e232);
        float4 _e236 = u.gcu;
        rgb_1 = _e236.xyz;
    }
    float _e238 = alpha;
    alpha = (_e238 * smoothstep(0.0, 0.035, cosine));
    float _e243 = alpha;
    if ((_e243 <= 0.002)) {
        discard;
    }
    float3 _e248 = rgb_1;
    float _e249 = alpha;
    o_5.col = float4(_e248, _e249);
    float4x4 _e253 = u.vp;
    float4 c_6 = mul(float4(w_4, 1.0), _e253);
    o_5.depth = clamp((c_6.z / c_6.w), 0.0, 1.0);
    GOut _e264 = o_5;
    const GOut gout = _e264;
    return gout;
}

VertexOutput_vs_pbr vs_pbr(PVI v_4)
{
    PVO o_6 = (PVO)0;

    float4x4 _e4 = mx.m;
    float3 p_5 = mul(float4(v_4.p, 1.0), _e4).xyz;
    float4x4 _e13 = u.vp;
    o_6.pos = mul(float4(p_5, 1.0), _e13);
    o_6.world = p_5;
    uint _e23 = mx.id.x;
    o_6.id = (v_4.id + _e23);
    o_6.col = v_4.col;
    o_6.face = v_4.face;
    float4x4 _e32 = mx.m;
    o_6.n = mul(float4(v_4.n, 0.0), _e32).xyz;
    o_6.slot = v_4.slot;
    PVO _e40 = o_6;
    const PVO pvo = _e40;
    const VertexOutput_vs_pbr pvo_1 = { pvo.world, pvo.id, pvo.col, pvo.face, pvo.n, pvo.slot, pvo.pos };
    return pvo_1;
}

float4 fs_pbr(FragmentInput_fs_pbr fragmentinput_fs_pbr) : SV_Target0
{
    PVO i_8 = { fragmentinput_fs_pbr.pos_13, fragmentinput_fs_pbr.world_11, fragmentinput_fs_pbr.id_12, fragmentinput_fs_pbr.col_9, fragmentinput_fs_pbr.face_12, fragmentinput_fs_pbr.n_3, fragmentinput_fs_pbr.slot_1 };
    bool front_1 = fragmentinput_fs_pbr.front_3;
    float3 n = (float3)0;
    float3 surface = (float3)0;
    bool local_19 = (bool)0;
    float nh = 0.0;
    float vh = 0.0;
    float ad = (float)0;
    float3 coat = (float3)0;
    float ac = (float)0;
    float alpha_1 = 1.0;
    float cov = (float)0;
    bool local_20 = (bool)0;

    const bool _e3 = clipped(i_8.world);
    if (_e3) {
        discard;
    }
    AP m_2 = ap.e[(i_8.slot & SLOT_MASK)];
    float4 _e13 = u.eye;
    float3 v_5 = normalize((_e13.xyz - i_8.world));
    n = normalize(i_8.n);
    if (!(front_1)) {
        uint _e24 = u.flags;
        if (((_e24 & 2u) != 0u)) {
            n = v_5;
        } else {
            float3 _e29 = n;
            n = -(_e29);
        }
    }
    float3 _e31 = n;
    float nv_2 = max(dot(_e31, v_5), MIN_NDOTV);
    float3 base = m_2.a.xyz;
    float metal = clamp(m_2.a.w, 0.0, 1.0);
    float rough_2 = clamp(m_2.b.x, 0.0, 1.0);
    float t_4 = clamp(m_2.b.y, 0.0, 1.0);
    float fr0_ = ((m_2.b.z - 1.0) / (m_2.b.z + 1.0));
    float3 f0_2 = lerp(float3((fr0_ * fr0_), (fr0_ * fr0_), (fr0_ * fr0_)), base, metal);
    const float2 _e66 = brdf_lut(nv_2, rough_2);
    float3 spec_albedo = ((f0_2 * _e66.x) + float3(_e66.y, _e66.y, _e66.y));
    float3 _e74 = n;
    float3 _e78 = n;
    float3 r = (((2.0 * dot(_e74, v_5)) * _e78) - v_5);
    const float3 _e81 = env_radiance(r, rough_2);
    float _e85 = u.lk.y;
    float3 reflected = (_e81 * _e85);
    float3 _e87 = n;
    const float3 _e88 = irradiance(_e87);
    float _e92 = u.lk.y;
    float3 irr = (_e88 * _e92);
    surface = ((reflected * spec_albedo) + ((((((float3(1.0, 1.0, 1.0) - spec_albedo) * (1.0 - metal)) * (1.0 - t_4)) * base) * irr) / (3.1415927).xxx));
    float4 _e115 = u.key;
    float3 l_3 = _e115.xyz;
    float3 _e117 = n;
    float nl_1 = dot(_e117, l_3);
    if ((nl_1 > 0.0)) {
        float4 _e125 = u.keyc;
        float4 _e129 = u.keyc;
        local_19 = (dot(_e125.xyz, _e129.xyz) > 0.0);
    } else {
        local_19 = false;
    }
    bool keyon = local_19;
    if (keyon) {
        float3 h = normalize((l_3 + v_5));
        float3 _e142 = n;
        nh = max(dot(_e142, h), 0.0);
        vh = max(dot(v_5, h), 0.0);
        ad = max(rough_2, MIN_ROUGHNESS);
        float _e152 = ad;
        float _e153 = ad;
        ad = (_e152 * _e153);
        float _e155 = vh;
        const float3 _e156 = schlick3_(f0_2, _e155);
        float _e157 = nh;
        float _e158 = ad;
        const float _e159 = ggx_d(_e157, _e158);
        float _e160 = ad;
        const float _e161 = smith_v(nv_2, nl_1, _e160);
        float3 lobe = (_e156 * (_e159 * _e161));
        float3 body = (((((float3(1.0, 1.0, 1.0) - _e156) * (1.0 - metal)) * (1.0 - t_4)) * base) / (3.1415927).xxx);
        float3 _e179 = surface;
        float4 _e183 = u.keyc;
        float _e189 = u.lk.y;
        surface = (_e179 + ((((lobe + body) * _e183.xyz) * _e189) * nl_1));
    }
    float cc = clamp(m_2.b.w, 0.0, 1.0);
    if ((cc > 0.0)) {
        float ccr = clamp(m_2.c.x, 0.0, 1.0);
        const float2 _e205 = brdf_lut(nv_2, ccr);
        float coat_albedo = ((DIELECTRIC_F0_ * _e205.x) + _e205.y);
        const float3 _e211 = env_radiance(r, ccr);
        float _e215 = u.lk.y;
        coat = ((_e211 * _e215) * coat_albedo);
        if (keyon) {
            ac = max(ccr, MIN_ROUGHNESS);
            float _e222 = ac;
            float _e223 = ac;
            ac = (_e222 * _e223);
            float3 _e225 = coat;
            float4 _e228 = u.keyc;
            float _e233 = u.lk.y;
            float _e236 = vh;
            const float _e237 = schlick1_(DIELECTRIC_F0_, _e236);
            float _e238 = nh;
            float _e239 = ac;
            const float _e240 = ggx_d(_e238, _e239);
            float _e242 = ac;
            const float _e243 = smith_v(nv_2, nl_1, _e242);
            coat = (_e225 + ((_e228.xyz * _e233) * (((_e237 * _e240) * _e243) * nl_1)));
        }
        float3 _e248 = surface;
        float3 _e253 = coat;
        surface = ((_e248 * (1.0 - (cc * coat_albedo))) + (_e253 * cc));
    }
    if ((t_4 > 0.0)) {
        float3 att = m_2.c.yzw;
        float fs = (((spec_albedo.x + spec_albedo.y) + spec_albedo.z) / 3.0);
        float tau = (((att.x + att.y) + att.z) / 3.0);
        float through = (t_4 * (1.0 - fs));
        alpha_1 = (1.0 - (through * tau));
        float3 _e282 = surface;
        surface = (_e282 + ((((through * (1.0 - tau)) * att) * irr) / (3.1415927).xxx));
    }
    cov = (((i_8.slot & STATED_ALPHA) != 0u) ? i_8.col.w : 1.0);
    uint _e304 = u.mode;
    if ((_e304 == 0u)) {
        const bool _e311 = is_selected(i_8.id, 0u);
        local_20 = _e311;
    } else {
        local_20 = false;
    }
    bool _e313 = local_20;
    if (_e313) {
        float _e314 = cov;
        cov = min(_e314, 0.5);
    }
    float _e317 = alpha_1;
    float _e318 = cov;
    float a_7 = (_e317 * _e318);
    float3 _e320 = surface;
    const float3 _e321 = display(_e320);
    float _e322 = cov;
    const float3 _e326 = highlight_pm((_e321 * _e322), a_7, i_8.id, i_8.face);
    return float4(_e326, a_7);
}

float4 fs_backdrop(FragmentInput_fs_backdrop fragmentinput_fs_backdrop) : SV_Target0
{
    GVO i_9 = { fragmentinput_fs_backdrop.pos_14, fragmentinput_fs_backdrop.ndc_2 };
    float _e4 = u.lk1_.x;
    if ((_e4 < 1.5)) {
        float t_5 = clamp(((i_9.ndc.y * 0.5) + 0.5), 0.0, 1.0);
        float4 _e18 = u.bg1_;
        float4 _e22 = u.bg0_;
        return float4(lerp(_e18.xyz, _e22.xyz, t_5), 1.0);
    }
    float4 _e29 = u.bd;
    float4 _e33 = u.bdx;
    float4 _e41 = u.bdy;
    float3 d_3 = ((_e29.xyz + (_e33.xyz * i_9.ndc.x)) + (_e41.xyz * i_9.ndc.y));
    const float3 _e49 = env_dir(d_3);
    const float2 _e50 = oct_uv(_e49);
    float4 _e52 = env.SampleLevel(env_s, _e50, 0.0);
    float _e57 = u.lk.y;
    float3 c_7 = (_e52.xyz * _e57);
    const float3 _e59 = display(c_7);
    return float4(_e59, 1.0);
}
