// generated by tools/ShaderGen from scene.wgsl — do not edit; wgsl-sha256: 3559e69464557803e1d26983471c32cd225c686840882c1280457942fe0156c6
struct U {
    row_major float4x4 vp;
    float4 eye;
    float4 clip_;
    uint hover;
    uint hover_face;
    uint flags;
    uint mode;
    uint nsel;
    uint pad0_;
    uint pad1_;
    uint pad2_;
    uint4 sel[32];
    float4 fphase;
    float4 fmode;
    float4 stops[16];
};

struct VI {
    float3 p : LOC0;
    uint id : LOC1;
    float4 col : LOC2;
    uint face : LOC3;
};

struct VO {
    float4 pos : SV_Position;
    float3 world : LOC0;
    nointerpolation uint id : LOC1;
    float4 col : LOC2;
    nointerpolation uint face : LOC3;
};

struct PickOut {
    uint2 id : SV_Target0;
    float4 world : SV_Target1;
};

struct FVI {
    float3 p : LOC0;
    float3 re : LOC1;
    float3 im : LOC2;
};

struct FVO {
    float4 pos : SV_Position;
    float3 world : LOC0;
    float3 re : LOC1;
    float3 im : LOC2;
};

cbuffer u : register(b0) { U u; }

struct VertexOutput_vs {
    float3 world : LOC0;
    nointerpolation uint id_2 : LOC1;
    float4 col : LOC2;
    nointerpolation uint face_2 : LOC3;
    float4 pos : SV_Position;
};

struct FragmentInput_fs_color {
    float3 world_1 : LOC0;
    nointerpolation uint id_3 : LOC1;
    float4 col_1 : LOC2;
    nointerpolation uint face_3 : LOC3;
    float4 pos_1 : SV_Position;
    bool front_1 : SV_IsFrontFace;
};

struct FragmentInput_fs_line {
    float3 world_2 : LOC0;
    nointerpolation uint id_4 : LOC1;
    float4 col_2 : LOC2;
    nointerpolation uint face_4 : LOC3;
    float4 pos_2 : SV_Position;
};

struct FragmentInput_fs_top {
    float3 world_3 : LOC0;
    nointerpolation uint id_5 : LOC1;
    float4 col_3 : LOC2;
    nointerpolation uint face_5 : LOC3;
    float4 pos_3 : SV_Position;
};

struct FragmentInput_fs_edge {
    float3 world_4 : LOC0;
    nointerpolation uint id_6 : LOC1;
    float4 col_4 : LOC2;
    nointerpolation uint face_6 : LOC3;
    float4 pos_4 : SV_Position;
};

struct FragmentInput_fs_pick {
    float3 world_5 : LOC0;
    nointerpolation uint id_7 : LOC1;
    float4 col_5 : LOC2;
    nointerpolation uint face_7 : LOC3;
    float4 pos_5 : SV_Position;
};

struct VertexOutput_vs_field {
    float3 world_6 : LOC0;
    float3 re_1 : LOC1;
    float3 im_1 : LOC2;
    float4 pos_6 : SV_Position;
};

struct FragmentInput_fs_field {
    float3 world_7 : LOC0;
    float3 re_2 : LOC1;
    float3 im_2 : LOC2;
    float4 pos_7 : SV_Position;
};

bool clipped(float3 w)
{
    bool local_4 = (bool)0;

    uint _e3 = u.flags;
    if (((_e3 & 1u) != 0u)) {
        float4 _e12 = u.clip_;
        float _e18 = u.clip_.w;
        local_4 = ((dot(_e12.xyz, w) + _e18) > 0.0);
    } else {
        local_4 = false;
    }
    bool _e23 = local_4;
    return _e23;
}

uint naga_div(uint lhs, uint rhs) {
    return lhs / (rhs == 0u ? 1u : rhs);
}

uint2 sel_entry(uint k)
{
    uint4 q = u.sel[naga_div(k, 2u)];
    if (((k & 1u) == 0u)) {
        return q.xy;
    }
    return q.zw;
}

bool is_selected(uint id, uint face)
{
    uint k_1 = 0u;
    bool local_5 = (bool)0;
    bool local_6 = (bool)0;

    uint2 loop_bound = uint2(4294967295u, 4294967295u);
    bool loop_init = true;
    while(true) {
        if (all(loop_bound == uint2(0u, 0u))) { break; }
        loop_bound -= uint2(loop_bound.y == 0u, 1u);
        if (!loop_init) {
            uint _e30 = k_1;
            k_1 = (_e30 + 1u);
        }
        loop_init = false;
        uint _e4 = k_1;
        uint _e7 = u.nsel;
        if ((_e4 < _e7)) {
        } else {
            break;
        }
        {
            uint _e9 = k_1;
            const uint2 _e10 = sel_entry(_e9);
            if ((_e10.x == id)) {
                uint _e17 = u.mode;
                if (!((_e17 != 1u))) {
                    local_6 = (_e10.y == face);
                } else {
                    local_6 = true;
                }
                bool _e26 = local_6;
                local_5 = _e26;
            } else {
                local_5 = false;
            }
            bool _e28 = local_5;
            if (_e28) {
                return true;
            }
        }
    }
    return false;
}

float3 highlight(float3 rgb_1, uint id_1, uint face_1)
{
    float3 c = (float3)0;
    bool local_7 = (bool)0;

    c = rgb_1;
    if ((id_1 == 0u)) {
        float3 _e6 = c;
        return _e6;
    }
    uint _e9 = u.mode;
    if ((_e9 == 0u)) {
        uint _e14 = u.hover;
        if ((id_1 == _e14)) {
            float3 _e16 = c;
            c = lerp(_e16, float3(0.2, 0.9, 1.0), 0.45);
        }
    } else {
        uint _e25 = u.mode;
        if ((_e25 == 1u)) {
            uint _e30 = u.hover;
            if ((id_1 == _e30)) {
                uint _e36 = u.hover_face;
                local_7 = (face_1 == _e36);
            } else {
                local_7 = false;
            }
            bool _e39 = local_7;
            if (_e39) {
                float3 _e40 = c;
                c = lerp(_e40, float3(1.0, 1.0, 1.0), 0.35);
            }
            const bool _e47 = is_selected(id_1, face_1);
            if (_e47) {
                float3 _e48 = c;
                c = lerp(_e48, float3(1.0, 0.35, 1.0), 0.6);
            }
        }
    }
    float3 _e55 = c;
    return _e55;
}

uint naga_f2u32(float value) {
    return uint(clamp(value, 0.0, 4294967000.0));
}

float field_value(float3 re, float3 im)
{
    float c_1 = u.fphase.x;
    float s = u.fphase.y;
    float _e13 = u.fmode.x;
    uint mode = naga_f2u32((_e13 + 0.5));
    if ((mode == 0u)) {
        return sqrt((dot(re, re) + dot(im, im)));
    }
    if ((mode == 1u)) {
        return length(((re * c_1) - (im * s)));
    }
    if ((mode == 2u)) {
        return re.x;
    }
    if ((mode == 3u)) {
        return ((re.x * c_1) - (im.x * s));
    }
    return sqrt(((re.x * re.x) + (im.x * im.x)));
}

float3 colour_map(float t)
{
    float3 rgb_2 = (float3)0;
    uint k_2 = 1u;
    bool local_8 = (bool)0;

    float _e4 = u.fmode.z;
    uint n = naga_f2u32((_e4 + 0.5));
    float4 _e11 = u.stops[0];
    rgb_2 = _e11.yzw;
    uint2 loop_bound_1 = uint2(4294967295u, 4294967295u);
    bool loop_init_1 = true;
    while(true) {
        if (all(loop_bound_1 == uint2(0u, 0u))) { break; }
        loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
        if (!loop_init_1) {
            uint _e55 = k_2;
            k_2 = (_e55 + 1u);
        }
        loop_init_1 = false;
        uint _e16 = k_2;
        if ((_e16 < n)) {
        } else {
            break;
        }
        {
            uint _e20 = k_2;
            float4 a = u.stops[(_e20 - 1u)];
            uint _e27 = k_2;
            float4 b = u.stops[_e27];
            if (!((t <= b.x))) {
                uint _e35 = k_2;
                local_8 = (_e35 == (n - 1u));
            } else {
                local_8 = true;
            }
            bool _e40 = local_8;
            if (_e40) {
                float w_1 = clamp(((t - a.x) / max((b.x - a.x), 1e-6)), 0.0, 1.0);
                rgb_2 = lerp(a.yzw, b.yzw, w_1);
                break;
            }
        }
    }
    float3 _e58 = rgb_2;
    return _e58;
}

VertexOutput_vs vs(VI v)
{
    VO o = (VO)0;

    float4x4 _e5 = u.vp;
    o.pos = mul(float4(v.p, 1.0), _e5);
    o.world = v.p;
    o.id = v.id;
    o.col = v.col;
    o.face = v.face;
    VO _e18 = o;
    const VO vo = _e18;
    const VertexOutput_vs vo_1 = { vo.world, vo.id, vo.col, vo.face, vo.pos };
    return vo_1;
}

float4 fs_color(FragmentInput_fs_color fragmentinput_fs_color) : SV_Target0
{
    VO i = { fragmentinput_fs_color.pos_1, fragmentinput_fs_color.world_1, fragmentinput_fs_color.id_3, fragmentinput_fs_color.col_1, fragmentinput_fs_color.face_3 };
    bool front = fragmentinput_fs_color.front_1;
    float3 rgb = (float3)0;
    bool local = (bool)0;

    const bool _e3 = clipped(i.world);
    if (_e3) {
        discard;
    }
    float3 _e5 = ddx(i.world);
    float3 _e7 = ddy(i.world);
    float3 n_1 = normalize(cross(_e5, _e7));
    float4 _e12 = u.eye;
    float d = abs(dot(n_1, normalize((_e12.xyz - i.world))));
    rgb = (i.col.xyz * (0.3 + (0.7 * d)));
    if (!(front)) {
        uint _e32 = u.flags;
        local = ((_e32 & 2u) != 0u);
    } else {
        local = false;
    }
    bool _e38 = local;
    if (_e38) {
        rgb = (i.col.xyz * 0.8);
    }
    float3 _e43 = rgb;
    const float3 _e46 = highlight(_e43, i.id, i.face);
    return float4(_e46, i.col.w);
}

float4 fs_line(FragmentInput_fs_line fragmentinput_fs_line) : SV_Target0
{
    VO i_1 = { fragmentinput_fs_line.pos_2, fragmentinput_fs_line.world_2, fragmentinput_fs_line.id_4, fragmentinput_fs_line.col_2, fragmentinput_fs_line.face_4 };
    return float4(i_1.col.xyz, 1.0);
}

float4 fs_top(FragmentInput_fs_top fragmentinput_fs_top) : SV_Target0
{
    VO i_2 = { fragmentinput_fs_top.pos_3, fragmentinput_fs_top.world_3, fragmentinput_fs_top.id_5, fragmentinput_fs_top.col_3, fragmentinput_fs_top.face_5 };
    bool local_1 = (bool)0;
    bool local_2 = (bool)0;

    const bool _e2 = clipped(i_2.world);
    if (!(_e2)) {
        uint _e8 = u.mode;
        local_1 = (_e8 != 1u);
    } else {
        local_1 = true;
    }
    bool _e12 = local_1;
    if (!(_e12)) {
        const bool _e18 = is_selected(i_2.id, i_2.face);
        local_2 = !(_e18);
    } else {
        local_2 = true;
    }
    bool _e21 = local_2;
    if (_e21) {
        discard;
    }
    return float4(1.0, 0.35, 1.0, 0.45);
}

float4 fs_edge(FragmentInput_fs_edge fragmentinput_fs_edge) : SV_Target0
{
    VO i_3 = { fragmentinput_fs_edge.pos_4, fragmentinput_fs_edge.world_4, fragmentinput_fs_edge.id_6, fragmentinput_fs_edge.col_4, fragmentinput_fs_edge.face_6 };
    bool show = false;
    bool local_3 = (bool)0;

    const bool _e2 = clipped(i_3.world);
    if (_e2) {
        discard;
    }
    uint _e7 = u.mode;
    if ((_e7 == 0u)) {
        const bool _e12 = is_selected(i_3.id, 0u);
        show = _e12;
    }
    uint _e15 = u.mode;
    if ((_e15 == 1u)) {
        const bool _e22 = is_selected(i_3.id, (i_3.face & 65535u));
        if (!(_e22)) {
            const bool _e30 = is_selected(i_3.id, (i_3.face >> 16u));
            local_3 = _e30;
        } else {
            local_3 = true;
        }
        bool _e32 = local_3;
        show = _e32;
    }
    bool _e33 = show;
    if (!(_e33)) {
        discard;
    }
    return float4(1.0, 0.35, 1.0, 1.0);
}

PickOut fs_pick(FragmentInput_fs_pick fragmentinput_fs_pick)
{
    VO i_4 = { fragmentinput_fs_pick.pos_5, fragmentinput_fs_pick.world_5, fragmentinput_fs_pick.id_7, fragmentinput_fs_pick.col_5, fragmentinput_fs_pick.face_7 };
    PickOut o_1 = (PickOut)0;

    const bool _e2 = clipped(i_4.world);
    if (_e2) {
        discard;
    }
    o_1.id = uint2(i_4.id, i_4.face);
    o_1.world = float4(i_4.world, 1.0);
    PickOut _e12 = o_1;
    const PickOut pickout = _e12;
    return pickout;
}

VertexOutput_vs_field vs_field(FVI v_1)
{
    FVO o_2 = (FVO)0;

    float4x4 _e5 = u.vp;
    o_2.pos = mul(float4(v_1.p, 1.0), _e5);
    o_2.world = v_1.p;
    o_2.re = v_1.re;
    o_2.im = v_1.im;
    FVO _e16 = o_2;
    const FVO fvo = _e16;
    const VertexOutput_vs_field fvo_1 = { fvo.world, fvo.re, fvo.im, fvo.pos };
    return fvo_1;
}

float4 fs_field(FragmentInput_fs_field fragmentinput_fs_field) : SV_Target0
{
    FVO i_5 = { fragmentinput_fs_field.pos_7, fragmentinput_fs_field.world_7, fragmentinput_fs_field.re_2, fragmentinput_fs_field.im_2 };
    float v_2 = (float)0;

    const bool _e2 = clipped(i_5.world);
    if (_e2) {
        discard;
    }
    const float _e5 = field_value(i_5.re, i_5.im);
    v_2 = _e5;
    float _e10 = u.fmode.y;
    if ((_e10 > 0.5)) {
        float _e13 = v_2;
        v_2 = (6.0206 * log2(max(abs(_e13), 1e-30)));
    }
    float _e20 = v_2;
    float _e24 = u.fphase.z;
    float _e29 = u.fphase.w;
    float _e33 = u.fphase.z;
    float t_1 = clamp(((_e20 - _e24) / max((_e29 - _e33), 1e-30)), 0.0, 1.0);
    const float3 _e41 = colour_map(t_1);
    return float4(_e41, 1.0);
}
