// generated by tools/ShaderGen from scene.wgsl — do not edit; wgsl-sha256: fbcb4126c7a5da352f75a7ec9eaac1124b95a2716d107b08b7e303f88ec4858e
// language: metal2.3
#include <metal_stdlib>
#include <simd/simd.h>

using metal::uint;

struct type_5 {
    metal::uint4 inner[32];
};
struct type_6 {
    metal::float4 inner[16];
};
struct U {
    metal::float4x4 vp;
    metal::float4 eye;
    metal::float4 clip;
    uint hover;
    uint hover_face;
    uint flags;
    uint mode;
    uint nsel;
    float ppx;
    float ppy;
    uint pad2_;
    type_5 sel;
    metal::float4 fphase;
    metal::float4 fmode;
    type_6 stops;
    metal::float4 gu;
    metal::float4 gv;
    metal::float4 gn;
    metal::float4 gq;
    metal::float4 gs;
    metal::float4 gcol;
    metal::float4 gax;
    metal::float4 gcu;
    metal::float4 gcv;
    metal::float4 gox;
    metal::float4 goy;
    metal::float4 gd;
    metal::float4 gdx;
    metal::float4 gdy;
};
struct MX {
    metal::float4x4 m;
    metal::uint4 id;
};
struct VI {
    metal::packed_float3 p;
    uint id;
    metal::float4 col;
    uint face;
    char _pad4[12];
};
struct VO {
    metal::float4 pos;
    metal::packed_float3 world;
    uint id;
    metal::float4 col;
    uint face;
    char _pad5[12];
};
struct PickOut {
    metal::uint2 id;
    char _pad1[8];
    metal::float4 world;
};
struct FVI {
    metal::float3 p;
    metal::float3 re;
    metal::float3 im;
};
struct FVO {
    metal::float4 pos;
    metal::float3 world;
    metal::float3 re;
    metal::float3 im;
};
struct GVO {
    metal::float4 pos;
    metal::float2 ndc;
    char _pad2[8];
};
struct GOut {
    metal::float4 col;
    float depth;
    char _pad2[12];
};

bool clipped(
    metal::float3 w,
    constant U& u
) {
    bool local_14 = {};
    uint _e3 = u.flags;
    if ((_e3 & 1u) != 0u) {
        metal::float4 _e12 = u.clip;
        float _e18 = u.clip.w;
        local_14 = (metal::dot(_e12.xyz, w) + _e18) > 0.0;
    } else {
        local_14 = false;
    }
    bool _e23 = local_14;
    return _e23;
}

uint naga_div(uint lhs, uint rhs) {
    return lhs / metal::select(rhs, 1u, rhs == 0u);
}

metal::uint2 sel_entry(
    uint k_1,
    constant U& u
) {
    metal::uint4 q = u.sel.inner[naga_div(k_1, 2u)];
    if ((k_1 & 1u) == 0u) {
        return q.xy;
    }
    return q.zw;
}

bool is_selected(
    uint id,
    uint face,
    constant U& u
) {
    uint k_2 = 0u;
    bool local_15 = {};
    bool local_16 = {};
    uint2 loop_bound = uint2(4294967295u);
    bool loop_init = true;
    while(true) {
        if (metal::all(loop_bound == uint2(0u))) { break; }
        loop_bound -= uint2(loop_bound.y == 0u, 1u);
        if (!loop_init) {
            uint _e30 = k_2;
            k_2 = _e30 + 1u;
        }
        loop_init = false;
        uint _e4 = k_2;
        uint _e7 = u.nsel;
        if (_e4 < _e7) {
        } else {
            break;
        }
        {
            uint _e9 = k_2;
            metal::uint2 _e10 = sel_entry(_e9, u);
            if (_e10.x == id) {
                uint _e17 = u.mode;
                if (!((_e17 != 1u))) {
                    local_16 = _e10.y == face;
                } else {
                    local_16 = true;
                }
                bool _e26 = local_16;
                local_15 = _e26;
            } else {
                local_15 = false;
            }
            bool _e28 = local_15;
            if (_e28) {
                return true;
            }
        }
    }
    return false;
}

metal::float3 highlight(
    metal::float3 rgb_2,
    uint id_1,
    uint face_1,
    constant U& u
) {
    metal::float3 c = {};
    bool local_17 = {};
    c = rgb_2;
    if (id_1 == 0u) {
        metal::float3 _e6 = c;
        return _e6;
    }
    uint _e9 = u.mode;
    if (_e9 == 0u) {
        uint _e14 = u.hover;
        if (id_1 == _e14) {
            metal::float3 _e16 = c;
            c = metal::mix(_e16, metal::float3(0.2, 0.9, 1.0), 0.45);
        }
    } else {
        uint _e25 = u.mode;
        if (_e25 == 1u) {
            uint _e30 = u.hover;
            if (id_1 == _e30) {
                uint _e36 = u.hover_face;
                local_17 = face_1 == _e36;
            } else {
                local_17 = false;
            }
            bool _e39 = local_17;
            if (_e39) {
                metal::float3 _e40 = c;
                c = metal::mix(_e40, metal::float3(1.0, 1.0, 1.0), 0.35);
            }
            bool _e47 = is_selected(id_1, face_1, u);
            if (_e47) {
                metal::float3 _e48 = c;
                c = metal::mix(_e48, metal::float3(1.0, 0.35, 1.0), 0.6);
            }
        }
    }
    metal::float3 _e55 = c;
    return _e55;
}

uint naga_f2u32(float value) {
    return static_cast<uint>(metal::clamp(value, 0.0, 4294967000.0));
}

float field_value(
    metal::float3 re,
    metal::float3 im,
    constant U& u
) {
    float c_2 = u.fphase.x;
    float s_1 = u.fphase.y;
    float _e13 = u.fmode.x;
    uint mode = naga_f2u32(_e13 + 0.5);
    if (mode == 0u) {
        return metal::sqrt(metal::dot(re, re) + metal::dot(im, im));
    }
    if (mode == 1u) {
        return metal::length((re * c_2) - (im * s_1));
    }
    if (mode == 2u) {
        return re.x;
    }
    if (mode == 3u) {
        return (re.x * c_2) - (im.x * s_1);
    }
    return metal::sqrt((re.x * re.x) + (im.x * im.x));
}

metal::float3 colour_map(
    float t,
    constant U& u
) {
    metal::float3 rgb_3 = {};
    uint k_3 = 1u;
    bool local_18 = {};
    float _e4 = u.fmode.z;
    uint n = naga_f2u32(_e4 + 0.5);
    metal::float4 _e11 = u.stops.inner[0];
    rgb_3 = _e11.yzw;
    uint2 loop_bound_1 = uint2(4294967295u);
    bool loop_init_1 = true;
    while(true) {
        if (metal::all(loop_bound_1 == uint2(0u))) { break; }
        loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
        if (!loop_init_1) {
            uint _e55 = k_3;
            k_3 = _e55 + 1u;
        }
        loop_init_1 = false;
        uint _e16 = k_3;
        if (_e16 < n) {
        } else {
            break;
        }
        {
            uint _e20 = k_3;
            metal::float4 a_1 = u.stops.inner[_e20 - 1u];
            uint _e27 = k_3;
            metal::float4 b = u.stops.inner[_e27];
            if (!((t <= b.x))) {
                uint _e35 = k_3;
                local_18 = _e35 == (n - 1u);
            } else {
                local_18 = true;
            }
            bool _e40 = local_18;
            if (_e40) {
                float w_1 = metal::clamp((t - a_1.x) / metal::max(b.x - a_1.x, 0.000001), 0.0, 1.0);
                rgb_3 = metal::mix(a_1.yzw, b.yzw, w_1);
                break;
            }
        }
    }
    metal::float3 _e58 = rgb_3;
    return _e58;
}

float grid_weight(
    float c_1,
    float m
) {
    return (0.45 * metal::clamp((c_1 - 6.0) / 8.0, 0.0, 1.0)) + (0.55 * metal::clamp((c_1 - (6.0 * m)) / (8.0 * m), 0.0, 1.0));
}

float grid_on(
    metal::float2 p,
    metal::float2 pf,
    float s,
    metal::float2 ph
) {
    metal::float2 a_2 = (p + ph) / metal::float2(s);
    metal::float2 d = metal::abs(metal::fract(a_2 - metal::float2(0.5)) - metal::float2(0.5)) / metal::max(pf / metal::float2(s), metal::float2(0.000000000001, 0.000000000001));
    return 1.0 - metal::min(metal::min(d.x, d.y), 1.0);
}

struct vsInput {
    metal::float3 p_1 [[attribute(0)]];
    uint id_2 [[attribute(1)]];
    metal::float4 col [[attribute(2)]];
    uint face_2 [[attribute(3)]];
};
struct vsOutput {
    metal::float4 pos [[position]];
    metal::float3 world [[user(loc0), center_perspective]];
    uint id [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face [[user(loc3), flat]];
};
vertex vsOutput vs(
  vsInput varyings [[stage_in]]
, constant U& u [[buffer(1)]]
, constant MX& mx [[buffer(2)]]
) {
    const VI v = { varyings.p_1, varyings.id_2, varyings.col, varyings.face_2 };
    VO o = {};
    metal::float4x4 _e4 = mx.m;
    metal::float3 p_1 = (_e4 * metal::float4(v.p, 1.0)).xyz;
    metal::float4x4 _e13 = u.vp;
    o.pos = _e13 * metal::float4(p_1, 1.0);
    uint _e20 = mx.id.y;
    if (_e20 != 0u) {
        uint _e26 = mx.id.y;
        float _e32 = u.ppx;
        uint _e37 = mx.id.y;
        float _e45 = u.ppy;
        metal::float2 px = metal::float2(static_cast<float>(_e26 & 1u) * _e32, static_cast<float>((_e37 >> 1u) & 1u) * _e45);
        metal::float4 _e50 = o.pos;
        float _e54 = o.pos.w;
        metal::float4 _e58 = o.pos;
        o.pos = metal::float4(_e50.xy + (px * _e54), _e58.zw);
    }
    o.world = p_1;
    uint _e67 = mx.id.x;
    o.id = v.id + _e67;
    o.col = v.col;
    o.face = v.face;
    VO _e73 = o;
    const auto _tmp = _e73;
    return vsOutput { _tmp.pos, _tmp.world, _tmp.id, _tmp.col, _tmp.face };
}


struct fs_colorInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_2 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_2 [[user(loc3), flat]];
};
struct fs_colorOutput {
    metal::float4 member_1 [[color(0)]];
};
fragment fs_colorOutput fs_color(
  fs_colorInput varyings_1 [[stage_in]]
, metal::float4 pos [[position]]
, bool front [[front_facing]]
, constant U& u [[buffer(1)]]
) {
    const VO i = { pos, varyings_1.world, varyings_1.id_2, varyings_1.col, varyings_1.face_2 };
    bool local = {};
    bool local_1 = {};
    bool local_2 = {};
    bool local_3 = {};
    bool local_4 = {};
    bool local_5 = {};
    bool local_6 = {};
    metal::float3 rgb = {};
    bool local_7 = {};
    float a = {};
    bool local_8 = {};
    metal::float3 _e3 = metal::dfdx(i.world);
    metal::float3 _e5 = metal::dfdy(i.world);
    metal::float3 n_1 = metal::normalize(metal::cross(_e3, _e5));
    bool _e9 = clipped(i.world, u);
    if (_e9) {
        metal::discard_fragment();
    }
    if (i.col.w == 0.0) {
        if (i.id != 0u) {
            uint _e21 = u.mode;
            local = _e21 == 0u;
        } else {
            local = false;
        }
        bool _e25 = local;
        if (_e25) {
            uint _e31 = u.hover;
            local_1 = i.id == _e31;
        } else {
            local_1 = false;
        }
        bool _e34 = local_1;
        if (_e34) {
            return fs_colorOutput { metal::float4(0.2, 0.9, 1.0, 0.18) };
        }
        if (i.id != 0u) {
            uint _e47 = u.mode;
            local_2 = _e47 == 1u;
        } else {
            local_2 = false;
        }
        bool _e51 = local_2;
        if (_e51) {
            bool _e56 = is_selected(i.id, i.face, u);
            local_3 = _e56;
        } else {
            local_3 = false;
        }
        bool _e58 = local_3;
        if (_e58) {
            return fs_colorOutput { metal::float4(1.0, 0.35, 1.0, 0.4) };
        }
        if (i.id != 0u) {
            uint _e71 = u.mode;
            local_4 = _e71 == 1u;
        } else {
            local_4 = false;
        }
        bool _e75 = local_4;
        if (_e75) {
            uint _e81 = u.hover;
            local_5 = i.id == _e81;
        } else {
            local_5 = false;
        }
        bool _e84 = local_5;
        if (_e84) {
            uint _e90 = u.hover_face;
            local_6 = i.face == _e90;
        } else {
            local_6 = false;
        }
        bool _e93 = local_6;
        if (_e93) {
            return fs_colorOutput { metal::float4(1.0, 1.0, 1.0, 0.25) };
        }
        metal::discard_fragment();
    }
    metal::float4 _e101 = u.eye;
    float d_1 = metal::abs(metal::dot(n_1, metal::normalize(_e101.xyz - i.world)));
    rgb = i.col.xyz * (0.3 + (0.7 * d_1));
    if (!(front)) {
        uint _e121 = u.flags;
        local_7 = (_e121 & 2u) != 0u;
    } else {
        local_7 = false;
    }
    bool _e127 = local_7;
    if (_e127) {
        rgb = i.col.xyz * 0.8;
    }
    a = i.col.w;
    uint _e137 = u.mode;
    if (_e137 == 0u) {
        bool _e144 = is_selected(i.id, 0u, u);
        local_8 = _e144;
    } else {
        local_8 = false;
    }
    bool _e146 = local_8;
    if (_e146) {
        float _e147 = a;
        a = metal::min(_e147, 0.5);
    }
    metal::float3 _e150 = rgb;
    metal::float3 _e153 = highlight(_e150, i.id, i.face, u);
    float _e154 = a;
    return fs_colorOutput { metal::float4(_e153, _e154) };
}


struct fs_lineInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_2 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_2 [[user(loc3), flat]];
};
struct fs_lineOutput {
    metal::float4 member_2 [[color(0)]];
};
fragment fs_lineOutput fs_line(
  fs_lineInput varyings_2 [[stage_in]]
, metal::float4 pos_1 [[position]]
) {
    const VO i_1 = { pos_1, varyings_2.world, varyings_2.id_2, varyings_2.col, varyings_2.face_2 };
    return fs_lineOutput { metal::float4(i_1.col.xyz, 1.0) };
}


struct fs_topInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_2 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_2 [[user(loc3), flat]];
};
struct fs_topOutput {
    metal::float4 member_3 [[color(0)]];
};
fragment fs_topOutput fs_top(
  fs_topInput varyings_3 [[stage_in]]
, metal::float4 pos_2 [[position]]
, constant U& u [[buffer(1)]]
) {
    const VO i_2 = { pos_2, varyings_3.world, varyings_3.id_2, varyings_3.col, varyings_3.face_2 };
    bool local_9 = {};
    bool local_10 = {};
    bool _e2 = clipped(i_2.world, u);
    if (!(_e2)) {
        uint _e8 = u.mode;
        local_9 = _e8 != 1u;
    } else {
        local_9 = true;
    }
    bool _e12 = local_9;
    if (!(_e12)) {
        bool _e18 = is_selected(i_2.id, i_2.face, u);
        local_10 = !(_e18);
    } else {
        local_10 = true;
    }
    bool _e21 = local_10;
    if (_e21) {
        metal::discard_fragment();
    }
    return fs_topOutput { metal::float4(1.0, 0.35, 1.0, 0.45) };
}


struct fs_edgeInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_2 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_2 [[user(loc3), flat]];
};
struct fs_edgeOutput {
    metal::float4 member_4 [[color(0)]];
};
fragment fs_edgeOutput fs_edge(
  fs_edgeInput varyings_4 [[stage_in]]
, metal::float4 pos_3 [[position]]
, constant U& u [[buffer(1)]]
) {
    const VO i_3 = { pos_3, varyings_4.world, varyings_4.id_2, varyings_4.col, varyings_4.face_2 };
    bool show = false;
    bool local_11 = {};
    bool _e2 = clipped(i_3.world, u);
    if (_e2) {
        metal::discard_fragment();
    }
    uint _e7 = u.mode;
    if (_e7 == 0u) {
        bool _e12 = is_selected(i_3.id, 0u, u);
        show = _e12;
    }
    uint _e15 = u.mode;
    if (_e15 == 1u) {
        bool _e22 = is_selected(i_3.id, i_3.face & 65535u, u);
        if (!(_e22)) {
            bool _e30 = is_selected(i_3.id, i_3.face >> 16u, u);
            local_11 = _e30;
        } else {
            local_11 = true;
        }
        bool _e32 = local_11;
        show = _e32;
    }
    bool _e33 = show;
    if (!(_e33)) {
        metal::discard_fragment();
    }
    return fs_edgeOutput { metal::float4(1.0, 0.35, 1.0, 1.0) };
}


struct fs_pickInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_2 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_2 [[user(loc3), flat]];
};
struct fs_pickOutput {
    metal::uint2 id [[color(0)]];
    metal::float4 world [[color(1)]];
};
fragment fs_pickOutput fs_pick(
  fs_pickInput varyings_5 [[stage_in]]
, metal::float4 pos_4 [[position]]
, constant U& u [[buffer(1)]]
) {
    const VO i_4 = { pos_4, varyings_5.world, varyings_5.id_2, varyings_5.col, varyings_5.face_2 };
    PickOut o_1 = {};
    bool _e2 = clipped(i_4.world, u);
    if (_e2) {
        metal::discard_fragment();
    }
    o_1.id = metal::uint2(i_4.id, i_4.face);
    o_1.world = metal::float4(i_4.world, 1.0);
    PickOut _e12 = o_1;
    const auto _tmp_1 = _e12;
    return fs_pickOutput { _tmp_1.id, _tmp_1.world };
}


struct vs_fieldInput {
    metal::float3 p_1 [[attribute(0)]];
    metal::float3 re_1 [[attribute(1)]];
    metal::float3 im_1 [[attribute(2)]];
};
struct vs_fieldOutput {
    metal::float4 pos [[position]];
    metal::float3 world [[user(loc0), center_perspective]];
    metal::float3 re [[user(loc1), center_perspective]];
    metal::float3 im [[user(loc2), center_perspective]];
};
vertex vs_fieldOutput vs_field(
  vs_fieldInput varyings_6 [[stage_in]]
, constant U& u [[buffer(1)]]
) {
    const FVI v_1 = { varyings_6.p_1, varyings_6.re_1, varyings_6.im_1 };
    FVO o_2 = {};
    metal::float4x4 _e5 = u.vp;
    o_2.pos = _e5 * metal::float4(v_1.p, 1.0);
    o_2.world = v_1.p;
    o_2.re = v_1.re;
    o_2.im = v_1.im;
    FVO _e16 = o_2;
    const auto _tmp_2 = _e16;
    return vs_fieldOutput { _tmp_2.pos, _tmp_2.world, _tmp_2.re, _tmp_2.im };
}


struct fs_fieldInput {
    metal::float3 world [[user(loc0), center_perspective]];
    metal::float3 re_1 [[user(loc1), center_perspective]];
    metal::float3 im_1 [[user(loc2), center_perspective]];
};
struct fs_fieldOutput {
    metal::float4 member_7 [[color(0)]];
};
fragment fs_fieldOutput fs_field(
  fs_fieldInput varyings_7 [[stage_in]]
, metal::float4 pos_5 [[position]]
, constant U& u [[buffer(1)]]
) {
    const FVO i_5 = { pos_5, varyings_7.world, varyings_7.re_1, varyings_7.im_1 };
    float v_2 = {};
    bool _e2 = clipped(i_5.world, u);
    if (_e2) {
        metal::discard_fragment();
    }
    float _e5 = field_value(i_5.re, i_5.im, u);
    v_2 = _e5;
    float _e10 = u.fmode.y;
    if (_e10 > 0.5) {
        float _e13 = v_2;
        v_2 = 6.0206 * metal::log2(metal::max(metal::abs(_e13), 0.000000000000000000000000000001));
    }
    float _e20 = v_2;
    float _e24 = u.fphase.z;
    float _e29 = u.fphase.w;
    float _e33 = u.fphase.z;
    float t_1 = metal::clamp((_e20 - _e24) / metal::max(_e29 - _e33, 0.000000000000000000000000000001), 0.0, 1.0);
    metal::float3 _e41 = colour_map(t_1, u);
    return fs_fieldOutput { metal::float4(_e41, 1.0) };
}


struct vs_gridInput {
};
struct vs_gridOutput {
    metal::float4 pos [[position]];
    metal::float2 ndc [[user(loc0), center_perspective]];
};
vertex vs_gridOutput vs_grid(
  uint k [[vertex_id]]
) {
    GVO o_3 = {};
    float cx = (static_cast<float>((22u >> k) & 1u) * 2.0) - 1.0;
    float cy = (static_cast<float>((52u >> k) & 1u) * 2.0) - 1.0;
    o_3.pos = metal::float4(cx, cy, 0.5, 1.0);
    o_3.ndc = metal::float2(cx, cy);
    GVO _e26 = o_3;
    const auto _tmp_3 = _e26;
    return vs_gridOutput { _tmp_3.pos, _tmp_3.ndc };
}


struct fs_gridInput {
    metal::float2 ndc [[user(loc0), center_perspective]];
};
struct fs_gridOutput {
    metal::float4 col [[color(0)]];
    float depth [[depth(any)]];
};
fragment fs_gridOutput fs_grid(
  fs_gridInput varyings_9 [[stage_in]]
, metal::float4 pos_6 [[position]]
, constant U& u [[buffer(1)]]
) {
    const GVO i_6 = { pos_6, varyings_9.ndc };
    bool local_12 = {};
    bool local_13 = {};
    float alpha = 0.0;
    int j = 0;
    metal::float3 rgb_1 = {};
    GOut o_4 = {};
    metal::float4 _e3 = u.gq;
    metal::float4 _e7 = u.gox;
    metal::float4 _e15 = u.goy;
    metal::float3 ro = (_e3.xyz + (_e7.xyz * i_6.ndc.x)) + (_e15.xyz * i_6.ndc.y);
    metal::float4 _e23 = u.gd;
    metal::float4 _e27 = u.gdx;
    metal::float4 _e35 = u.gdy;
    metal::float3 rd = (_e23.xyz + (_e27.xyz * i_6.ndc.x)) + (_e35.xyz * i_6.ndc.y);
    metal::float4 _e43 = u.gn;
    float dn = metal::dot(rd, _e43.xyz);
    float _e49 = u.gn.w;
    metal::float4 _e52 = u.gn;
    float t_2 = (_e49 - metal::dot(ro, _e52.xyz)) / ((dn == 0.0) ? 0.000000000000000000000000000001 : dn);
    metal::float3 w_2 = ro + (rd * t_2);
    metal::float4 _e65 = u.gu;
    float pu = metal::dot(w_2, _e65.xyz);
    metal::float4 _e70 = u.gv;
    float pv = metal::dot(w_2, _e70.xyz);
    metal::float2 p_2 = metal::float2(pu, pv);
    metal::float2 _e74 = metal::fwidth(p_2);
    metal::float2 pf_1 = metal::max(_e74, metal::float2(0.000000000000000000000000000001, 0.000000000000000000000000000001));
    float cosine = metal::abs(dn) / metal::max(metal::length(rd), 0.000000000000000000000000000001);
    if (!((cosine < 0.0001))) {
        float _e92 = u.gq.w;
        if (_e92 > 0.5) {
            local_13 = t_2 <= 0.0;
        } else {
            local_13 = false;
        }
        bool _e100 = local_13;
        local_12 = _e100;
    } else {
        local_12 = true;
    }
    bool _e102 = local_12;
    if (_e102) {
        metal::discard_fragment();
    }
    float mpp = metal::max(pf_1.x, pf_1.y);
    float _e109 = u.gs.y;
    float m_1 = metal::max(_e109, 2.0);
    float _e115 = u.gs.x;
    float c0_ = _e115 / mpp;
    float k0_ = metal::clamp(metal::ceil(metal::log(6.0 / c0_) / metal::log(m_1)), 0.0, 24.0);
    uint2 loop_bound_2 = uint2(4294967295u);
    bool loop_init_2 = true;
    while(true) {
        if (metal::all(loop_bound_2 == uint2(0u))) { break; }
        loop_bound_2 -= uint2(loop_bound_2.y == 0u, 1u);
        if (!loop_init_2) {
            int _e164 = j;
            j = as_type<int>(as_type<uint>(_e164) + as_type<uint>(1));
        }
        loop_init_2 = false;
        int _e130 = j;
        if (_e130 < 3) {
        } else {
            break;
        }
        {
            int _e133 = j;
            float k_4 = k0_ + static_cast<float>(_e133);
            float _e139 = u.gs.x;
            float s_2 = _e139 * metal::pow(m_1, k_4);
            metal::float4 _e144 = u.gax;
            float _e149 = u.gu.w;
            float _e153 = u.gv.w;
            metal::float2 ph_1 = (k_4 < 1.5) ? metal::float2(_e149, _e153) : _e144.zw;
            float _e158 = alpha;
            float _e159 = grid_on(p_2, pf_1, s_2, ph_1);
            float _e161 = grid_weight(s_2 / mpp, m_1);
            alpha = metal::max(_e158, _e159 * _e161);
        }
    }
    float _e167 = alpha;
    float _e171 = u.gcol.w;
    alpha = _e167 * _e171;
    metal::float4 _e175 = u.gcol;
    rgb_1 = _e175.xyz;
    float _e181 = u.gax.x;
    float on_v = 1.0 - metal::min((metal::abs(pu - _e181) / pf_1.x) / 1.2, 1.0);
    float _e195 = u.gax.y;
    float on_u = 1.0 - metal::min((metal::abs(pv - _e195) / pf_1.y) / 1.2, 1.0);
    float _e209 = u.gcv.w;
    float _e211 = alpha;
    if ((on_v * _e209) > _e211) {
        float _e216 = u.gcv.w;
        alpha = on_v * _e216;
        metal::float4 _e220 = u.gcv;
        rgb_1 = _e220.xyz;
    }
    float _e225 = u.gcu.w;
    float _e227 = alpha;
    if ((on_u * _e225) > _e227) {
        float _e232 = u.gcu.w;
        alpha = on_u * _e232;
        metal::float4 _e236 = u.gcu;
        rgb_1 = _e236.xyz;
    }
    float _e238 = alpha;
    alpha = _e238 * metal::smoothstep(0.0, 0.035, cosine);
    float _e243 = alpha;
    if (_e243 <= 0.002) {
        metal::discard_fragment();
    }
    metal::float3 _e248 = rgb_1;
    float _e249 = alpha;
    o_4.col = metal::float4(_e248, _e249);
    metal::float4x4 _e253 = u.vp;
    metal::float4 c_3 = _e253 * metal::float4(w_2, 1.0);
    o_4.depth = metal::clamp(c_3.z / c_3.w, 0.0, 1.0);
    GOut _e264 = o_4;
    const auto _tmp_4 = _e264;
    return fs_gridOutput { _tmp_4.col, _tmp_4.depth };
}
