// generated by tools/ShaderGen from scene.wgsl — do not edit; wgsl-sha256: 86c815f8b494c1a21e849bf84704f6e9b18c95c4f3c5fab198d90e41255b62d2
// language: metal2.3
#include <metal_stdlib>
#include <simd/simd.h>

using metal::uint;

struct type_1 {
    metal::float4 inner[16];
};
struct FB {
    metal::float4 fphase;
    metal::float4 fmode;
    type_1 stops;
};
struct type_6 {
    metal::uint4 inner[32];
};
struct type_7 {
    FB inner[4];
};
struct type_8 {
    metal::float4 inner[9];
};
struct U {
    metal::float4x4 vp;
    metal::float4 eye;
    metal::float4 clip;
    uint hover;
    uint hover_face;
    uint flags;
    uint mode;
    uint nsel;
    float ppx;
    float ppy;
    uint pad2_;
    type_6 sel;
    type_7 f;
    metal::float4 gu;
    metal::float4 gv;
    metal::float4 gn;
    metal::float4 gq;
    metal::float4 gs;
    metal::float4 gcol;
    metal::float4 gax;
    metal::float4 gcu;
    metal::float4 gcv;
    metal::float4 gox;
    metal::float4 goy;
    metal::float4 gd;
    metal::float4 gdx;
    metal::float4 gdy;
    metal::float4 lk;
    metal::float4 lk1_;
    metal::float4 key;
    metal::float4 keyc;
    metal::float4 bg0_;
    metal::float4 bg1_;
    metal::float4 bd;
    metal::float4 bdx;
    metal::float4 bdy;
    type_8 sh;
};
struct MX {
    metal::float4x4 m;
    metal::uint4 id;
};
struct VI {
    metal::packed_float3 p;
    uint id;
    metal::float4 col;
    uint face;
    char _pad4[12];
};
struct VO {
    metal::float4 pos;
    metal::packed_float3 world;
    uint id;
    metal::float4 col;
    uint face;
    char _pad5[12];
};
struct PickOut {
    metal::uint2 id;
    char _pad1[8];
    metal::float4 world;
};
struct IVI {
    metal::float3 p;
    metal::float2 uv;
    uint id;
    uint face;
    metal::float4 col;
};
struct IVO {
    metal::float4 pos;
    metal::float3 world;
    metal::float2 uv;
    uint id;
    uint face;
    metal::float4 col;
};
struct FVI {
    metal::float3 p;
    metal::float3 re;
    metal::float3 im;
};
struct FVO {
    metal::float4 pos;
    metal::float3 world;
    metal::float3 re;
    metal::packed_float3 im;
    uint layer;
};
struct GVO {
    metal::float4 pos;
    metal::float2 ndc;
    char _pad2[8];
};
struct GOut {
    metal::float4 col;
    float depth;
    char _pad2[12];
};
struct AP {
    metal::float4 a;
    metal::float4 b;
    metal::float4 c;
};
struct type_16 {
    AP inner[256];
};
struct APT {
    type_16 e;
};
struct PVI {
    metal::packed_float3 p;
    uint id;
    metal::float4 col;
    uint face;
    char _pad4[12];
    metal::packed_float3 n;
    uint slot;
};
struct PVO {
    metal::float4 pos;
    metal::packed_float3 world;
    uint id;
    metal::float4 col;
    uint face;
    char _pad5[12];
    metal::packed_float3 n;
    uint slot;
};
constant float PI = 3.1415927;
constant float DIELECTRIC_F0_ = 0.04;
constant float MIN_ROUGHNESS = 0.045;
constant float MIN_NDOTV = 0.0001;
constant uint SLOT_MASK = 255u;
constant uint STATED_ALPHA = 256u;
constant float TONE_START = 0.76;
constant float TONE_DESAT = 0.15;
constant float TONE_TOE_BREAK = 0.08;
constant float TONE_TOE_SLOPE = 6.25;
constant float TONE_TOE_OFFSET = 0.04;
constant float SRGB_BREAK = 0.0031308;
constant float SRGB_SLOPE = 12.92;
constant float SRGB_SCALE = 1.055;
constant float SRGB_OFFSET = 0.055;
constant float SRGB_GAMMA = 2.4;

bool clipped(
    metal::float3 w,
    constant U& u
) {
    bool local_21 = {};
    uint _e3 = u.flags;
    if ((_e3 & 1u) != 0u) {
        metal::float4 _e12 = u.clip;
        float _e18 = u.clip.w;
        local_21 = (metal::dot(_e12.xyz, w) + _e18) > 0.0;
    } else {
        local_21 = false;
    }
    bool _e23 = local_21;
    return _e23;
}

uint naga_div(uint lhs, uint rhs) {
    return lhs / metal::select(rhs, 1u, rhs == 0u);
}

metal::uint2 sel_entry(
    uint k_1,
    constant U& u
) {
    metal::uint4 q = u.sel.inner[naga_div(k_1, 2u)];
    if ((k_1 & 1u) == 0u) {
        return q.xy;
    }
    return q.zw;
}

bool is_selected(
    uint id,
    uint face,
    constant U& u
) {
    uint k_2 = 0u;
    bool local_22 = {};
    bool local_23 = {};
    uint2 loop_bound = uint2(4294967295u);
    bool loop_init = true;
    while(true) {
        if (metal::all(loop_bound == uint2(0u))) { break; }
        loop_bound -= uint2(loop_bound.y == 0u, 1u);
        if (!loop_init) {
            uint _e30 = k_2;
            k_2 = _e30 + 1u;
        }
        loop_init = false;
        uint _e4 = k_2;
        uint _e7 = u.nsel;
        if (_e4 < _e7) {
        } else {
            break;
        }
        {
            uint _e9 = k_2;
            metal::uint2 _e10 = sel_entry(_e9, u);
            if (_e10.x == id) {
                uint _e17 = u.mode;
                if (!((_e17 != 1u))) {
                    local_23 = _e10.y == face;
                } else {
                    local_23 = true;
                }
                bool _e26 = local_23;
                local_22 = _e26;
            } else {
                local_22 = false;
            }
            bool _e28 = local_22;
            if (_e28) {
                return true;
            }
        }
    }
    return false;
}

metal::float3 highlight(
    metal::float3 rgb_2,
    uint id_1,
    uint face_1,
    constant U& u
) {
    metal::float3 c = {};
    bool local_24 = {};
    c = rgb_2;
    if (id_1 == 0u) {
        metal::float3 _e6 = c;
        return _e6;
    }
    uint _e9 = u.mode;
    if (_e9 == 0u) {
        uint _e14 = u.hover;
        if (id_1 == _e14) {
            metal::float3 _e16 = c;
            c = metal::mix(_e16, metal::float3(0.2, 0.9, 1.0), 0.45);
        }
    } else {
        uint _e25 = u.mode;
        if (_e25 == 1u) {
            uint _e30 = u.hover;
            if (id_1 == _e30) {
                uint _e36 = u.hover_face;
                local_24 = face_1 == _e36;
            } else {
                local_24 = false;
            }
            bool _e39 = local_24;
            if (_e39) {
                metal::float3 _e40 = c;
                c = metal::mix(_e40, metal::float3(1.0, 1.0, 1.0), 0.35);
            }
            bool _e47 = is_selected(id_1, face_1, u);
            if (_e47) {
                metal::float3 _e48 = c;
                c = metal::mix(_e48, metal::float3(1.0, 0.35, 1.0), 0.6);
            }
        }
    }
    metal::float3 _e55 = c;
    return _e55;
}

uint naga_f2u32(float value) {
    return static_cast<uint>(metal::clamp(value, 0.0, 4294967000.0));
}

float field_value(
    metal::float3 re,
    metal::float3 im,
    uint l,
    constant U& u
) {
    float c_4 = u.f.inner[l].fphase.x;
    float s_1 = u.f.inner[l].fphase.y;
    float _e20 = u.f.inner[l].fmode.x;
    uint mode = naga_f2u32(_e20 + 0.5);
    if (mode == 0u) {
        return metal::sqrt(metal::dot(re, re) + metal::dot(im, im));
    }
    if (mode == 1u) {
        return metal::length((re * c_4) - (im * s_1));
    }
    if (mode == 2u) {
        return re.x;
    }
    if (mode == 3u) {
        return (re.x * c_4) - (im.x * s_1);
    }
    return metal::sqrt((re.x * re.x) + (im.x * im.x));
}

metal::float3 colour_map(
    float t,
    uint l_1,
    constant U& u
) {
    metal::float3 rgb_3 = {};
    uint k_3 = 1u;
    bool local_25 = {};
    float _e7 = u.f.inner[l_1].fmode.z;
    uint n_2 = naga_f2u32(_e7 + 0.5);
    metal::float4 _e16 = u.f.inner[l_1].stops.inner[0];
    rgb_3 = _e16.yzw;
    uint2 loop_bound_1 = uint2(4294967295u);
    bool loop_init_1 = true;
    while(true) {
        if (metal::all(loop_bound_1 == uint2(0u))) { break; }
        loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
        if (!loop_init_1) {
            uint _e64 = k_3;
            k_3 = _e64 + 1u;
        }
        loop_init_1 = false;
        uint _e21 = k_3;
        if (_e21 < n_2) {
        } else {
            break;
        }
        {
            uint _e27 = k_3;
            metal::float4 a_5 = u.f.inner[l_1].stops.inner[_e27 - 1u];
            uint _e36 = k_3;
            metal::float4 b = u.f.inner[l_1].stops.inner[_e36];
            if (!((t <= b.x))) {
                uint _e44 = k_3;
                local_25 = _e44 == (n_2 - 1u);
            } else {
                local_25 = true;
            }
            bool _e49 = local_25;
            if (_e49) {
                float w_3 = metal::clamp((t - a_5.x) / metal::max(b.x - a_5.x, 0.000001), 0.0, 1.0);
                rgb_3 = metal::mix(a_5.yzw, b.yzw, w_3);
                break;
            }
        }
    }
    metal::float3 _e67 = rgb_3;
    return _e67;
}

float grid_weight(
    float c_1,
    float m
) {
    return (0.45 * metal::clamp((c_1 - 6.0) / 8.0, 0.0, 1.0)) + (0.55 * metal::clamp((c_1 - (6.0 * m)) / (8.0 * m), 0.0, 1.0));
}

float grid_on(
    metal::float2 p,
    metal::float2 pf,
    float s,
    metal::float2 ph
) {
    metal::float2 a_6 = (p + ph) / metal::float2(s);
    metal::float2 d_1 = metal::abs(metal::fract(a_6 - metal::float2(0.5)) - metal::float2(0.5)) / metal::max(pf / metal::float2(s), metal::float2(0.000000000001, 0.000000000001));
    return 1.0 - metal::min(metal::min(d_1.x, d_1.y), 1.0);
}

metal::float3 env_dir(
    metal::float3 w_1,
    constant U& u
) {
    float _e4 = u.lk.z;
    float _e10 = u.lk.w;
    float _e17 = u.lk.w;
    float _e24 = u.lk.z;
    return metal::float3((_e4 * w_1.x) + (_e10 * w_1.y), (-(_e17) * w_1.x) + (_e24 * w_1.y), w_1.z);
}

metal::float2 oct_uv(
    metal::float3 d
) {
    metal::float2 p_1 = {};
    float s_2 = (metal::abs(d.x) + metal::abs(d.y)) + metal::abs(d.z);
    p_1 = d.xy / metal::float2(s_2);
    if (d.z < 0.0) {
        metal::float2 _e19 = p_1;
        metal::float2 _e29 = p_1;
        p_1 = (metal::float2(1.0, 1.0) - metal::abs(_e19.yx)) * metal::select(metal::float2(-1.0, -1.0), metal::float2(1.0, 1.0), _e29 >= metal::float2(0.0, 0.0));
    }
    metal::float2 _e36 = p_1;
    return (_e36 * 0.5) + metal::float2(0.5, 0.5);
}

metal::float3 env_radiance(
    metal::float3 w_2,
    float rough,
    constant U& u,
    metal::texture2d<float, metal::access::sample> env,
    metal::sampler env_s
) {
    metal::float3 _e4 = env_dir(w_2, u);
    metal::float2 _e5 = oct_uv(_e4);
    float _e9 = u.lk1_.y;
    metal::float4 _e11 = env.sample(env_s, _e5, metal::level(rough * _e9));
    return _e11.xyz;
}

metal::float3 irradiance(
    metal::float3 n_1,
    constant U& u
) {
    metal::float3 _e1 = env_dir(n_1, u);
    metal::float4 _e5 = u.sh.inner[0];
    metal::float4 _e10 = u.sh.inner[1];
    metal::float4 _e18 = u.sh.inner[2];
    metal::float4 _e26 = u.sh.inner[3];
    metal::float4 _e34 = u.sh.inner[4];
    metal::float4 _e44 = u.sh.inner[5];
    metal::float4 _e54 = u.sh.inner[6];
    metal::float4 _e68 = u.sh.inner[7];
    metal::float4 _e78 = u.sh.inner[8];
    return (((((((_e5.xyz + (_e10.xyz * _e1.y)) + (_e18.xyz * _e1.z)) + (_e26.xyz * _e1.x)) + (_e34.xyz * (_e1.x * _e1.y))) + (_e44.xyz * (_e1.y * _e1.z))) + (_e54.xyz * (((3.0 * _e1.z) * _e1.z) - 1.0))) + (_e68.xyz * (_e1.x * _e1.z))) + (_e78.xyz * ((_e1.x * _e1.x) - (_e1.y * _e1.y)));
}

metal::float2 brdf_lut(
    float nv,
    float rough_1,
    metal::sampler env_s,
    metal::texture2d<float, metal::access::sample> brdf
) {
    metal::float4 _e12 = brdf.sample(env_s, metal::float2(metal::clamp(nv, 0.0, 1.0), metal::clamp(rough_1, 0.0, 1.0)), metal::level(0.0));
    return _e12.xy;
}

float ggx_d(
    float nh_1,
    float a_2
) {
    float a2_ = a_2 * a_2;
    float f = ((nh_1 * nh_1) * (a2_ - 1.0)) + 1.0;
    return a2_ / ((PI * f) * f);
}

float smith_v(
    float nv_1,
    float nl,
    float a_3
) {
    float a2_1 = a_3 * a_3;
    float gv = nl * metal::sqrt(((nv_1 * nv_1) * (1.0 - a2_1)) + a2_1);
    float gl = nv_1 * metal::sqrt(((nl * nl) * (1.0 - a2_1)) + a2_1);
    return 0.5 / metal::max(gv + gl, 0.0000001);
}

metal::float3 schlick3_(
    metal::float3 f0_,
    float vh_1
) {
    float k_4 = metal::pow(1.0 - metal::clamp(vh_1, 0.0, 1.0), 5.0);
    return f0_ + ((metal::float3(1.0, 1.0, 1.0) - f0_) * k_4);
}

float schlick1_(
    float f0_1,
    float vh_2
) {
    return f0_1 + ((1.0 - f0_1) * metal::pow(1.0 - metal::clamp(vh_2, 0.0, 1.0), 5.0));
}

metal::float3 pbr_neutral(
    metal::float3 c0_
) {
    metal::float3 c_2 = {};
    c_2 = c0_;
    float _e3 = c_2.x;
    float _e5 = c_2.y;
    float _e7 = c_2.z;
    float x_1 = metal::min(_e3, metal::min(_e5, _e7));
    float offset = (x_1 < TONE_TOE_BREAK) ? (x_1 - ((TONE_TOE_SLOPE * x_1) * x_1)) : TONE_TOE_OFFSET;
    metal::float3 _e18 = c_2;
    c_2 = _e18 - metal::float3(offset, offset, offset);
    float _e22 = c_2.x;
    float _e24 = c_2.y;
    float _e26 = c_2.z;
    float peak = metal::max(_e22, metal::max(_e24, _e26));
    if (peak < TONE_START) {
        metal::float3 _e31 = c_2;
        return _e31;
    }
    float np = 1.0 - ((0.24000001 * 0.24000001) / ((peak + 0.24000001) - TONE_START));
    metal::float3 _e40 = c_2;
    c_2 = _e40 * (np / peak);
    float g = 1.0 - (1.0 / ((TONE_DESAT * (peak - np)) + 1.0));
    metal::float3 _e52 = c_2;
    return metal::mix(_e52, metal::float3(np, np, np), g);
}

float srgb1_(
    float x
) {
    float c_5 = metal::clamp(x, 0.0, 1.0);
    return (c_5 <= SRGB_BREAK) ? (c_5 * SRGB_SLOPE) : ((SRGB_SCALE * metal::pow(c_5, 0.41666666)) - SRGB_OFFSET);
}

metal::float3 display(
    metal::float3 lin,
    constant U& u
) {
    float _e4 = u.lk.x;
    metal::float3 _e11 = pbr_neutral(metal::max(lin * _e4, metal::float3(0.0, 0.0, 0.0)));
    float _e13 = srgb1_(_e11.x);
    float _e15 = srgb1_(_e11.y);
    float _e17 = srgb1_(_e11.z);
    return metal::float3(_e13, _e15, _e17);
}

metal::float3 highlight_pm(
    metal::float3 rgb_4,
    float a_4,
    uint id_2,
    uint face_2,
    constant U& u
) {
    metal::float3 c_3 = {};
    bool local_26 = {};
    c_3 = rgb_4;
    if (id_2 == 0u) {
        metal::float3 _e7 = c_3;
        return _e7;
    }
    uint _e10 = u.mode;
    if (_e10 == 0u) {
        uint _e15 = u.hover;
        if (id_2 == _e15) {
            metal::float3 _e17 = c_3;
            c_3 = metal::mix(_e17, metal::float3(0.2, 0.9, 1.0) * a_4, 0.45);
        }
    } else {
        uint _e27 = u.mode;
        if (_e27 == 1u) {
            uint _e32 = u.hover;
            if (id_2 == _e32) {
                uint _e38 = u.hover_face;
                local_26 = face_2 == _e38;
            } else {
                local_26 = false;
            }
            bool _e41 = local_26;
            if (_e41) {
                metal::float3 _e42 = c_3;
                c_3 = metal::mix(_e42, metal::float3(1.0, 1.0, 1.0) * a_4, 0.35);
            }
            bool _e50 = is_selected(id_2, face_2, u);
            if (_e50) {
                metal::float3 _e51 = c_3;
                c_3 = metal::mix(_e51, metal::float3(1.0, 0.35, 1.0) * a_4, 0.6);
            }
        }
    }
    metal::float3 _e59 = c_3;
    return _e59;
}

struct vsInput {
    metal::float3 p_2 [[attribute(0)]];
    uint id_3 [[attribute(1)]];
    metal::float4 col [[attribute(2)]];
    uint face_3 [[attribute(3)]];
};
struct vsOutput {
    metal::float4 pos [[position]];
    metal::float3 world [[user(loc0), center_perspective]];
    uint id [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face [[user(loc3), flat]];
};
vertex vsOutput vs(
  vsInput varyings [[stage_in]]
, constant U& u [[buffer(1)]]
, constant MX& mx [[buffer(2)]]
) {
    const VI v = { varyings.p_2, varyings.id_3, varyings.col, varyings.face_3 };
    VO o = {};
    metal::float4x4 _e4 = mx.m;
    metal::float3 p_2 = (_e4 * metal::float4(v.p, 1.0)).xyz;
    metal::float4x4 _e13 = u.vp;
    o.pos = _e13 * metal::float4(p_2, 1.0);
    uint _e20 = mx.id.y;
    if (_e20 != 0u) {
        uint _e26 = mx.id.y;
        float _e32 = u.ppx;
        uint _e37 = mx.id.y;
        float _e45 = u.ppy;
        metal::float2 px = metal::float2(static_cast<float>(_e26 & 1u) * _e32, static_cast<float>((_e37 >> 1u) & 1u) * _e45);
        metal::float4 _e50 = o.pos;
        float _e54 = o.pos.w;
        metal::float4 _e58 = o.pos;
        o.pos = metal::float4(_e50.xy + (px * _e54), _e58.zw);
    }
    o.world = p_2;
    uint _e67 = mx.id.x;
    o.id = v.id + _e67;
    o.col = v.col;
    o.face = v.face;
    VO _e73 = o;
    const auto _tmp = _e73;
    return vsOutput { _tmp.pos, _tmp.world, _tmp.id, _tmp.col, _tmp.face };
}


struct fs_colorInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_3 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_3 [[user(loc3), flat]];
};
struct fs_colorOutput {
    metal::float4 member_1 [[color(0)]];
};
fragment fs_colorOutput fs_color(
  fs_colorInput varyings_1 [[stage_in]]
, metal::float4 pos [[position]]
, bool front [[front_facing]]
, constant U& u [[buffer(1)]]
) {
    const VO i = { pos, varyings_1.world, varyings_1.id_3, varyings_1.col, varyings_1.face_3 };
    bool local = {};
    bool local_1 = {};
    bool local_2 = {};
    bool local_3 = {};
    bool local_4 = {};
    bool local_5 = {};
    bool local_6 = {};
    metal::float3 rgb = {};
    bool local_7 = {};
    float a = {};
    bool local_8 = {};
    metal::float3 _e3 = metal::dfdx(i.world);
    metal::float3 _e5 = metal::dfdy(i.world);
    metal::float3 n_3 = metal::normalize(metal::cross(_e3, _e5));
    bool _e9 = clipped(i.world, u);
    if (_e9) {
        metal::discard_fragment();
    }
    if (i.col.w == 0.0) {
        if (i.id != 0u) {
            uint _e21 = u.mode;
            local = _e21 == 0u;
        } else {
            local = false;
        }
        bool _e25 = local;
        if (_e25) {
            uint _e31 = u.hover;
            local_1 = i.id == _e31;
        } else {
            local_1 = false;
        }
        bool _e34 = local_1;
        if (_e34) {
            return fs_colorOutput { metal::float4(0.2, 0.9, 1.0, 0.18) };
        }
        if (i.id != 0u) {
            uint _e47 = u.mode;
            local_2 = _e47 == 1u;
        } else {
            local_2 = false;
        }
        bool _e51 = local_2;
        if (_e51) {
            bool _e56 = is_selected(i.id, i.face, u);
            local_3 = _e56;
        } else {
            local_3 = false;
        }
        bool _e58 = local_3;
        if (_e58) {
            return fs_colorOutput { metal::float4(1.0, 0.35, 1.0, 0.4) };
        }
        if (i.id != 0u) {
            uint _e71 = u.mode;
            local_4 = _e71 == 1u;
        } else {
            local_4 = false;
        }
        bool _e75 = local_4;
        if (_e75) {
            uint _e81 = u.hover;
            local_5 = i.id == _e81;
        } else {
            local_5 = false;
        }
        bool _e84 = local_5;
        if (_e84) {
            uint _e90 = u.hover_face;
            local_6 = i.face == _e90;
        } else {
            local_6 = false;
        }
        bool _e93 = local_6;
        if (_e93) {
            return fs_colorOutput { metal::float4(1.0, 1.0, 1.0, 0.25) };
        }
        metal::discard_fragment();
    }
    metal::float4 _e101 = u.eye;
    float d_2 = metal::abs(metal::dot(n_3, metal::normalize(_e101.xyz - i.world)));
    rgb = i.col.xyz * (0.3 + (0.7 * d_2));
    if (!(front)) {
        uint _e121 = u.flags;
        local_7 = (_e121 & 2u) != 0u;
    } else {
        local_7 = false;
    }
    bool _e127 = local_7;
    if (_e127) {
        rgb = i.col.xyz * 0.8;
    }
    a = i.col.w;
    uint _e137 = u.mode;
    if (_e137 == 0u) {
        bool _e144 = is_selected(i.id, 0u, u);
        local_8 = _e144;
    } else {
        local_8 = false;
    }
    bool _e146 = local_8;
    if (_e146) {
        float _e147 = a;
        a = metal::min(_e147, 0.5);
    }
    metal::float3 _e150 = rgb;
    metal::float3 _e153 = highlight(_e150, i.id, i.face, u);
    float _e154 = a;
    return fs_colorOutput { metal::float4(_e153, _e154) };
}


struct fs_lineInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_3 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_3 [[user(loc3), flat]];
};
struct fs_lineOutput {
    metal::float4 member_2 [[color(0)]];
};
fragment fs_lineOutput fs_line(
  fs_lineInput varyings_2 [[stage_in]]
, metal::float4 pos_1 [[position]]
) {
    const VO i_1 = { pos_1, varyings_2.world, varyings_2.id_3, varyings_2.col, varyings_2.face_3 };
    return fs_lineOutput { metal::float4(i_1.col.xyz, 1.0) };
}


struct fs_topInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_3 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_3 [[user(loc3), flat]];
};
struct fs_topOutput {
    metal::float4 member_3 [[color(0)]];
};
fragment fs_topOutput fs_top(
  fs_topInput varyings_3 [[stage_in]]
, metal::float4 pos_2 [[position]]
, constant U& u [[buffer(1)]]
) {
    const VO i_2 = { pos_2, varyings_3.world, varyings_3.id_3, varyings_3.col, varyings_3.face_3 };
    bool local_9 = {};
    bool local_10 = {};
    bool _e2 = clipped(i_2.world, u);
    if (!(_e2)) {
        uint _e8 = u.mode;
        local_9 = _e8 != 1u;
    } else {
        local_9 = true;
    }
    bool _e12 = local_9;
    if (!(_e12)) {
        bool _e18 = is_selected(i_2.id, i_2.face, u);
        local_10 = !(_e18);
    } else {
        local_10 = true;
    }
    bool _e21 = local_10;
    if (_e21) {
        metal::discard_fragment();
    }
    return fs_topOutput { metal::float4(1.0, 0.35, 1.0, 0.45) };
}


struct fs_edgeInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_3 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_3 [[user(loc3), flat]];
};
struct fs_edgeOutput {
    metal::float4 member_4 [[color(0)]];
};
fragment fs_edgeOutput fs_edge(
  fs_edgeInput varyings_4 [[stage_in]]
, metal::float4 pos_3 [[position]]
, constant U& u [[buffer(1)]]
) {
    const VO i_3 = { pos_3, varyings_4.world, varyings_4.id_3, varyings_4.col, varyings_4.face_3 };
    bool show = false;
    bool local_11 = {};
    bool _e2 = clipped(i_3.world, u);
    if (_e2) {
        metal::discard_fragment();
    }
    uint _e7 = u.mode;
    if (_e7 == 0u) {
        bool _e12 = is_selected(i_3.id, 0u, u);
        show = _e12;
    }
    uint _e15 = u.mode;
    if (_e15 == 1u) {
        bool _e22 = is_selected(i_3.id, i_3.face & 65535u, u);
        if (!(_e22)) {
            bool _e30 = is_selected(i_3.id, i_3.face >> 16u, u);
            local_11 = _e30;
        } else {
            local_11 = true;
        }
        bool _e32 = local_11;
        show = _e32;
    }
    bool _e33 = show;
    if (!(_e33)) {
        metal::discard_fragment();
    }
    return fs_edgeOutput { metal::float4(1.0, 0.35, 1.0, 1.0) };
}


struct fs_pickInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_3 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_3 [[user(loc3), flat]];
};
struct fs_pickOutput {
    metal::uint2 id [[color(0)]];
    metal::float4 world [[color(1)]];
};
fragment fs_pickOutput fs_pick(
  fs_pickInput varyings_5 [[stage_in]]
, metal::float4 pos_4 [[position]]
, constant U& u [[buffer(1)]]
) {
    const VO i_4 = { pos_4, varyings_5.world, varyings_5.id_3, varyings_5.col, varyings_5.face_3 };
    PickOut o_1 = {};
    bool _e2 = clipped(i_4.world, u);
    if (_e2) {
        metal::discard_fragment();
    }
    o_1.id = metal::uint2(i_4.id, i_4.face);
    o_1.world = metal::float4(i_4.world, 1.0);
    PickOut _e12 = o_1;
    const auto _tmp_1 = _e12;
    return fs_pickOutput { _tmp_1.id, _tmp_1.world };
}


struct vs_imageInput {
    metal::float3 p_2 [[attribute(0)]];
    metal::float2 uv [[attribute(1)]];
    uint id_3 [[attribute(2)]];
    uint face_3 [[attribute(3)]];
    metal::float4 col [[attribute(4)]];
};
struct vs_imageOutput {
    metal::float4 pos [[position]];
    metal::float3 world [[user(loc0), center_perspective]];
    metal::float2 uv [[user(loc1), center_perspective]];
    uint id [[user(loc2), flat]];
    uint face [[user(loc3), flat]];
    metal::float4 col [[user(loc4), center_perspective]];
};
vertex vs_imageOutput vs_image(
  vs_imageInput varyings_6 [[stage_in]]
, constant U& u [[buffer(1)]]
, constant MX& mx [[buffer(2)]]
) {
    const IVI v_1 = { varyings_6.p_2, varyings_6.uv, varyings_6.id_3, varyings_6.face_3, varyings_6.col };
    IVO o_2 = {};
    metal::float4x4 _e4 = mx.m;
    metal::float3 p_3 = (_e4 * metal::float4(v_1.p, 1.0)).xyz;
    metal::float4x4 _e13 = u.vp;
    o_2.pos = _e13 * metal::float4(p_3, 1.0);
    o_2.world = p_3;
    o_2.uv = v_1.uv;
    uint _e25 = mx.id.x;
    o_2.id = v_1.id + _e25;
    o_2.face = v_1.face;
    o_2.col = v_1.col;
    IVO _e31 = o_2;
    const auto _tmp_2 = _e31;
    return vs_imageOutput { _tmp_2.pos, _tmp_2.world, _tmp_2.uv, _tmp_2.id, _tmp_2.face, _tmp_2.col };
}


struct fs_imageInput {
    metal::float3 world [[user(loc0), center_perspective]];
    metal::float2 uv [[user(loc1), center_perspective]];
    uint id_3 [[user(loc2), flat]];
    uint face_3 [[user(loc3), flat]];
    metal::float4 col [[user(loc4), center_perspective]];
};
struct fs_imageOutput {
    metal::float4 member_7 [[color(0)]];
};
fragment fs_imageOutput fs_image(
  fs_imageInput varyings_7 [[stage_in]]
, metal::float4 pos_5 [[position]]
, constant U& u [[buffer(1)]]
, metal::texture2d<float, metal::access::sample> img [[texture(0)]]
, metal::sampler img_s [[sampler(0)]]
) {
    const IVO i_5 = { pos_5, varyings_7.world, varyings_7.uv, varyings_7.id_3, varyings_7.face_3, varyings_7.col };
    bool local_12 = {};
    bool local_13 = {};
    bool local_14 = {};
    float a_1 = {};
    bool local_15 = {};
    metal::float4 t_1 = img.sample(img_s, i_5.uv);
    bool _e6 = clipped(i_5.world, u);
    if (_e6) {
        metal::discard_fragment();
    }
    if (!((i_5.uv.x < -(0.0001)))) {
        local_12 = i_5.uv.x > (1.0 + 0.0001);
    } else {
        local_12 = true;
    }
    bool _e21 = local_12;
    if (!(_e21)) {
        local_13 = i_5.uv.y < -(0.0001);
    } else {
        local_13 = true;
    }
    bool _e30 = local_13;
    if (!(_e30)) {
        local_14 = i_5.uv.y > (1.0 + 0.0001);
    } else {
        local_14 = true;
    }
    bool _e40 = local_14;
    if (_e40) {
        metal::discard_fragment();
    }
    a_1 = t_1.w * i_5.col.w;
    uint _e48 = u.mode;
    if (_e48 == 0u) {
        bool _e55 = is_selected(i_5.id, 0u, u);
        local_15 = _e55;
    } else {
        local_15 = false;
    }
    bool _e57 = local_15;
    if (_e57) {
        float _e58 = a_1;
        a_1 = metal::min(_e58, 0.5);
    }
    float _e61 = a_1;
    if (_e61 <= 0.0) {
        metal::discard_fragment();
    }
    metal::float3 _e67 = highlight(t_1.xyz, i_5.id, i_5.face, u);
    float _e68 = a_1;
    return fs_imageOutput { metal::float4(_e67, _e68) };
}


struct vs_fieldInput {
    metal::float3 p_2 [[attribute(0)]];
    metal::float3 re_1 [[attribute(1)]];
    metal::float3 im_1 [[attribute(2)]];
};
struct vs_fieldOutput {
    metal::float4 pos [[position]];
    metal::float3 world [[user(loc0), center_perspective]];
    metal::float3 re [[user(loc1), center_perspective]];
    metal::float3 im [[user(loc2), center_perspective]];
    uint layer [[user(loc3), flat]];
};
vertex vs_fieldOutput vs_field(
  vs_fieldInput varyings_8 [[stage_in]]
, constant U& u [[buffer(1)]]
, constant MX& mx [[buffer(2)]]
) {
    const FVI v_2 = { varyings_8.p_2, varyings_8.re_1, varyings_8.im_1 };
    FVO o_3 = {};
    metal::float4x4 _e5 = u.vp;
    o_3.pos = _e5 * metal::float4(v_2.p, 1.0);
    o_3.world = v_2.p;
    o_3.re = v_2.re;
    o_3.im = v_2.im;
    uint _e20 = mx.id.y;
    o_3.layer = metal::min(_e20, 3u);
    FVO _e23 = o_3;
    const auto _tmp_3 = _e23;
    return vs_fieldOutput { _tmp_3.pos, _tmp_3.world, _tmp_3.re, _tmp_3.im, _tmp_3.layer };
}


struct fs_fieldInput {
    metal::float3 world [[user(loc0), center_perspective]];
    metal::float3 re_1 [[user(loc1), center_perspective]];
    metal::float3 im_1 [[user(loc2), center_perspective]];
    uint layer [[user(loc3), flat]];
};
struct fs_fieldOutput {
    metal::float4 member_9 [[color(0)]];
};
fragment fs_fieldOutput fs_field(
  fs_fieldInput varyings_9 [[stage_in]]
, metal::float4 pos_6 [[position]]
, constant U& u [[buffer(1)]]
) {
    const FVO i_6 = { pos_6, varyings_9.world, varyings_9.re_1, varyings_9.im_1, varyings_9.layer };
    bool local_16 = {};
    float v_3 = {};
    uint l_2 = i_6.layer;
    float _e7 = u.f.inner[l_2].fmode.w;
    if (_e7 < 0.5) {
        bool _e13 = clipped(i_6.world, u);
        local_16 = _e13;
    } else {
        local_16 = false;
    }
    bool _e15 = local_16;
    if (_e15) {
        metal::discard_fragment();
    }
    float _e18 = field_value(i_6.re, i_6.im, l_2, u);
    v_3 = _e18;
    float _e25 = u.f.inner[l_2].fmode.y;
    if (_e25 > 0.5) {
        float _e28 = v_3;
        v_3 = 6.0206 * metal::log2(metal::max(metal::abs(_e28), 0.000000000000000000000000000001));
    }
    float lo = u.f.inner[l_2].fphase.z;
    float hi = u.f.inner[l_2].fphase.w;
    float _e47 = v_3;
    float t_2 = metal::clamp((_e47 - lo) / metal::max(hi - lo, 0.000000000000000000000000000001), 0.0, 1.0);
    metal::float3 _e56 = colour_map(t_2, l_2, u);
    return fs_fieldOutput { metal::float4(_e56, 1.0) };
}


struct vs_gridInput {
};
struct vs_gridOutput {
    metal::float4 pos [[position]];
    metal::float2 ndc [[user(loc0), center_perspective]];
};
vertex vs_gridOutput vs_grid(
  uint k [[vertex_id]]
) {
    GVO o_4 = {};
    float cx = (static_cast<float>((22u >> k) & 1u) * 2.0) - 1.0;
    float cy = (static_cast<float>((52u >> k) & 1u) * 2.0) - 1.0;
    o_4.pos = metal::float4(cx, cy, 0.5, 1.0);
    o_4.ndc = metal::float2(cx, cy);
    GVO _e26 = o_4;
    const auto _tmp_4 = _e26;
    return vs_gridOutput { _tmp_4.pos, _tmp_4.ndc };
}


struct fs_gridInput {
    metal::float2 ndc [[user(loc0), center_perspective]];
};
struct fs_gridOutput {
    metal::float4 col [[color(0)]];
    float depth [[depth(any)]];
};
fragment fs_gridOutput fs_grid(
  fs_gridInput varyings_11 [[stage_in]]
, metal::float4 pos_7 [[position]]
, constant U& u [[buffer(1)]]
) {
    const GVO i_7 = { pos_7, varyings_11.ndc };
    bool local_17 = {};
    bool local_18 = {};
    float alpha = 0.0;
    int j = 0;
    metal::float3 rgb_1 = {};
    GOut o_5 = {};
    metal::float4 _e3 = u.gq;
    metal::float4 _e7 = u.gox;
    metal::float4 _e15 = u.goy;
    metal::float3 ro = (_e3.xyz + (_e7.xyz * i_7.ndc.x)) + (_e15.xyz * i_7.ndc.y);
    metal::float4 _e23 = u.gd;
    metal::float4 _e27 = u.gdx;
    metal::float4 _e35 = u.gdy;
    metal::float3 rd = (_e23.xyz + (_e27.xyz * i_7.ndc.x)) + (_e35.xyz * i_7.ndc.y);
    metal::float4 _e43 = u.gn;
    float dn = metal::dot(rd, _e43.xyz);
    float _e49 = u.gn.w;
    metal::float4 _e52 = u.gn;
    float t_3 = (_e49 - metal::dot(ro, _e52.xyz)) / ((dn == 0.0) ? 0.000000000000000000000000000001 : dn);
    metal::float3 w_4 = ro + (rd * t_3);
    metal::float4 _e65 = u.gu;
    float pu = metal::dot(w_4, _e65.xyz);
    metal::float4 _e70 = u.gv;
    float pv = metal::dot(w_4, _e70.xyz);
    metal::float2 p_4 = metal::float2(pu, pv);
    metal::float2 _e74 = metal::fwidth(p_4);
    metal::float2 pf_1 = metal::max(_e74, metal::float2(0.000000000000000000000000000001, 0.000000000000000000000000000001));
    float cosine = metal::abs(dn) / metal::max(metal::length(rd), 0.000000000000000000000000000001);
    if (!((cosine < 0.0001))) {
        float _e92 = u.gq.w;
        if (_e92 > 0.5) {
            local_18 = t_3 <= 0.0;
        } else {
            local_18 = false;
        }
        bool _e100 = local_18;
        local_17 = _e100;
    } else {
        local_17 = true;
    }
    bool _e102 = local_17;
    if (_e102) {
        metal::discard_fragment();
    }
    float mpp = metal::max(pf_1.x, pf_1.y);
    float _e109 = u.gs.y;
    float m_1 = metal::max(_e109, 2.0);
    float _e115 = u.gs.x;
    float c0_1 = _e115 / mpp;
    float k0_ = metal::clamp(metal::ceil(metal::log(6.0 / c0_1) / metal::log(m_1)), 0.0, 24.0);
    uint2 loop_bound_2 = uint2(4294967295u);
    bool loop_init_2 = true;
    while(true) {
        if (metal::all(loop_bound_2 == uint2(0u))) { break; }
        loop_bound_2 -= uint2(loop_bound_2.y == 0u, 1u);
        if (!loop_init_2) {
            int _e164 = j;
            j = as_type<int>(as_type<uint>(_e164) + as_type<uint>(1));
        }
        loop_init_2 = false;
        int _e130 = j;
        if (_e130 < 3) {
        } else {
            break;
        }
        {
            int _e133 = j;
            float k_5 = k0_ + static_cast<float>(_e133);
            float _e139 = u.gs.x;
            float s_3 = _e139 * metal::pow(m_1, k_5);
            metal::float4 _e144 = u.gax;
            float _e149 = u.gu.w;
            float _e153 = u.gv.w;
            metal::float2 ph_1 = (k_5 < 1.5) ? metal::float2(_e149, _e153) : _e144.zw;
            float _e158 = alpha;
            float _e159 = grid_on(p_4, pf_1, s_3, ph_1);
            float _e161 = grid_weight(s_3 / mpp, m_1);
            alpha = metal::max(_e158, _e159 * _e161);
        }
    }
    float _e167 = alpha;
    float _e171 = u.gcol.w;
    alpha = _e167 * _e171;
    metal::float4 _e175 = u.gcol;
    rgb_1 = _e175.xyz;
    float _e181 = u.gax.x;
    float on_v = 1.0 - metal::min((metal::abs(pu - _e181) / pf_1.x) / 1.2, 1.0);
    float _e195 = u.gax.y;
    float on_u = 1.0 - metal::min((metal::abs(pv - _e195) / pf_1.y) / 1.2, 1.0);
    float _e209 = u.gcv.w;
    float _e211 = alpha;
    if ((on_v * _e209) > _e211) {
        float _e216 = u.gcv.w;
        alpha = on_v * _e216;
        metal::float4 _e220 = u.gcv;
        rgb_1 = _e220.xyz;
    }
    float _e225 = u.gcu.w;
    float _e227 = alpha;
    if ((on_u * _e225) > _e227) {
        float _e232 = u.gcu.w;
        alpha = on_u * _e232;
        metal::float4 _e236 = u.gcu;
        rgb_1 = _e236.xyz;
    }
    float _e238 = alpha;
    alpha = _e238 * metal::smoothstep(0.0, 0.035, cosine);
    float _e243 = alpha;
    if (_e243 <= 0.002) {
        metal::discard_fragment();
    }
    metal::float3 _e248 = rgb_1;
    float _e249 = alpha;
    o_5.col = metal::float4(_e248, _e249);
    metal::float4x4 _e253 = u.vp;
    metal::float4 c_6 = _e253 * metal::float4(w_4, 1.0);
    o_5.depth = metal::clamp(c_6.z / c_6.w, 0.0, 1.0);
    GOut _e264 = o_5;
    const auto _tmp_5 = _e264;
    return fs_gridOutput { _tmp_5.col, _tmp_5.depth };
}


struct vs_pbrInput {
    metal::float3 p_2 [[attribute(0)]];
    uint id_3 [[attribute(1)]];
    metal::float4 col [[attribute(2)]];
    uint face_3 [[attribute(3)]];
    metal::float3 n_2 [[attribute(4)]];
    uint slot [[attribute(5)]];
};
struct vs_pbrOutput {
    metal::float4 pos [[position]];
    metal::float3 world [[user(loc0), center_perspective]];
    uint id [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face [[user(loc3), flat]];
    metal::float3 n [[user(loc4), center_perspective]];
    uint slot [[user(loc5), flat]];
};
vertex vs_pbrOutput vs_pbr(
  vs_pbrInput varyings_12 [[stage_in]]
, constant U& u [[buffer(1)]]
, constant MX& mx [[buffer(2)]]
) {
    const PVI v_4 = { varyings_12.p_2, varyings_12.id_3, varyings_12.col, varyings_12.face_3, {}, varyings_12.n_2, varyings_12.slot };
    PVO o_6 = {};
    metal::float4x4 _e4 = mx.m;
    metal::float3 p_5 = (_e4 * metal::float4(v_4.p, 1.0)).xyz;
    metal::float4x4 _e13 = u.vp;
    o_6.pos = _e13 * metal::float4(p_5, 1.0);
    o_6.world = p_5;
    uint _e23 = mx.id.x;
    o_6.id = v_4.id + _e23;
    o_6.col = v_4.col;
    o_6.face = v_4.face;
    metal::float4x4 _e32 = mx.m;
    o_6.n = (_e32 * metal::float4(v_4.n, 0.0)).xyz;
    o_6.slot = v_4.slot;
    PVO _e40 = o_6;
    const auto _tmp_6 = _e40;
    return vs_pbrOutput { _tmp_6.pos, _tmp_6.world, _tmp_6.id, _tmp_6.col, _tmp_6.face, _tmp_6.n, _tmp_6.slot };
}


struct fs_pbrInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_3 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_3 [[user(loc3), flat]];
    metal::float3 n_2 [[user(loc4), center_perspective]];
    uint slot [[user(loc5), flat]];
};
struct fs_pbrOutput {
    metal::float4 member_13 [[color(0)]];
};
fragment fs_pbrOutput fs_pbr(
  fs_pbrInput varyings_13 [[stage_in]]
, metal::float4 pos_8 [[position]]
, bool front_1 [[front_facing]]
, constant U& u [[buffer(1)]]
, constant APT& ap [[buffer(4)]]
, metal::texture2d<float, metal::access::sample> env [[texture(1)]]
, metal::sampler env_s [[sampler(1)]]
, metal::texture2d<float, metal::access::sample> brdf [[texture(2)]]
) {
    const PVO i_8 = { pos_8, varyings_13.world, varyings_13.id_3, varyings_13.col, varyings_13.face_3, {}, varyings_13.n_2, varyings_13.slot };
    metal::float3 n = {};
    metal::float3 surface = {};
    bool local_19 = {};
    float nh = 0.0;
    float vh = 0.0;
    float ad = {};
    metal::float3 coat = {};
    float ac = {};
    float alpha_1 = 1.0;
    float cov = {};
    bool local_20 = {};
    bool _e3 = clipped(i_8.world, u);
    if (_e3) {
        metal::discard_fragment();
    }
    AP m_2 = ap.e.inner[i_8.slot & SLOT_MASK];
    metal::float4 _e13 = u.eye;
    metal::float3 v_5 = metal::normalize(_e13.xyz - i_8.world);
    n = metal::normalize(i_8.n);
    if (!(front_1)) {
        uint _e24 = u.flags;
        if ((_e24 & 2u) != 0u) {
            n = v_5;
        } else {
            metal::float3 _e29 = n;
            n = -(_e29);
        }
    }
    metal::float3 _e31 = n;
    float nv_2 = metal::max(metal::dot(_e31, v_5), MIN_NDOTV);
    metal::float3 base = m_2.a.xyz;
    float metal_ = metal::clamp(m_2.a.w, 0.0, 1.0);
    float rough_2 = metal::clamp(m_2.b.x, 0.0, 1.0);
    float t_4 = metal::clamp(m_2.b.y, 0.0, 1.0);
    float fr0_ = (m_2.b.z - 1.0) / (m_2.b.z + 1.0);
    metal::float3 f0_2 = metal::mix(metal::float3(fr0_ * fr0_, fr0_ * fr0_, fr0_ * fr0_), base, metal_);
    metal::float2 _e66 = brdf_lut(nv_2, rough_2, env_s, brdf);
    metal::float3 spec_albedo = (f0_2 * _e66.x) + metal::float3(_e66.y, _e66.y, _e66.y);
    metal::float3 _e74 = n;
    metal::float3 _e78 = n;
    metal::float3 r = ((2.0 * metal::dot(_e74, v_5)) * _e78) - v_5;
    metal::float3 _e81 = env_radiance(r, rough_2, u, env, env_s);
    float _e85 = u.lk.y;
    metal::float3 reflected = _e81 * _e85;
    metal::float3 _e87 = n;
    metal::float3 _e88 = irradiance(_e87, u);
    float _e92 = u.lk.y;
    metal::float3 irr = _e88 * _e92;
    surface = (reflected * spec_albedo) + ((((((metal::float3(1.0, 1.0, 1.0) - spec_albedo) * (1.0 - metal_)) * (1.0 - t_4)) * base) * irr) / metal::float3(3.1415927));
    metal::float4 _e115 = u.key;
    metal::float3 l_3 = _e115.xyz;
    metal::float3 _e117 = n;
    float nl_1 = metal::dot(_e117, l_3);
    if (nl_1 > 0.0) {
        metal::float4 _e125 = u.keyc;
        metal::float4 _e129 = u.keyc;
        local_19 = metal::dot(_e125.xyz, _e129.xyz) > 0.0;
    } else {
        local_19 = false;
    }
    bool keyon = local_19;
    if (keyon) {
        metal::float3 h = metal::normalize(l_3 + v_5);
        metal::float3 _e142 = n;
        nh = metal::max(metal::dot(_e142, h), 0.0);
        vh = metal::max(metal::dot(v_5, h), 0.0);
        ad = metal::max(rough_2, MIN_ROUGHNESS);
        float _e152 = ad;
        float _e153 = ad;
        ad = _e152 * _e153;
        float _e155 = vh;
        metal::float3 _e156 = schlick3_(f0_2, _e155);
        float _e157 = nh;
        float _e158 = ad;
        float _e159 = ggx_d(_e157, _e158);
        float _e160 = ad;
        float _e161 = smith_v(nv_2, nl_1, _e160);
        metal::float3 lobe = _e156 * (_e159 * _e161);
        metal::float3 body = ((((metal::float3(1.0, 1.0, 1.0) - _e156) * (1.0 - metal_)) * (1.0 - t_4)) * base) / metal::float3(3.1415927);
        metal::float3 _e179 = surface;
        metal::float4 _e183 = u.keyc;
        float _e189 = u.lk.y;
        surface = _e179 + ((((lobe + body) * _e183.xyz) * _e189) * nl_1);
    }
    float cc = metal::clamp(m_2.b.w, 0.0, 1.0);
    if (cc > 0.0) {
        float ccr = metal::clamp(m_2.c.x, 0.0, 1.0);
        metal::float2 _e205 = brdf_lut(nv_2, ccr, env_s, brdf);
        float coat_albedo = (DIELECTRIC_F0_ * _e205.x) + _e205.y;
        metal::float3 _e211 = env_radiance(r, ccr, u, env, env_s);
        float _e215 = u.lk.y;
        coat = (_e211 * _e215) * coat_albedo;
        if (keyon) {
            ac = metal::max(ccr, MIN_ROUGHNESS);
            float _e222 = ac;
            float _e223 = ac;
            ac = _e222 * _e223;
            metal::float3 _e225 = coat;
            metal::float4 _e228 = u.keyc;
            float _e233 = u.lk.y;
            float _e236 = vh;
            float _e237 = schlick1_(DIELECTRIC_F0_, _e236);
            float _e238 = nh;
            float _e239 = ac;
            float _e240 = ggx_d(_e238, _e239);
            float _e242 = ac;
            float _e243 = smith_v(nv_2, nl_1, _e242);
            coat = _e225 + ((_e228.xyz * _e233) * (((_e237 * _e240) * _e243) * nl_1));
        }
        metal::float3 _e248 = surface;
        metal::float3 _e253 = coat;
        surface = (_e248 * (1.0 - (cc * coat_albedo))) + (_e253 * cc);
    }
    if (t_4 > 0.0) {
        metal::float3 att = m_2.c.yzw;
        float fs = ((spec_albedo.x + spec_albedo.y) + spec_albedo.z) / 3.0;
        float tau = ((att.x + att.y) + att.z) / 3.0;
        float through = t_4 * (1.0 - fs);
        alpha_1 = 1.0 - (through * tau);
        metal::float3 _e282 = surface;
        surface = _e282 + ((((through * (1.0 - tau)) * att) * irr) / metal::float3(3.1415927));
    }
    cov = ((i_8.slot & STATED_ALPHA) != 0u) ? i_8.col.w : 1.0;
    uint _e304 = u.mode;
    if (_e304 == 0u) {
        bool _e311 = is_selected(i_8.id, 0u, u);
        local_20 = _e311;
    } else {
        local_20 = false;
    }
    bool _e313 = local_20;
    if (_e313) {
        float _e314 = cov;
        cov = metal::min(_e314, 0.5);
    }
    float _e317 = alpha_1;
    float _e318 = cov;
    float a_7 = _e317 * _e318;
    metal::float3 _e320 = surface;
    metal::float3 _e321 = display(_e320, u);
    float _e322 = cov;
    metal::float3 _e326 = highlight_pm(_e321 * _e322, a_7, i_8.id, i_8.face, u);
    return fs_pbrOutput { metal::float4(_e326, a_7) };
}


struct fs_backdropInput {
    metal::float2 ndc [[user(loc0), center_perspective]];
};
struct fs_backdropOutput {
    metal::float4 member_14 [[color(0)]];
};
fragment fs_backdropOutput fs_backdrop(
  fs_backdropInput varyings_14 [[stage_in]]
, metal::float4 pos_9 [[position]]
, constant U& u [[buffer(1)]]
, metal::texture2d<float, metal::access::sample> env [[texture(1)]]
, metal::sampler env_s [[sampler(1)]]
) {
    const GVO i_9 = { pos_9, varyings_14.ndc };
    float _e4 = u.lk1_.x;
    if (_e4 < 1.5) {
        float t_5 = metal::clamp((i_9.ndc.y * 0.5) + 0.5, 0.0, 1.0);
        metal::float4 _e18 = u.bg1_;
        metal::float4 _e22 = u.bg0_;
        return fs_backdropOutput { metal::float4(metal::mix(_e18.xyz, _e22.xyz, t_5), 1.0) };
    }
    metal::float4 _e29 = u.bd;
    metal::float4 _e33 = u.bdx;
    metal::float4 _e41 = u.bdy;
    metal::float3 d_3 = (_e29.xyz + (_e33.xyz * i_9.ndc.x)) + (_e41.xyz * i_9.ndc.y);
    metal::float3 _e49 = env_dir(d_3, u);
    metal::float2 _e50 = oct_uv(_e49);
    metal::float4 _e52 = env.sample(env_s, _e50, metal::level(0.0));
    float _e57 = u.lk.y;
    metal::float3 c_7 = _e52.xyz * _e57;
    metal::float3 _e59 = display(c_7, u);
    return fs_backdropOutput { metal::float4(_e59, 1.0) };
}
