// generated by tools/ShaderGen from scene.wgsl — do not edit; wgsl-sha256: d6861d123f2d5e2bec7a4544c4ae3e3c45b2ab1c47b1199ca94fc032b0ab5768
// language: metal2.3
#include <metal_stdlib>
#include <simd/simd.h>

using metal::uint;

struct type_4 {
    metal::uint4 inner[32];
};
struct type_5 {
    metal::float4 inner[16];
};
struct U {
    metal::float4x4 vp;
    metal::float4 eye;
    metal::float4 clip;
    uint hover;
    uint hover_face;
    uint flags;
    uint mode;
    uint nsel;
    uint pad0_;
    uint pad1_;
    uint pad2_;
    type_4 sel;
    metal::float4 fphase;
    metal::float4 fmode;
    type_5 stops;
    metal::float4 gu;
    metal::float4 gv;
    metal::float4 gn;
    metal::float4 gq;
    metal::float4 gs;
    metal::float4 gcol;
    metal::float4 gax;
    metal::float4 gcu;
    metal::float4 gcv;
};
struct MX {
    metal::float4x4 m;
    metal::uint4 id;
};
struct VI {
    metal::packed_float3 p;
    uint id;
    metal::float4 col;
    uint face;
    char _pad4[12];
};
struct VO {
    metal::float4 pos;
    metal::packed_float3 world;
    uint id;
    metal::float4 col;
    uint face;
    char _pad5[12];
};
struct PickOut {
    metal::uint2 id;
    char _pad1[8];
    metal::float4 world;
};
struct FVI {
    metal::float3 p;
    metal::float3 re;
    metal::float3 im;
};
struct FVO {
    metal::float4 pos;
    metal::float3 world;
    metal::float3 re;
    metal::float3 im;
};
struct GVO {
    metal::float4 pos;
    metal::float3 world;
};

bool clipped(
    metal::float3 w,
    constant U& u
) {
    bool local_4 = {};
    uint _e3 = u.flags;
    if ((_e3 & 1u) != 0u) {
        metal::float4 _e12 = u.clip;
        float _e18 = u.clip.w;
        local_4 = (metal::dot(_e12.xyz, w) + _e18) > 0.0;
    } else {
        local_4 = false;
    }
    bool _e23 = local_4;
    return _e23;
}

uint naga_div(uint lhs, uint rhs) {
    return lhs / metal::select(rhs, 1u, rhs == 0u);
}

metal::uint2 sel_entry(
    uint k_1,
    constant U& u
) {
    metal::uint4 q = u.sel.inner[naga_div(k_1, 2u)];
    if ((k_1 & 1u) == 0u) {
        return q.xy;
    }
    return q.zw;
}

bool is_selected(
    uint id,
    uint face,
    constant U& u
) {
    uint k_2 = 0u;
    bool local_5 = {};
    bool local_6 = {};
    uint2 loop_bound = uint2(4294967295u);
    bool loop_init = true;
    while(true) {
        if (metal::all(loop_bound == uint2(0u))) { break; }
        loop_bound -= uint2(loop_bound.y == 0u, 1u);
        if (!loop_init) {
            uint _e30 = k_2;
            k_2 = _e30 + 1u;
        }
        loop_init = false;
        uint _e4 = k_2;
        uint _e7 = u.nsel;
        if (_e4 < _e7) {
        } else {
            break;
        }
        {
            uint _e9 = k_2;
            metal::uint2 _e10 = sel_entry(_e9, u);
            if (_e10.x == id) {
                uint _e17 = u.mode;
                if (!((_e17 != 1u))) {
                    local_6 = _e10.y == face;
                } else {
                    local_6 = true;
                }
                bool _e26 = local_6;
                local_5 = _e26;
            } else {
                local_5 = false;
            }
            bool _e28 = local_5;
            if (_e28) {
                return true;
            }
        }
    }
    return false;
}

metal::float3 highlight(
    metal::float3 rgb_2,
    uint id_1,
    uint face_1,
    constant U& u
) {
    metal::float3 c = {};
    bool local_7 = {};
    c = rgb_2;
    if (id_1 == 0u) {
        metal::float3 _e6 = c;
        return _e6;
    }
    uint _e9 = u.mode;
    if (_e9 == 0u) {
        uint _e14 = u.hover;
        if (id_1 == _e14) {
            metal::float3 _e16 = c;
            c = metal::mix(_e16, metal::float3(0.2, 0.9, 1.0), 0.45);
        }
    } else {
        uint _e25 = u.mode;
        if (_e25 == 1u) {
            uint _e30 = u.hover;
            if (id_1 == _e30) {
                uint _e36 = u.hover_face;
                local_7 = face_1 == _e36;
            } else {
                local_7 = false;
            }
            bool _e39 = local_7;
            if (_e39) {
                metal::float3 _e40 = c;
                c = metal::mix(_e40, metal::float3(1.0, 1.0, 1.0), 0.35);
            }
            bool _e47 = is_selected(id_1, face_1, u);
            if (_e47) {
                metal::float3 _e48 = c;
                c = metal::mix(_e48, metal::float3(1.0, 0.35, 1.0), 0.6);
            }
        }
    }
    metal::float3 _e55 = c;
    return _e55;
}

uint naga_f2u32(float value) {
    return static_cast<uint>(metal::clamp(value, 0.0, 4294967000.0));
}

float field_value(
    metal::float3 re,
    metal::float3 im,
    constant U& u
) {
    float c_1 = u.fphase.x;
    float s = u.fphase.y;
    float _e13 = u.fmode.x;
    uint mode = naga_f2u32(_e13 + 0.5);
    if (mode == 0u) {
        return metal::sqrt(metal::dot(re, re) + metal::dot(im, im));
    }
    if (mode == 1u) {
        return metal::length((re * c_1) - (im * s));
    }
    if (mode == 2u) {
        return re.x;
    }
    if (mode == 3u) {
        return (re.x * c_1) - (im.x * s);
    }
    return metal::sqrt((re.x * re.x) + (im.x * im.x));
}

metal::float3 colour_map(
    float t,
    constant U& u
) {
    metal::float3 rgb_3 = {};
    uint k_3 = 1u;
    bool local_8 = {};
    float _e4 = u.fmode.z;
    uint n = naga_f2u32(_e4 + 0.5);
    metal::float4 _e11 = u.stops.inner[0];
    rgb_3 = _e11.yzw;
    uint2 loop_bound_1 = uint2(4294967295u);
    bool loop_init_1 = true;
    while(true) {
        if (metal::all(loop_bound_1 == uint2(0u))) { break; }
        loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
        if (!loop_init_1) {
            uint _e55 = k_3;
            k_3 = _e55 + 1u;
        }
        loop_init_1 = false;
        uint _e16 = k_3;
        if (_e16 < n) {
        } else {
            break;
        }
        {
            uint _e20 = k_3;
            metal::float4 a = u.stops.inner[_e20 - 1u];
            uint _e27 = k_3;
            metal::float4 b = u.stops.inner[_e27];
            if (!((t <= b.x))) {
                uint _e35 = k_3;
                local_8 = _e35 == (n - 1u);
            } else {
                local_8 = true;
            }
            bool _e40 = local_8;
            if (_e40) {
                float w_1 = metal::clamp((t - a.x) / metal::max(b.x - a.x, 0.000001), 0.0, 1.0);
                rgb_3 = metal::mix(a.yzw, b.yzw, w_1);
                break;
            }
        }
    }
    metal::float3 _e58 = rgb_3;
    return _e58;
}

struct vsInput {
    metal::float3 p [[attribute(0)]];
    uint id_2 [[attribute(1)]];
    metal::float4 col [[attribute(2)]];
    uint face_2 [[attribute(3)]];
};
struct vsOutput {
    metal::float4 pos [[position]];
    metal::float3 world [[user(loc0), center_perspective]];
    uint id [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face [[user(loc3), flat]];
};
vertex vsOutput vs(
  vsInput varyings [[stage_in]]
, constant U& u [[buffer(1)]]
, constant MX& mx [[buffer(2)]]
) {
    const VI v = { varyings.p, varyings.id_2, varyings.col, varyings.face_2 };
    VO o = {};
    metal::float4x4 _e4 = mx.m;
    metal::float3 p = (_e4 * metal::float4(v.p, 1.0)).xyz;
    metal::float4x4 _e13 = u.vp;
    o.pos = _e13 * metal::float4(p, 1.0);
    o.world = p;
    uint _e23 = mx.id.x;
    o.id = v.id + _e23;
    o.col = v.col;
    o.face = v.face;
    VO _e29 = o;
    const auto _tmp = _e29;
    return vsOutput { _tmp.pos, _tmp.world, _tmp.id, _tmp.col, _tmp.face };
}


struct fs_colorInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_2 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_2 [[user(loc3), flat]];
};
struct fs_colorOutput {
    metal::float4 member_1 [[color(0)]];
};
fragment fs_colorOutput fs_color(
  fs_colorInput varyings_1 [[stage_in]]
, metal::float4 pos [[position]]
, bool front [[front_facing]]
, constant U& u [[buffer(1)]]
) {
    const VO i = { pos, varyings_1.world, varyings_1.id_2, varyings_1.col, varyings_1.face_2 };
    metal::float3 rgb = {};
    bool local = {};
    bool _e3 = clipped(i.world, u);
    if (_e3) {
        metal::discard_fragment();
    }
    metal::float3 _e5 = metal::dfdx(i.world);
    metal::float3 _e7 = metal::dfdy(i.world);
    metal::float3 n_1 = metal::normalize(metal::cross(_e5, _e7));
    metal::float4 _e12 = u.eye;
    float d = metal::abs(metal::dot(n_1, metal::normalize(_e12.xyz - i.world)));
    rgb = i.col.xyz * (0.3 + (0.7 * d));
    if (!(front)) {
        uint _e32 = u.flags;
        local = (_e32 & 2u) != 0u;
    } else {
        local = false;
    }
    bool _e38 = local;
    if (_e38) {
        rgb = i.col.xyz * 0.8;
    }
    metal::float3 _e43 = rgb;
    metal::float3 _e46 = highlight(_e43, i.id, i.face, u);
    return fs_colorOutput { metal::float4(_e46, i.col.w) };
}


struct fs_lineInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_2 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_2 [[user(loc3), flat]];
};
struct fs_lineOutput {
    metal::float4 member_2 [[color(0)]];
};
fragment fs_lineOutput fs_line(
  fs_lineInput varyings_2 [[stage_in]]
, metal::float4 pos_1 [[position]]
) {
    const VO i_1 = { pos_1, varyings_2.world, varyings_2.id_2, varyings_2.col, varyings_2.face_2 };
    return fs_lineOutput { metal::float4(i_1.col.xyz, 1.0) };
}


struct fs_topInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_2 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_2 [[user(loc3), flat]];
};
struct fs_topOutput {
    metal::float4 member_3 [[color(0)]];
};
fragment fs_topOutput fs_top(
  fs_topInput varyings_3 [[stage_in]]
, metal::float4 pos_2 [[position]]
, constant U& u [[buffer(1)]]
) {
    const VO i_2 = { pos_2, varyings_3.world, varyings_3.id_2, varyings_3.col, varyings_3.face_2 };
    bool local_1 = {};
    bool local_2 = {};
    bool _e2 = clipped(i_2.world, u);
    if (!(_e2)) {
        uint _e8 = u.mode;
        local_1 = _e8 != 1u;
    } else {
        local_1 = true;
    }
    bool _e12 = local_1;
    if (!(_e12)) {
        bool _e18 = is_selected(i_2.id, i_2.face, u);
        local_2 = !(_e18);
    } else {
        local_2 = true;
    }
    bool _e21 = local_2;
    if (_e21) {
        metal::discard_fragment();
    }
    return fs_topOutput { metal::float4(1.0, 0.35, 1.0, 0.45) };
}


struct fs_edgeInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_2 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_2 [[user(loc3), flat]];
};
struct fs_edgeOutput {
    metal::float4 member_4 [[color(0)]];
};
fragment fs_edgeOutput fs_edge(
  fs_edgeInput varyings_4 [[stage_in]]
, metal::float4 pos_3 [[position]]
, constant U& u [[buffer(1)]]
) {
    const VO i_3 = { pos_3, varyings_4.world, varyings_4.id_2, varyings_4.col, varyings_4.face_2 };
    bool show = false;
    bool local_3 = {};
    bool _e2 = clipped(i_3.world, u);
    if (_e2) {
        metal::discard_fragment();
    }
    uint _e7 = u.mode;
    if (_e7 == 0u) {
        bool _e12 = is_selected(i_3.id, 0u, u);
        show = _e12;
    }
    uint _e15 = u.mode;
    if (_e15 == 1u) {
        bool _e22 = is_selected(i_3.id, i_3.face & 65535u, u);
        if (!(_e22)) {
            bool _e30 = is_selected(i_3.id, i_3.face >> 16u, u);
            local_3 = _e30;
        } else {
            local_3 = true;
        }
        bool _e32 = local_3;
        show = _e32;
    }
    bool _e33 = show;
    if (!(_e33)) {
        metal::discard_fragment();
    }
    return fs_edgeOutput { metal::float4(1.0, 0.35, 1.0, 1.0) };
}


struct fs_pickInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_2 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
    uint face_2 [[user(loc3), flat]];
};
struct fs_pickOutput {
    metal::uint2 id [[color(0)]];
    metal::float4 world [[color(1)]];
};
fragment fs_pickOutput fs_pick(
  fs_pickInput varyings_5 [[stage_in]]
, metal::float4 pos_4 [[position]]
, constant U& u [[buffer(1)]]
) {
    const VO i_4 = { pos_4, varyings_5.world, varyings_5.id_2, varyings_5.col, varyings_5.face_2 };
    PickOut o_1 = {};
    bool _e2 = clipped(i_4.world, u);
    if (_e2) {
        metal::discard_fragment();
    }
    o_1.id = metal::uint2(i_4.id, i_4.face);
    o_1.world = metal::float4(i_4.world, 1.0);
    PickOut _e12 = o_1;
    const auto _tmp_1 = _e12;
    return fs_pickOutput { _tmp_1.id, _tmp_1.world };
}


struct vs_fieldInput {
    metal::float3 p [[attribute(0)]];
    metal::float3 re_1 [[attribute(1)]];
    metal::float3 im_1 [[attribute(2)]];
};
struct vs_fieldOutput {
    metal::float4 pos [[position]];
    metal::float3 world [[user(loc0), center_perspective]];
    metal::float3 re [[user(loc1), center_perspective]];
    metal::float3 im [[user(loc2), center_perspective]];
};
vertex vs_fieldOutput vs_field(
  vs_fieldInput varyings_6 [[stage_in]]
, constant U& u [[buffer(1)]]
) {
    const FVI v_1 = { varyings_6.p, varyings_6.re_1, varyings_6.im_1 };
    FVO o_2 = {};
    metal::float4x4 _e5 = u.vp;
    o_2.pos = _e5 * metal::float4(v_1.p, 1.0);
    o_2.world = v_1.p;
    o_2.re = v_1.re;
    o_2.im = v_1.im;
    FVO _e16 = o_2;
    const auto _tmp_2 = _e16;
    return vs_fieldOutput { _tmp_2.pos, _tmp_2.world, _tmp_2.re, _tmp_2.im };
}


struct fs_fieldInput {
    metal::float3 world [[user(loc0), center_perspective]];
    metal::float3 re_1 [[user(loc1), center_perspective]];
    metal::float3 im_1 [[user(loc2), center_perspective]];
};
struct fs_fieldOutput {
    metal::float4 member_7 [[color(0)]];
};
fragment fs_fieldOutput fs_field(
  fs_fieldInput varyings_7 [[stage_in]]
, metal::float4 pos_5 [[position]]
, constant U& u [[buffer(1)]]
) {
    const FVO i_5 = { pos_5, varyings_7.world, varyings_7.re_1, varyings_7.im_1 };
    float v_2 = {};
    bool _e2 = clipped(i_5.world, u);
    if (_e2) {
        metal::discard_fragment();
    }
    float _e5 = field_value(i_5.re, i_5.im, u);
    v_2 = _e5;
    float _e10 = u.fmode.y;
    if (_e10 > 0.5) {
        float _e13 = v_2;
        v_2 = 6.0206 * metal::log2(metal::max(metal::abs(_e13), 0.000000000000000000000000000001));
    }
    float _e20 = v_2;
    float _e24 = u.fphase.z;
    float _e29 = u.fphase.w;
    float _e33 = u.fphase.z;
    float t_1 = metal::clamp((_e20 - _e24) / metal::max(_e29 - _e33, 0.000000000000000000000000000001), 0.0, 1.0);
    metal::float3 _e41 = colour_map(t_1, u);
    return fs_fieldOutput { metal::float4(_e41, 1.0) };
}


struct vs_gridInput {
};
struct vs_gridOutput {
    metal::float4 pos [[position]];
    metal::float3 world [[user(loc0), center_perspective]];
};
vertex vs_gridOutput vs_grid(
  uint k [[vertex_id]]
, constant U& u [[buffer(1)]]
) {
    GVO o_3 = {};
    float cx = (static_cast<float>((22u >> k) & 1u) * 2.0) - 1.0;
    float cy = (static_cast<float>((52u >> k) & 1u) * 2.0) - 1.0;
    metal::float4 _e21 = u.gq;
    metal::float4 _e25 = u.gu;
    metal::float4 _e30 = u.gv;
    float _e37 = u.gq.w;
    metal::float3 p_1 = _e21.xyz + (((_e25.xyz * cx) + (_e30.xyz * cy)) * _e37);
    metal::float4x4 _e44 = u.vp;
    o_3.pos = _e44 * metal::float4(p_1, 1.0);
    o_3.world = p_1;
    GVO _e49 = o_3;
    const auto _tmp_3 = _e49;
    return vs_gridOutput { _tmp_3.pos, _tmp_3.world };
}


struct fs_gridInput {
    metal::float3 world [[user(loc0), center_perspective]];
};
struct fs_gridOutput {
    metal::float4 member_9 [[color(0)]];
};
fragment fs_gridOutput fs_grid(
  fs_gridInput varyings_9 [[stage_in]]
, metal::float4 pos_6 [[position]]
, constant U& u [[buffer(1)]]
) {
    const GVO i_6 = { pos_6, varyings_9.world };
    float alpha = {};
    metal::float3 rgb_1 = {};
    bool _e2 = clipped(i_6.world, u);
    if (_e2) {
        metal::discard_fragment();
    }
    metal::float4 _e6 = u.gu;
    float pu = metal::dot(i_6.world, _e6.xyz);
    metal::float4 _e12 = u.gv;
    float pv = metal::dot(i_6.world, _e12.xyz);
    float _e19 = u.gu.w;
    float _e23 = u.gv.w;
    float _e29 = u.gs.x;
    metal::float2 a_1 = (metal::float2(pu, pv) + metal::float2(_e19, _e23)) / metal::float2(_e29);
    metal::float2 _e32 = metal::fwidth(a_1);
    metal::float2 fw = metal::max(_e32, metal::float2(0.0000001, 0.0000001));
    float cell_px = 1.0 / metal::max(fw.x, fw.y);
    float minor_fade = metal::clamp((cell_px - 4.0) / 6.0, 0.0, 1.0);
    metal::float2 dm = metal::abs(metal::fract(a_1 - metal::float2(0.5)) - metal::float2(0.5)) / fw;
    float line_minor = 1.0 - metal::min(metal::min(dm.x, dm.y), 1.0);
    float _e68 = u.gs.y;
    metal::float2 am = a_1 / metal::float2(_e68);
    float _e82 = u.gs.y;
    metal::float2 dmaj = metal::abs(metal::fract(am - metal::float2(0.5)) - metal::float2(0.5)) / (fw / metal::float2(_e82));
    float line_major = 1.0 - metal::min(metal::min(dmaj.x, dmaj.y), 1.0);
    metal::float4 _e96 = u.gq;
    float r = metal::length(i_6.world - _e96.xyz);
    metal::float4 _e102 = u.eye;
    metal::float3 view = metal::normalize(_e102.xyz - i_6.world);
    float _e110 = u.gs.z;
    float _e116 = u.gs.z;
    metal::float4 _e122 = u.gn;
    float fade = (1.0 - metal::smoothstep(0.45 * _e110, _e116, r)) * metal::smoothstep(0.03, 0.35, metal::abs(metal::dot(_e122.xyz, view)));
    float _e137 = u.gcol.w;
    alpha = metal::max((line_minor * 0.45) * minor_fade, line_major) * _e137;
    metal::float4 _e142 = u.gcol;
    rgb_1 = _e142.xyz;
    float _e148 = u.gax.x;
    float _e151 = metal::fwidth(pu);
    float on_v = 1.0 - metal::min((metal::abs(pu - _e148) / metal::max(_e151, 0.000000000001)) / 1.2, 1.0);
    float _e164 = u.gax.y;
    float _e167 = metal::fwidth(pv);
    float on_u = 1.0 - metal::min((metal::abs(pv - _e164) / metal::max(_e167, 0.000000000001)) / 1.2, 1.0);
    float _e180 = u.gcv.w;
    float _e182 = alpha;
    if ((on_v * _e180) > _e182) {
        float _e187 = u.gcv.w;
        alpha = on_v * _e187;
        metal::float4 _e191 = u.gcv;
        rgb_1 = _e191.xyz;
    }
    float _e196 = u.gcu.w;
    float _e198 = alpha;
    if ((on_u * _e196) > _e198) {
        float _e203 = u.gcu.w;
        alpha = on_u * _e203;
        metal::float4 _e207 = u.gcu;
        rgb_1 = _e207.xyz;
    }
    float _e209 = alpha;
    alpha = _e209 * fade;
    float _e211 = alpha;
    if (_e211 <= 0.002) {
        metal::discard_fragment();
    }
    metal::float3 _e214 = rgb_1;
    float _e215 = alpha;
    return fs_gridOutput { metal::float4(_e214, _e215) };
}
