//! shadergen — brief-em3d-28 R-em3d28-1c: ONE WGSL source, cross-compiled offline by naga's LIBRARY
//! into the three shader languages route A's backends load (Metal, D3D11, Vulkan).
//!
//!   shadergen <in.wgsl> <out-dir>           write <stem>.metal, <stem>.hlsl, <stem>.spv
//!   shadergen --check <in.wgsl> <out-dir>   exit 1 unless every output records the WGSL's hash
//!
//! Every output RECORDS the SHA-256 of the WGSL's exact bytes, so a test can fail when someone edits
//! the WGSL without regenerating (gate 1b):
//!   - .metal / .hlsl: the first line is
//!     `// generated by tools/ShaderGen from <file>.wgsl — do not edit; wgsl-sha256: <hex>`
//!   - .spv: an `OpSourceExtension "wgsl-sha256:<hex>"` instruction (opcode 4), at the end of the
//!     debug section's first group (after OpString/OpSource, before OpName). Not OpModuleProcessed, the
//!     semantically closer instruction: that one needs SPIR-V 1.1, and spirv-val rejects it in the 1.0
//!     module a Vulkan 1.0 driver requires (checked, spirv-tools 2024).
//!
//! The bindings are STATED here rather than left to naga's defaults, which is why no fix-up is needed
//! (the naga CLI has no MSL binding map and emits `[[user(fake0)]]` — findings §5.4):
//!   - uniform block @group(0) @binding(0): MSL `[[buffer(1)]]` in every entry point (the vertex
//!     buffer is stage_in from buffer 0 through the pipeline's vertex descriptor); HLSL `register(b0)`;
//!     SPIR-V descriptor set 0, binding 0.
//!   - the per-draw transform @group(0) @binding(1) (brief-em3d-46): MSL `[[buffer(2)]]`; HLSL
//!     `register(b1)`; SPIR-V descriptor set 0, binding 1. A uniform, not an immediate: naga writes an
//!     immediate to HLSL as `ConstantBuffer<T>`, which Shader Model 5.0 does not compile.
//!   - an image's texture @group(1) @binding(0) and sampler @group(1) @binding(1) (brief-em3d-101): MSL
//!     `[[texture(0)]]` / `[[sampler(0)]]`; HLSL `register(t0)` / `register(s0)`; SPIR-V set 1, bindings 0 and 1.
//!   - the realistic view's appearance table @group(0) @binding(2) (brief-em3d-106): MSL `[[buffer(4)]]`; HLSL `register(b2)`;
//!     SPIR-V set 0 binding 2. Its environment @group(2) @binding(0..2) — the prefiltered map, its sampler, the split-sum table:
//!     MSL `[[texture(1)]]`, `[[sampler(1)]]`, `[[texture(2)]]`; HLSL `t1`, `s1`, `t2`; SPIR-V set 2, bindings 0, 1, 2.
//!
//! Deterministic: every option is set explicitly (naga's SPIR-V default flips a DEBUG flag with the
//! build profile, which would make a debug-built tool emit different words).

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use naga::back::{hlsl, msl, spv};
use naga::valid::{Capabilities, ValidationFlags, Validator};
use sha2::{Digest, Sha256};

/// Uniform block binding in the WGSL: @group(0) @binding(0).
const UNIFORM: naga::ResourceBinding = naga::ResourceBinding { group: 0, binding: 0 };
/// MSL argument-table slot of the uniform block (slot 0 is the vertex buffer).
const MSL_UNIFORM_BUFFER: u8 = 1;
/// brief-em3d-46 — the per-draw transform block, @group(0) @binding(1): MSL slot 2 (setVertexBytes per draw),
/// HLSL register b1, SPIR-V descriptor set 0 binding 1.
const TRANSFORM: naga::ResourceBinding = naga::ResourceBinding { group: 0, binding: 1 };
const MSL_TRANSFORM_BUFFER: u8 = 2;
/// brief-em3d-101 — an image draw's texture, @group(1) @binding(0), and its sampler, @group(1) @binding(1): MSL texture 0 and
/// sampler 0; HLSL t0 and s0; SPIR-V descriptor set 1, bindings 0 and 1 (a set of its own, so the Vulkan backend binds one small
/// set per texture and leaves the uniform set it writes once alone).
const IMAGE: naga::ResourceBinding = naga::ResourceBinding { group: 1, binding: 0 };
const IMAGE_SAMPLER: naga::ResourceBinding = naga::ResourceBinding { group: 1, binding: 1 };
/// brief-em3d-106 — the realistic view's appearance table, @group(0) @binding(2): MSL buffer 4 (index 3 is the shade stream's vertex
/// buffer, which shares the argument table), HLSL b2, SPIR-V set 0 binding 2.
const APPEARANCES: naga::ResourceBinding = naga::ResourceBinding { group: 0, binding: 2 };
const MSL_APPEARANCE_BUFFER: u8 = 4;
/// brief-em3d-106 — the environment's prefiltered map @group(2) @binding(0), its sampler @binding(1) and the split-sum table
/// @binding(2): MSL texture 1, sampler 1, texture 2; HLSL t1, s1, t2; SPIR-V descriptor set 2, bindings 0, 1, 2 (a set of its own,
/// bound once per frame by the realistic pipelines).
const ENV: naga::ResourceBinding = naga::ResourceBinding { group: 2, binding: 0 };
const ENV_SAMPLER: naga::ResourceBinding = naga::ResourceBinding { group: 2, binding: 1 };
const BRDF: naga::ResourceBinding = naga::ResourceBinding { group: 2, binding: 2 };
/// Every sampler and the HLSL register it is rewritten to (plain_hlsl_samplers).
const HLSL_SAMPLERS: [(&str, u32); 2] = [("img_s", 0), ("env_s", 1)];
/// MSL 2.3: macOS 11+.
const MSL_VERSION: (u8, u8) = (2, 3);
/// SPIR-V 1.0: every Vulkan 1.0 driver.
const SPV_VERSION: (u8, u8) = (1, 0);

/// OpSourceExtension: "a string describing ... the source" — legal in every SPIR-V version, and ignored
/// by every consumer. Carries `wgsl-sha256:<hex>`.
const OP_SOURCE_EXTENSION: u32 = 4;

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let result = match args.as_slice() {
        [flag, wgsl, out] if flag == "--check" => check(Path::new(wgsl), Path::new(out)),
        [wgsl, out] => generate(Path::new(wgsl), Path::new(out)).map(|_| true),
        _ => {
            eprintln!("usage: shadergen <in.wgsl> <out-dir> | shadergen --check <in.wgsl> <out-dir>");
            return ExitCode::from(2);
        }
    };
    match result {
        Ok(true) => ExitCode::SUCCESS,
        Ok(false) => ExitCode::from(1),
        Err(e) => {
            eprintln!("shadergen: {e}");
            ExitCode::from(2)
        }
    }
}

fn hex_sha256(bytes: &[u8]) -> String {
    Sha256::digest(bytes).iter().map(|b| format!("{b:02x}")).collect()
}

fn outputs(wgsl: &Path, out: &Path) -> Result<(String, PathBuf, PathBuf, PathBuf), String> {
    let stem = wgsl.file_stem().and_then(|s| s.to_str()).ok_or("the WGSL path has no file stem")?;
    let file = wgsl.file_name().and_then(|s| s.to_str()).ok_or("the WGSL path has no file name")?;
    Ok((
        file.to_string(),
        out.join(format!("{stem}.metal")),
        out.join(format!("{stem}.hlsl")),
        out.join(format!("{stem}.spv")),
    ))
}

fn header(file: &str, hash: &str) -> String {
    format!("// generated by tools/ShaderGen from {file} — do not edit; wgsl-sha256: {hash}\n")
}

fn generate(wgsl_path: &Path, out: &Path) -> Result<(), String> {
    let bytes = std::fs::read(wgsl_path).map_err(|e| format!("{}: {e}", wgsl_path.display()))?;
    let text = std::str::from_utf8(&bytes).map_err(|e| format!("{}: not UTF-8: {e}", wgsl_path.display()))?;
    let hash = hex_sha256(&bytes);
    let (file, metal_path, hlsl_path, spv_path) = outputs(wgsl_path, out)?;

    let module = naga::front::wgsl::parse_str(text).map_err(|e| e.emit_to_string(text))?;
    let info = Validator::new(ValidationFlags::all(), Capabilities::empty())
        .validate(&module)
        .map_err(|e| e.emit_to_string(text))?;

    // ---- MSL ----
    let mut resources = msl::EntryPointResources::default();
    resources.resources.insert(
        TRANSFORM,
        msl::BindTarget { buffer: Some(MSL_TRANSFORM_BUFFER), ..Default::default() },
    );
    resources.resources.insert(
        UNIFORM,
        msl::BindTarget { buffer: Some(MSL_UNIFORM_BUFFER), ..Default::default() },
    );
    resources.resources.insert(IMAGE, msl::BindTarget { texture: Some(0), ..Default::default() });
    resources.resources.insert(
        IMAGE_SAMPLER,
        msl::BindTarget { sampler: Some(msl::BindSamplerTarget::Resource(0)), ..Default::default() },
    );
    resources.resources.insert(
        APPEARANCES,
        msl::BindTarget { buffer: Some(MSL_APPEARANCE_BUFFER), ..Default::default() },
    );
    resources.resources.insert(ENV, msl::BindTarget { texture: Some(1), ..Default::default() });
    resources.resources.insert(
        ENV_SAMPLER,
        msl::BindTarget { sampler: Some(msl::BindSamplerTarget::Resource(1)), ..Default::default() },
    );
    resources.resources.insert(BRDF, msl::BindTarget { texture: Some(2), ..Default::default() });
    let mut msl_opts = msl::Options {
        lang_version: MSL_VERSION,
        fake_missing_bindings: false,
        ..Default::default()
    };
    for ep in &module.entry_points {
        msl_opts.per_entry_point_map.insert(ep.name.clone(), resources.clone());
    }
    let msl_pipe = msl::PipelineOptions::default(); // stage_in (vertex_pulling_transform = false)
    let (msl_src, _) = msl::write_string(&module, &info, &msl_opts, &msl_pipe).map_err(|e| format!("MSL: {e}"))?;

    // ---- HLSL ----
    let mut hlsl_opts = hlsl::Options {
        shader_model: hlsl::ShaderModel::V5_0,
        fake_missing_bindings: false,
        ..Default::default()
    };
    hlsl_opts.binding_map.insert(UNIFORM, hlsl::BindTarget { space: 0, register: 0, ..Default::default() });
    hlsl_opts.binding_map.insert(TRANSFORM, hlsl::BindTarget { space: 0, register: 1, ..Default::default() });
    hlsl_opts.binding_map.insert(IMAGE, hlsl::BindTarget { space: 0, register: 0, ..Default::default() });
    hlsl_opts.binding_map.insert(IMAGE_SAMPLER, hlsl::BindTarget { space: 0, register: 0, ..Default::default() });
    hlsl_opts.binding_map.insert(APPEARANCES, hlsl::BindTarget { space: 0, register: 2, ..Default::default() });
    hlsl_opts.binding_map.insert(ENV, hlsl::BindTarget { space: 0, register: 1, ..Default::default() });
    hlsl_opts.binding_map.insert(ENV_SAMPLER, hlsl::BindTarget { space: 0, register: 1, ..Default::default() });
    hlsl_opts.binding_map.insert(BRDF, hlsl::BindTarget { space: 0, register: 2, ..Default::default() });
    // naga writes every sampler through a D3D12 sampler HEAP (a 2,048-entry array indexed by a per-group StructuredBuffer), which
    // a D3D11 Shader Model 5.0 compile cannot take — D3D11 has 16 sampler slots. The index buffer is given a register here only so
    // naga writes it; plain_hlsl_samplers then rewrites the heap away into a plain `SamplerState … : register(sN)`.
    hlsl_opts.sampler_buffer_binding_map.insert(
        hlsl::SamplerIndexBufferKey { group: IMAGE_SAMPLER.group },
        hlsl::BindTarget { space: 0, register: 15, ..Default::default() },
    );
    hlsl_opts.sampler_buffer_binding_map.insert(
        hlsl::SamplerIndexBufferKey { group: ENV_SAMPLER.group },
        hlsl::BindTarget { space: 0, register: 14, ..Default::default() },
    );
    let mut hlsl_src = String::new();
    let hlsl_pipe = hlsl::PipelineOptions::default();
    hlsl::Writer::new(&mut hlsl_src, &hlsl_opts, &hlsl_pipe)
        .write(&module, &info, None)
        .map_err(|e| format!("HLSL: {e}"))?;

    let hlsl_src = plain_hlsl_samplers(&hlsl_src)?;

    // ---- SPIR-V ----
    let mut spv_opts = spv::Options {
        lang_version: SPV_VERSION,
        flags: spv::WriterFlags::ADJUST_COORDINATE_SPACE | spv::WriterFlags::LABEL_VARYINGS | spv::WriterFlags::CLAMP_FRAG_DEPTH,
        fake_missing_bindings: false,
        ..Default::default()
    };
    spv_opts.binding_map.insert(UNIFORM, spv::BindingInfo { descriptor_set: 0, binding: 0, binding_array_size: None });
    spv_opts.binding_map.insert(TRANSFORM, spv::BindingInfo { descriptor_set: 0, binding: 1, binding_array_size: None });
    spv_opts.binding_map.insert(IMAGE, spv::BindingInfo { descriptor_set: 1, binding: 0, binding_array_size: None });
    spv_opts.binding_map.insert(IMAGE_SAMPLER, spv::BindingInfo { descriptor_set: 1, binding: 1, binding_array_size: None });
    spv_opts.binding_map.insert(APPEARANCES, spv::BindingInfo { descriptor_set: 0, binding: 2, binding_array_size: None });
    spv_opts.binding_map.insert(ENV, spv::BindingInfo { descriptor_set: 2, binding: 0, binding_array_size: None });
    spv_opts.binding_map.insert(ENV_SAMPLER, spv::BindingInfo { descriptor_set: 2, binding: 1, binding_array_size: None });
    spv_opts.binding_map.insert(BRDF, spv::BindingInfo { descriptor_set: 2, binding: 2, binding_array_size: None });
    let words = spv::write_vec(&module, &info, &spv_opts, None).map_err(|e| format!("SPIR-V: {e}"))?;
    let words = insert_hash_string(&words, &format!("wgsl-sha256:{hash}"))?;

    // The SPIR-V we wrote must still be a module naga itself accepts and validates.
    let spv_bytes: Vec<u8> = words.iter().flat_map(|w| w.to_le_bytes()).collect();
    let reread = naga::front::spv::parse_u8_slice(&spv_bytes, &naga::front::spv::Options::default())
        .map_err(|e| format!("SPIR-V re-read failed after inserting the hash: {e}"))?;
    Validator::new(ValidationFlags::all(), Capabilities::all())
        .validate(&reread)
        .map_err(|e| format!("SPIR-V re-validation failed: {e:?}"))?;
    if recorded_spv_hash(&spv_bytes).as_deref() != Some(hash.as_str()) {
        return Err("SPIR-V: the recorded hash does not read back".into());
    }

    std::fs::create_dir_all(out).map_err(|e| format!("{}: {e}", out.display()))?;
    let head = header(&file, &hash);
    write(&metal_path, format!("{head}{msl_src}").as_bytes())?;
    write(&hlsl_path, format!("{head}{hlsl_src}").as_bytes())?;
    write(&spv_path, &spv_bytes)?;
    println!("wgsl-sha256 {hash}");
    for p in [&metal_path, &hlsl_path, &spv_path] {
        println!("  wrote {}", p.display());
    }
    Ok(())
}

/// brief-em3d-101 — naga's sampler heap rewritten into D3D11's model. naga declares
///   SamplerState nagaSamplerHeap[2048]: register(s0, space0);
///   SamplerComparisonState nagaComparisonSamplerHeap[2048]: register(s0, space1);
///   StructuredBuffer<uint> nagaGroup1SamplerIndexArray : register(t15);
///   static const SamplerState img_s = nagaSamplerHeap[nagaGroup1SamplerIndexArray[1]];
/// and every use names `img_s`. The three declarations go, and the static becomes `SamplerState img_s : register(s0);` — the
/// sampler's own binding-map register. Every pattern must match EXACTLY as expected, or generation fails: a naga upgrade that
/// changes the spelling is a loud error here, never a shader that silently samples nothing.
fn plain_hlsl_samplers(src: &str) -> Result<String, String> {
    let mut out = String::with_capacity(src.len());
    let (mut heaps, mut index, mut samplers) = (0, 0, 0);
    for line in src.split_inclusive('\n') {
        let t = line.trim();
        if t.starts_with("SamplerState nagaSamplerHeap[") || t.starts_with("SamplerComparisonState nagaComparisonSamplerHeap[") {
            heaps += 1;
            continue;
        }
        if t.starts_with("StructuredBuffer<uint> nagaGroup") && t.contains("SamplerIndexArray") {
            index += 1;
            continue;
        }
        if let Some(rest) = t.strip_prefix("static const SamplerState ") {
            let name = rest.split(|c: char| c == ' ' || c == '=').next().unwrap_or("");
            if name.is_empty() || !rest.contains("= nagaSamplerHeap[") {
                return Err(format!("HLSL: an unexpected sampler declaration: {t}"));
            }
            // Each sampler at its own binding-map register (HLSL_SAMPLERS): the image's s0, the environment's s1.
            let Some((_, reg)) = HLSL_SAMPLERS.iter().find(|(n, _)| *n == name) else {
                return Err(format!("HLSL: a sampler HLSL_SAMPLERS does not name: {name}"));
            };
            out.push_str(&format!("SamplerState {name} : register(s{reg});\n"));
            samplers += 1;
            continue;
        }
        out.push_str(line);
    }
    if samplers != HLSL_SAMPLERS.len() || heaps != 2 || index != HLSL_SAMPLERS.len() {
        return Err(format!(
            "HLSL: expected naga's two sampler heaps, an index buffer and a sampler for each of {}; found {heaps}, {index} and {samplers}",
            HLSL_SAMPLERS.len()
        ));
    }
    if out.contains("nagaSamplerHeap") || out.contains("SamplerIndexArray") {
        return Err("HLSL: the sampler heap is still referenced after the rewrite".into());
    }
    Ok(out)
}

fn write(p: &Path, b: &[u8]) -> Result<(), String> {
    std::fs::write(p, b).map_err(|e| format!("{}: {e}", p.display()))
}

/// Opcodes that may precede the end of the debug section's first group (logical layout §2.4:
/// capabilities, extensions, imports, memory model, entry points, execution modes, then debug 7a).
fn is_preamble_or_source_debug(op: u32) -> bool {
    // Capability 17, Extension 10, ExtInstImport 11, MemoryModel 14, EntryPoint 15, ExecutionMode 16,
    // ExecutionModeId 331; String 7, Source 3, SourceExtension 4, SourceContinued 2.
    matches!(op, 17 | 10 | 11 | 14 | 15 | 16 | 331 | 7 | 3 | 4 | 2)
}

/// Inserts `OpSourceExtension "<text>"` after the last 7a debug instruction and before the first
/// OpName (7b) — or the first annotation or type when there is no name — the place the layout allows it.
fn insert_hash_string(words: &[u32], text: &str) -> Result<Vec<u32>, String> {
    if words.len() < 5 || words[0] != 0x0723_0203 {
        return Err("SPIR-V: bad magic".into());
    }
    let mut i = 5;
    let mut at = None;
    while i < words.len() {
        let (count, op) = ((words[i] >> 16) as usize, words[i] & 0xffff);
        if count == 0 {
            return Err("SPIR-V: zero-length instruction".into());
        }
        if !is_preamble_or_source_debug(op) {
            at = Some(i);
            break;
        }
        i += count;
    }
    let at = at.ok_or("SPIR-V: no name, annotation or type section")?;
    let lit = string_words(text);
    let mut ins = vec![(((1 + lit.len()) as u32) << 16) | OP_SOURCE_EXTENSION];
    ins.extend(lit);
    let mut out = Vec::with_capacity(words.len() + ins.len());
    out.extend_from_slice(&words[..at]);
    out.extend(ins);
    out.extend_from_slice(&words[at..]);
    Ok(out)
}

/// A SPIR-V literal string: UTF-8, NUL-terminated, zero-padded to a word, little-endian in each word.
fn string_words(s: &str) -> Vec<u32> {
    let mut b = s.as_bytes().to_vec();
    b.push(0);
    while b.len() % 4 != 0 {
        b.push(0);
    }
    b.chunks(4).map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]])).collect()
}

/// The hash an `.spv` records, from its OpSourceExtension "wgsl-sha256:…" instruction.
fn recorded_spv_hash(bytes: &[u8]) -> Option<String> {
    if bytes.len() % 4 != 0 {
        return None;
    }
    let words: Vec<u32> = bytes.chunks(4).map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]])).collect();
    let mut i = 5;
    while i < words.len() {
        let (count, op) = ((words[i] >> 16) as usize, words[i] & 0xffff);
        if count == 0 {
            return None;
        }
        if op == OP_SOURCE_EXTENSION {
            let lit: Vec<u8> = words[i + 1..i + count].iter().flat_map(|w| w.to_le_bytes()).collect();
            let s = String::from_utf8_lossy(&lit[..lit.iter().position(|&c| c == 0).unwrap_or(lit.len())]).to_string();
            if let Some(h) = s.strip_prefix("wgsl-sha256:") {
                return Some(h.to_string());
            }
        }
        i += count;
    }
    None
}

fn recorded_text_hash(text: &str) -> Option<String> {
    let first = text.lines().next()?;
    first.split("wgsl-sha256: ").nth(1).map(|h| h.trim().to_string())
}

fn check(wgsl_path: &Path, out: &Path) -> Result<bool, String> {
    let bytes = std::fs::read(wgsl_path).map_err(|e| format!("{}: {e}", wgsl_path.display()))?;
    let hash = hex_sha256(&bytes);
    let (_, metal, hlsl, spv) = outputs(wgsl_path, out)?;
    let mut ok = true;
    for p in [&metal, &hlsl, &spv] {
        let recorded = match std::fs::read(p) {
            Err(e) => {
                println!("MISSING  {} ({e})", p.display());
                ok = false;
                continue;
            }
            Ok(b) if p.extension().is_some_and(|e| e == "spv") => recorded_spv_hash(&b),
            Ok(b) => recorded_text_hash(&String::from_utf8_lossy(&b)),
        };
        match recorded {
            Some(h) if h == hash => println!("current  {}", p.display()),
            Some(h) => {
                println!("STALE    {} records {h}, the WGSL is {hash}", p.display());
                ok = false;
            }
            None => {
                println!("NO HASH  {}", p.display());
                ok = false;
            }
        }
    }
    Ok(ok)
}
