using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Numerics;
using CircuitRF.Core.Elaboration;
using CircuitRF.Core.Netlist;
using CircuitRF.Engine;
using Xunit;

namespace CircuitRF.Engine.Tests.Devices;

/// <summary>
/// brief-via-component.md §6 gates 2, 5 and 6 — the VIA component through the engine, the path a
/// user's circuit takes.
/// </summary>
public class ViaSParamTests
{
    private const double Mu0 = 4e-7 * Math.PI;

    private static Complex[,] SAt(string cnl, double freqHz, out IReadOnlyList<string> warnings)
    {
        var (lib, tb) = new CnlReader().Read(cnl);
        var nl = new Elaborator(lib).Elaborate(tb);
        var s = SParameterEngine.Run(nl, [freqHz])["S"];
        warnings = nl.Warnings;
        return new[,] { { (Complex)s[0, 0, 0], (Complex)s[0, 0, 1] }, { (Complex)s[0, 1, 0], (Complex)s[0, 1, 1] } };
    }

    private static string F(double v) => v.ToString("R", CultureInfo.InvariantCulture);

    /// <summary>
    /// Gate 2. A VIA with one plane passed and a stub, against the same T built by hand out of R, L and C
    /// — every value computed HERE from the published formulas, not by the model — at three frequencies.
    /// </summary>
    [Theory]
    [InlineData(0.5e9)]
    [InlineData(3e9)]
    [InlineData(12e9)]
    public void AVia_IsTheRlcTeeItsFormulasDescribe(double f)
    {
        const double drill = 0.3e-3, pad = 0.6e-3, antipad = 1.0e-3, t = 25e-6, h = 1.2e-3, hs = 0.4e-3;
        const double sigma = 5.8e7, er = 4.4, tp = 0.5e-3, tsp = 0.2e-3;

        string via = $"""
            Port:P1 a 0 Num=1 Z=50 Ohm
            VIA:V1 a b Drill={F(drill)} Pad={F(pad)} Antipad={F(antipad)} Plating={F(t)} H={F(h)} Er={F(er)} Sigma={F(sigma)} Planes=1 Tp1={F(tp)} Erp1={F(er)} Hstub={F(hs)} StubPlanes=1 Tsp1={F(tsp)} Ersp1={F(er)}
            Port:P2 b 0 Num=2 Z=50 Ohm
            """;

        double r = drill / 2;
        double L(double len) { double q = Math.Sqrt(r * r + len * len); return Mu0 / (2 * Math.PI) * (len * Math.Log((len + q) / r) + 1.5 * (r - q)); }
        double R(double len) => len / (sigma * Math.PI * (r * r - (r - t) * (r - t))) * Math.Sqrt(1 + f * Math.PI * Mu0 * sigma * t * t);
        double C(double thickness) => 1.41 * er * (thickness / 0.0254) * pad / (antipad - pad) * 1e-12;

        string hand = $"""
            Port:P1 a 0 Num=1 Z=50 Ohm
            R:Ra a x1 R={F(R(h) / 2)} Ohm
            L:La x1 m L={F(L(h) / 2)}
            C:Cm m 0 C={F(C(tp))}
            L:Lb m x2 L={F(L(h) / 2)}
            R:Rb x2 b R={F(R(h) / 2)} Ohm
            R:Rs b y1 R={F(R(hs))} Ohm
            L:Ls y1 y2 L={F(L(hs))}
            C:Cs y2 0 C={F(C(tsp))}
            Port:P2 b 0 Num=2 Z=50 Ohm
            """;

        var a = SAt(via, f, out _);
        var b = SAt(hand, f, out _);
        for (int i = 0; i < 2; i++)
            for (int j = 0; j < 2; j++)
                Assert.True((a[i, j] - b[i, j]).Magnitude < 1e-9, $"S{i + 1}{j + 1} at {f / 1e9} GHz: {a[i, j]} vs {b[i, j]}");
    }

    [Fact]
    public void AViaToGround_IsItsBarrelToGround_WithThePadCapacitanceAcrossIt()
    {
        const double f = 2e9, drill = 0.3e-3, pad = 0.6e-3, antipad = 0.9e-3, h = 1.6e-3, er = 4.4;
        string via = $"""
            Port:P1 a 0 Num=1 Z=50 Ohm
            VIAGND:V1 a 0 Drill={F(drill)} Pad={F(pad)} Antipad={F(antipad)} H={F(h)} Er={F(er)}
            """;
        double r = drill / 2, q = Math.Sqrt(r * r + h * h), t = 25e-6, sigma = 5.8e7;
        double l = Mu0 / (2 * Math.PI) * (h * Math.Log((h + q) / r) + 1.5 * (r - q));
        double rr = h / (sigma * Math.PI * (r * r - (r - t) * (r - t))) * Math.Sqrt(1 + f * Math.PI * Mu0 * sigma * t * t);
        double c = 1.41 * er * (h / 0.0254) * pad / (antipad - pad) * 1e-12;
        string hand = $"""
            Port:P1 a 0 Num=1 Z=50 Ohm
            R:R1 a x R={F(rr)} Ohm
            L:L1 x 0 L={F(l)}
            C:C1 a 0 C={F(c)}
            """;

        var (lib1, tb1) = new CnlReader().Read(via);
        var (lib2, tb2) = new CnlReader().Read(hand);
        var s1 = (Complex)SParameterEngine.Run(new Elaborator(lib1).Elaborate(tb1), [f])["S"][0, 0, 0];
        var s2 = (Complex)SParameterEngine.Run(new Elaborator(lib2).Elaborate(tb2), [f])["S"][0, 0, 0];
        Assert.True((s1 - s2).Magnitude < 1e-9, $"{s1} vs {s2}");
    }

    /// <summary>
    /// Gate 5. MLIN + VIA + MLIN against the committed, independently generated Palace solve of the same
    /// transition (testdata/em3d/f0/B-via: a 400 µm microstrip on top, a solid 300 µm via through a
    /// 900 µm clearance in the middle ground plane, an inverted microstrip underneath; order-2 elements,
    /// never regenerated by circuitRF). Every value on the circuit side is what the stackup gives —
    /// the via's plane term is the 200 µm of barrel the plane owns (half the dielectric either side).
    ///
    /// <para>Measured when written: |S21| within 0.031 dB and ∠S21 within 0.17° at every point.
    /// |S11| is where the model is weakest (about −25 dB against Palace's −44 dB at 6 GHz): its L is low
    /// and its C high against the de-embedded transition, and the two errors partly cancel in S21. That
    /// is recorded in the component's help rather than asserted here.</para>
    /// </summary>
    [Fact]
    public void MlinViaMlin_AgreesWithThePalaceSolveOfTheSameTransition()
    {
        const string cnl = """
            Port:P1 in 0 Num=1 Z=50 Ohm
            MLIN:ML1 in a W=400e-6 L=5e-3 H=200e-6 T=35e-6 Er=3.66 TanD=0.004 Sigma=5.8e7
            VIA:V1 a b Drill=300e-6 Pad=600e-6 Antipad=900e-6 H=470e-6 Er=3.66 Sigma=5.8e7 Solid=1 Planes=1 Tp1=200e-6 Erp1=3.66
            MLIN:ML2 b out W=400e-6 L=5e-3 H=200e-6 T=35e-6 Er=3.66 TanD=0.004 Sigma=5.8e7
            Port:P2 out 0 Num=2 Z=50 Ohm
            """;
        var reference = ReadS21(Path.Combine(RepoRoot(), "testdata", "em3d", "f0", "B-via", "palace", "reference.s2p"));

        foreach (double ghz in new[] { 1.2, 2.4, 3.6, 4.8, 6.0 })
        {
            var s21 = SAt(cnl, ghz * 1e9, out _)[1, 0];
            var r = reference[ghz];
            double dDb = 20 * Math.Log10(s21.Magnitude / r.Magnitude);
            double dDeg = (s21 / r).Phase * 180 / Math.PI;
            Assert.True(Math.Abs(dDb) < 0.1, $"|S21| at {ghz} GHz is {dDb:+0.000;-0.000} dB from Palace");
            Assert.True(Math.Abs(dDeg) < 3, $"∠S21 at {ghz} GHz is {dDeg:+0.00;-0.00}° from Palace");
        }
    }

    /// <summary>Gate 6. A 1.6 mm barrel in εr 4.4 is a twentieth of a wavelength at 4.5 GHz: a sweep past it
    /// warns once for the instance, however many points lie beyond; a sweep below it says nothing.</summary>
    [Fact]
    public void AViaSweptPastItsLumpedLimit_WarnsExactlyOnce()
    {
        const string cnl = """
            Port:P1 a 0 Num=1 Z=50 Ohm
            VIA:V1 a b H=1.6e-3 Er=4.4
            Port:P2 b 0 Num=2 Z=50 Ohm
            """;
        var (lib, tb) = new CnlReader().Read(cnl);
        var nl = new Elaborator(lib).Elaborate(tb);
        SParameterEngine.Run(nl, [1e9, 3e9, 6e9, 9e9, 12e9]);
        var viaWarnings = nl.Warnings.Where(w => w.Contains("twentieth of the wavelength")).ToList();
        Assert.Single(viaWarnings);
        Assert.Contains("V1", viaWarnings[0]);

        var (lib2, tb2) = new CnlReader().Read(cnl);
        var below = new Elaborator(lib2).Elaborate(tb2);
        SParameterEngine.Run(below, [1e9, 3e9]);
        Assert.DoesNotContain(below.Warnings, w => w.Contains("twentieth of the wavelength"));
    }

    private static string RepoRoot()
    {
        string dir = AppContext.BaseDirectory;
        while (dir.Length > 0 && !Directory.Exists(Path.Combine(dir, "testdata", "em3d")))
            dir = Path.GetDirectoryName(dir) ?? "";
        return dir;
    }

    private static Dictionary<double, Complex> ReadS21(string path)
    {
        var d = new Dictionary<double, Complex>();
        foreach (var line in File.ReadLines(path))
        {
            if (line.StartsWith('!') || line.StartsWith('#') || line.Trim().Length == 0) continue;
            var v = line.Split(' ', StringSplitOptions.RemoveEmptyEntries).Select(x => double.Parse(x, CultureInfo.InvariantCulture)).ToArray();
            d[Math.Round(v[0], 3)] = new Complex(v[3], v[4]);
        }
        return d;
    }
}
